### ISSUE TITLE
Recommendation for "The underlying connection was closed: The connection was closed unexpectedly"

### ISSUE THREAD

**Issue by danilobreda** [TykTechnologies/tyk#1033]
On Gateway v2.3.3:
When i try to create a key using Oauth and the Api is duplicated or configured wrong i get:

`2017/08/24 20:51:54 http: panic serving 172.31.10.5:63060: runtime error: invalid memory address or nil pointer dereference
goroutine 4795 [running]:
net/http.(*conn).serve.func1(0xc420ef7200)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xcc7600, 0xc42000c0c0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
main.(*DefaultSessionManager).ResetQuota(0xc4204322d0, 0xc420e7f4c0, 0x38, 0x0, 0x408f400000000000, 0x408f400000000000, 0x3ff0000000000000, 0x599f6881, 0xffffffffffffffff, 0x599f6872, ...)
        /src/github.com/TykTechnologies/tyk/auth_manager.go:110 +0x452
main.createKeyHandler(0x12b3220, 0xc4210ee750, 0xc420c48780)
        /src/github.com/TykTechnologies/tyk/api.go:1340 +0x28c4
main.InstrumentationMW.func1(0x12b3220, 0xc4210ee750, 0xc420c48780)
        /src/github.com/TykTechnologies/tyk/instrumentation_handlers.go:54 +0x97
main.CheckIsAPIOwner.func1(0x12b3220, 0xc4210ee750, 0xc420c48780)
        /src/github.com/TykTechnologies/tyk/middleware_api_security_handler.go:24 +0x2ae
net/http.HandlerFunc.ServeHTTP(0xc4205b4790, 0x12b3220, 0xc4210ee750, 0xc420c48780)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420415bd0, 0x12b3220, 0xc4210ee750, 0xc420c48780)
        /src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10d
net/http.(*ServeMux).ServeHTTP(0x1379780, 0x12b3220, 0xc4210ee750, 0xc420c485a0)
        /usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420fdb200, 0x12b3220, 0xc4210ee750, 0xc420c485a0)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420ef7200, 0x12b42a0, 0xc420e7f2c0)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
`

This is not good for Integrators (like me that uses , because the return is a "connection interrupted error". 
For a better integration on REST principles I would like to request a recommendation to return a 500 or somehting like that for this kind of error.
I took 3 guys all day to resolve this issue. And i lost a customer for that reason. The real error on the end was that the api was duplicated on the endpoint. Human error. Thanks.

**Comment by lonelycode** [comment]
> I took 3 guys all day to resolve this issue. And i lost a customer for that reason. 

Sorry to hear that, it is unfortunate.

>The real error on the end was that the api was duplicated on the endpoint. Human error.  

We can't protect against that

Were you using the dashboard for integration? If you were using the Dashboard, then it shouldn't have allowed you to add a duplicate API. The Gateway doesn't have that many checks for dupes except for when the APIs get loaded. 

v2.3.4 of the gateway improved dupe detection even more, so you might want to try that.

A panic is never good, so we'll make sure we clean that up.

**Comment by danilobreda** [comment]
Thanks lonelycode... sorry for my my late comment. I will update my dashboard and gateway to the latest version.
I dont know if i need to close the issue or not, its only a recommendation for that kind of error, i think you get it.
