### ISSUE TITLE
Activating a response middleware causes a panic

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1041]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I use response middleware (e.g. body transform), the gateway panics

**What is the expected behavior?**
It should not panic

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create an API
2. Add a response transform to a path
3. Start gateway
4. Make request 
5. Panic

Output:

```
2017/08/29 04:14:25 http: panic serving 172.18.0.1:51626: runtime error: invalid memory address or nil pointer dereference
goroutine 11912 [running]:
net/http.(*conn).serve.func1(0xc421898fa0)
        /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xc85500, 0x131dd30)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
main.(*APISpec).Version(0x0, 0xc4200dbf00, 0x4, 0xd, 0x1, 0xc423782f60, 0xc4233d2d50, 0xc422ccc7c0, 0x0)
        /develop/go/src/github.com/TykTechnologies/tyk/api_definition.go:1068 +0xe0
main.(*ResponseTransformMiddleware).HandleResponse(0xc4233dedd0, 0x126c6e0, 0xc421564000, 0xc4230ff5f0, 0xc4200dbf00, 0xc42186f8c0, 0x0, 0x0)
        /develop/go/src/github.com/TykTechnologies/tyk/res_handler_transform.go:38 +0x6b
main.handleResponseChain(0xc4233dedc0, 0x1, 0x1, 0x126c6e0, 0xc421564000, 0xc4230ff5f0, 0xc4200dbf00, 0xc42186f8c0, 0xc422565ea0, 0xc423782cc4)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:142 +0x8f
main.(*ReverseProxy).WrappedServeHTTP(0xc422f9c740, 0x126c6e0, 0xc421564000, 0xc4200dbf00, 0x59a4ea00, 0x0)
        /develop/go/src/github.com/TykTechnologies/tyk/reverse_proxy.go:601 +0x18a2
main.(*ReverseProxy).ServeHTTP(0xc422f9c740, 0x126c6e0, 0xc421564000, 0xc4200dbf00, 0x0)
        /develop/go/src/github.com/TykTechnologies/tyk/reverse_proxy.go:362 +0x60
main.(*SuccessHandler).ServeHTTP(0xc42000f0b8, 0x126c6e0, 0xc421564000, 0xc4200dbf00, 0x0)
        /develop/go/src/github.com/TykTechnologies/tyk/handler_success.go:338 +0x174
main.(*DummyProxyHandler).ServeHTTP(0xc42000f0b8, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/api_loader.go:553 +0x4b
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c800, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c840, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c880, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c8c0, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c900, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c940, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c980, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c9c0, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9ca00, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202fcb40, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.(*ServeMux).ServeHTTP(0xc4233c7320, 0x126c6e0, 0xc421564000, 0xc422ff7100)
        /usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4203a7970, 0x126c6e0, 0xc421564000, 0xc422ff7100)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc421898fa0, 0x126d4e0, 0xc4232b68c0)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master

**Comment by mvdan** [comment]
Found the fix to this by chance, so assigning to self.

**Comment by mvdan** [comment]
Also, this regression was introduced by me in this refactor: d5401d913c4c45e90d362be05cbcba2f7e433138

The func used to receive the object and return it too, and I removed the return. But this one slipped past me (and we had no tests).

**Comment by ilijabojanovic** [comment]
Branch: Master
rev:  d83299a758a5f28f789111b676ff4248f23dd60a

I can still reproduce this issue.

Here is testing api definition:
```
{
    "id": "59ba8291b44d9901d3cd66bb",
    "name": "test3",
    "slug": "test3",
    "api_id": "c5635579fc1b4e3e56db777e03ff0e3f",
    "org_id": "59ba58daf1c5e702d237b293",
    "use_keyless": true,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": ""
    },
    "use_basic_auth": false,
    "enable_jwt": false,
    "use_standard_auth": false,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {
                    "transform": [
                        {
                            "template_data": {
                                "input_type": "xml",
                                "template_mode": "blob",
                                "enable_session": false,
                                "template_source": "ewogICAge3tyYW5nZSAkeCwgJHMgOj0gLnNlcnZlcnMuc2VydmVyfX0gICAgInt7JHMuc2VydmVyTmFtZX19IjogInt7JHMuc2VydmVySVB9fSJ7e2lmIG5vdCAkeH19LHt7ZW5kfX0KICAgIHt7ZW5kfX0KICAgIH0="
                            },
                            "path": "/ip",
                            "method": "GET"
                        }
                    ]
                },
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/test3/",
        "target_url": "http://httpbin.org/",
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "hostname",
            "port_data_path": "port",
            "target_path": "/api-slug",
            "use_target_list": false,
            "cache_timeout": 60,
            "endpoint_returns_list": false
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false
    },
    "session_lifetime": 0,
    "active": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": null
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false,
    "config_data": {}
}
```
Trigger GET call to /ip endpoint 

Gateway will crash without panic. In log i just have this:

```
tyk-gateway_1    | /develop/start/entrypoint.sh: line 22:   518 Killed                  ./tyk --conf=/develop/confs/tyk.conf --debug --httpprofile
compose_tyk-gateway_1 exited with code 137
```

**Comment by mvdan** [comment]
Thanks, will have another look.

**Comment by mvdan** [comment]
Huh, I just hit an out-of-memory crash. At least the original issue is fixed.

**Comment by mvdan** [comment]
@ilijabojanovic you have an issue in your config - you want `"transform_response": [`, as `"transform"` is a path transform, not a response one. With that fix, it works fine here.

Nevertheless, the setup you had made Tyk crash in a bad way. Please open a separate issue about it.

**Comment by mvdan** [comment]
(also, yes the names are quite confusing - it's probably an artifact of the order in which these features were introduced)

**Comment by ilijabojanovic** [comment]
@mvdan @lonelycode Response transform working fine after this fix. I will open separate task for Request transform
