### ISSUE TITLE
Tyk gateway runtime error

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#1045]
**Do you want to request a *feature* or report a *bug*?**
bug?
**What is the current behavior?**
Tyk gateway service unable to bring up. Errors as below
```
time="Aug 29 08:21:44" level=info msg="Connection dropped, connecting.." 
time="Aug 29 08:21:44" level=info msg="PIDFile location set to: /var/run/tyk-gateway.pid" 
time="Aug 29 08:21:44" level=error msg="Instrumentation is enabled, but no connectionstring set for statsd" 
time="Aug 29 08:21:44" level=info msg="Initialising Tyk REST API Endpoints" 
time="Aug 29 08:21:44" level=info msg="--> Standard listener (http)" 
time="Aug 29 08:21:44" level=info msg="Setting up Server" 
time="Aug 29 08:21:44" level=info msg="Registering node." 
time="Aug 29 08:21:44" level=info msg="Node registered" id=61dcbb98-408a-44b4-70a1-54dc02815f10 
time="Aug 29 08:21:44" level=info msg="Initialising distributed rate limiter" 
time="Aug 29 08:21:44" level=info msg="Starting gateway rate imiter notifications..." 
time="Aug 29 08:21:44" level=warning msg="Insecure configuration detected (allowing)!" 
time="Aug 29 08:21:44" level=info msg="Using /opt/tyk-gateway/tyk.conf for configuration" 
time="Aug 29 08:21:44" level=info msg="Detected 8 APIs" 
time="Aug 29 08:21:44" level=info msg="Loading API configurations." 
time="Aug 29 08:21:44" level=info msg="Tracking hostname" api_name="Portal Assets" domain=www.tyk-portal-test.com 
time="Aug 29 08:21:44" level=info msg="Tracking hostname" api_name="Portal API" domain=www.tyk-portal-test.com 
time="Aug 29 08:21:44" level=info msg="Tracking hostname" api_name=Portal domain=www.tyk-portal-test.com 
time="Aug 29 08:21:44" level=info msg="Tracking hostname" api_name=test2 domain="(no host)" 
time="Aug 29 08:21:44" level=info msg="Tracking hostname" api_name=test domain="(no host)" 
time="Aug 29 08:21:44" level=info msg="Tracking hostname" api_name="Portal API" domain=www.tyk-portal-test.com 
time="Aug 29 08:21:44" level=info msg="Loading API" api_name=Portal 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42cfbb]

goroutine 332 [running]:
panic(0xccaae0, 0xc420010070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.processSpec(0xc420270320, 0xc4203c5770, 0x5, 0xc420ceb5e0, 0xc420ceb600, 0xc420ceb620, 0xc420940b40, 0xc420940ba0, 0xc4203c5770, 0xc420280ee8)
	/src/github.com/TykTechnologies/tyk/api_loader.go:149 +0x5bb
main.loadApps.func1(0xc420bc32a0, 0xc4201288d8, 0xc420ceb5e0, 0xc420ceb600, 0xc420ceb620, 0xc420940b40, 0xc420940ba0, 0xc420940c00, 0xc420270320, 0x5, ...)
	/src/github.com/TykTechnologies/tyk/api_loader.go:646 +0x10a
created by main.loadApps
	/src/github.com/TykTechnologies/tyk/api_loader.go:649 +0x4eb
```
Such error just come hours ago, and it was normal before that.
**What is the expected behavior?**
gateway running without such error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Latest docker images.

**Comment by mvdan** [comment]
As explained in the forums, this is a dup of #938 and the bug was fixed in 2.3.8. Please update to the latest version.
