### ISSUE TITLE
Key generation session issue

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#1063]
Gateway branch: Master
Dashboard branch: Refactoring
Version: On-prem

Reproduction steps:

1. Create token protected api over dashboard api
2. Create key request for that api over api and trigger request

Actual:
Dashboard api returns this response:
```
{"Status":"Error","Message":"Failed to save new session object to Tyk: Failed to create key: Post http://tyk-gateway:8181/tyk/keys/create: EOF","Meta":null}
```
In gateway console we have this:
```
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=debug msg="Inbound redis event received" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=debug msg="Inbound redis event received" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=info msg="Reloading endpoints" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=info msg="Reload queued" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=info msg="Initiating reload" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=info msg="Loading policies" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=info msg="Using Policies from Dashboard Service" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=info msg="Mutex lock acquired... calling" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=info msg="Calling dashboard service for policy list" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=debug msg="Loading Policies Finished: Nonce Set: NDJmMmYwMjctNTc2Zi00NzY4LTUwZDktYTUzZmRlNWUyOTRiMTI5ZjJkOTI1NTQ1NDMxNjUyODk2YzEzYTk2OThmZjI=" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=info msg="Processing policy list" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=debug msg="Calling: http://tyk-dashboard:3000/system/apis" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=debug msg="Using: NodeID: 42f2f027-576f-4768-50d9-a53fde5e294b" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=info msg="Reset quota for key." inbound-key="****c335" key=quota-bb69b66e 
�[36mtyk-gateway_1    |�[0m 2017/09/02 16:17:07 http: panic serving 172.18.0.6:50938: runtime error: invalid memory address or nil pointer dereference
�[36mtyk-gateway_1    |�[0m goroutine 755 [running]:
�[36mtyk-gateway_1    |�[0m net/http.(*conn).serve.func1(0xc42050c640)
�[36mtyk-gateway_1    |�[0m 	/usr/local/go/src/net/http/server.go:1721 +0xd0
�[36mtyk-gateway_1    |�[0m panic(0xc864c0, 0x131fd30)
�[36mtyk-gateway_1    |�[0m 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
�[36mtyk-gateway_1    |�[0m main.(*DefaultSessionManager).ResetQuota(0x13467d0, 0xc4205e8e00, 0x38, 0xc42070adc0)
�[36mtyk-gateway_1    |�[0m 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:101 +0x471
�[36mtyk-gateway_1    |�[0m main.createKeyHandler(0x126e760, 0xc42025c380, 0xc4204e4800)
�[36mtyk-gateway_1    |�[0m 	/develop/go/src/github.com/TykTechnologies/tyk/api.go:925 +0x29dc
�[36mtyk-gateway_1    |�[0m main.allowMethods.func1(0x126e760, 0xc42025c380, 0xc4204e4800)
�[36mtyk-gateway_1    |�[0m 	/develop/go/src/github.com/TykTechnologies/tyk/api.go:62 +0x172
�[36mtyk-gateway_1    |�[0m net/http.HandlerFunc.ServeHTTP(0xc4204fe060, 0x126e760, 0xc42025c380, 0xc4204e4800)
�[36mtyk-gateway_1    |�[0m 	/usr/local/go/src/net/http/server.go:1942 +0x44
�[36mtyk-gateway_1    |�[0m github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420288050, 0x126e760, 0xc42025c380, 0xc4204e4800)
�[36mtyk-gateway_1    |�[0m 	/develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
�[36mtyk-gateway_1    |�[0m main.InstrumentationMW.func1(0x126e760, 0xc42025c380, 0xc4204e4600)
�[36mtyk-gateway_1    |�[0m 	/develop/go/src/github.com/TykTechnologies/tyk/instrumentation_handlers.go:51 +0xab
�[36mtyk-gateway_1    |�[0m net/http.HandlerFunc.ServeHTTP(0xc4204d9900, 0x126e760, 0xc42025c380, 0xc4204e4600)
�[36mtyk-gateway_1    |�[0m 	/usr/local/go/src/net/http/server.go:1942 +0x44
�[36mtyk-gateway_1    |�[0m main.checkIsAPIOwner.func1(0x126e760, 0xc42025c380, 0xc4204e4600)
�[36mtyk-gateway_1    |�[0m 	/develop/go/src/github.com/TykTechnologies/tyk/main.go:345 +0x1ef
�[36mtyk-gateway_1    |�[0m net/http.HandlerFunc.ServeHTTP(0xc4204d9920, 0x126e760, 0xc42025c380, 0xc4204e4600)
�[36mtyk-gateway_1    |�[0m 	/usr/local/go/src/net/http/server.go:1942 +0x44
�[36mtyk-gateway_1    |�[0m net/http.StripPrefix.func1(0x126e760, 0xc42025c380, 0xc4204e4600)
�[36mtyk-gateway_1    |�[0m 	/usr/local/go/src/net/http/server.go:1977 +0xcf
�[36mtyk-gateway_1    |�[0m net/http.HandlerFunc.ServeHTTP(0xc4204d7800, 0x126e760, 0xc42025c380, 0xc4204e4600)
�[36mtyk-gateway_1    |�[0m 	/usr/local/go/src/net/http/server.go:1942 +0x44
�[36mtyk-gateway_1    |�[0m github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420228c80, 0x126e760, 0xc42025c380, 0xc4204e4600)
�[36mtyk-gateway_1    |�[0m 	/develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
�[36mtyk-gateway_1    |�[0m net/http.(*ServeMux).ServeHTTP(0xc4202eb440, 0x126e760, 0xc42025c380, 0xc4204e4400)
�[36mtyk-gateway_1    |�[0m 	/usr/local/go/src/net/http/server.go:2238 +0x130
�[36mtyk-gateway_1    |�[0m net/http.serverHandler.ServeHTTP(0xc4201ec630, 0x126e760, 0xc42025c380, 0xc4204e4400)
�[36mtyk-gateway_1    |�[0m 	/usr/local/go/src/net/http/server.go:2568 +0x92
�[36mtyk-gateway_1    |�[0m net/http.(*conn).serve(0xc42050c640, 0x126f560, 0xc4205e8ac0)
�[36mtyk-gateway_1    |�[0m 	/usr/local/go/src/net/http/server.go:1825 +0x612
�[36mtyk-gateway_1    |�[0m created by net/http.(*Server).Serve
�[36mtyk-gateway_1    |�[0m 	/usr/local/go/src/net/http/server.go:2668 +0x2ce
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=debug msg="INITIALISING EVENT HANDLERS" 
�[36mtyk-gateway_1    |�[0m time="Sep  2 16:17:07" level=debug msg="Checking for transform paths..." 
```

**Comment by mvdan** [comment]
@ilijabojanovic does this happen after you trigger a reload? do you have any api definitions loaded in the gateway?

**Comment by ilijabojanovic** [comment]
@mvdan Yes i have only one api def loaded on gateway and this happening only first key generation request.  If i trigger same call again gateway will generate and return key in response.

**Comment by mvdan** [comment]
See above - have you tried doing a reload before the first key generation request?

What about waiting for one minute before doing the first call, in case the issue is that we're not waiting for Redis to be ready?

**Comment by ilijabojanovic** [comment]
@mvdan yes, since reload is triggered after we add api def. I will try to reload twice before i submit request for key

**Comment by mvdan** [comment]
This is working as intended, sort of. The thing is that this was an automated test, trying to generate a key and using it immediately after the API had been created. A reload had been triggered, but not a blocking one.

Hence, the reload may not be done when the request comes in - which is the case here - and the request fails in a funny way.

The fix is to use a blocking reload as introduced in master, i.e. `/tyk/reload?block=true`. Adding a one-second sleep also worked, but that's a bit hacky.
