### ISSUE TITLE
Panic with policy request auth failure

### ISSUE THREAD

**Issue by MangoMM** [TykTechnologies/tyk#1179]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When calling hot reload via API

```
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Reload URL Structure - Scheduled" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Reload queued" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Initiating reload" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Loading policies" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Using Policies from Dashboard Service" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Mutex lock acquired... calling" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Calling dashboard service for policy list" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=error msg="Policy request login failure, Response was: {\"Status\":\"Error\",\"Message\":\"Authorization failed (Nonce empty)\",\"Meta\":null}\n" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Registering node (again)." 
tyk-gateway_1    | panic: runtime error: invalid memory address or nil pointer dereference
tyk-gateway_1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xb1215f]
tyk-gateway_1    | 
tyk-gateway_1    | goroutine 109 [running]:
tyk-gateway_1    | main.reLogin()
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/dashboard_register.go:43 +0x1df
tyk-gateway_1    | main.LoadPoliciesFromDashboard(0xc42030db00, 0x29, 0xc4201f8000, 0x20, 0xc42030db01, 0x0)
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/policy.go:130 +0x150a
tyk-gateway_1    | main.getPolicies()
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/main.go:248 +0xb58
tyk-gateway_1    | main.doReload()
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/main.go:551 +0x37
tyk-gateway_1    | main.reloadLoop(0xc4205147e0)
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/main.go:604 +0x102
tyk-gateway_1    | created by main.start
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/main.go:1081 +0x180
compose_tyk-gateway_1 exited with code 2
```

**What is the expected behavior?**
Should not panic

**Comment by mvdan** [comment]
@MangoMM as said, feel free to work on this issue and ping me if you need assistance.
