### ISSUE TITLE
Caching endpoints causing panics and crash on gateway

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#1327]
Branch: Stable 2.4 and master
Env: All

**UPDATED**
When we enable caching on endpoint on second call to cached endpoint kills gateway.

In order to reproduce issue we must enable detailed recording in tyk.conf:
"analytics_config":{
    "enable_detailed_recording": true,

Reproduction steps:
1. Log on dashboard 
2. Go to apis
3. Create keyless or protected api
4. Enable caching for some endpoint endpoint designer 
5. Update api def
6. Trigger two or three requests to api with caching enabled on endpoint 

Actual:
Gateway will crash 

```
tyk-gateway_1    | time="Nov 29 21:11:29" level=debug msg="Expires: 2017-11-29 21:12:20 +0000 UTC"
tyk-gateway_1    | time="Nov 29 21:11:29" level=debug msg="Cache got: HTTP/1.1 200 OK\r\nContent-Length: 44\r\nAccess-Control-Allow-Credentials: true\r\nAccess-Control-Allow-Origin: *\r\nConnection: close\r\nContent-Type: application/json\r\nDate: Wed, 29 Nov 2017 21:10:59 GMT\r\nServer: meinheld/0.6.1\r\nVia: 1.1 vegur\r\nX-Powered-By: Flask\r\nX-Processed-Time: 0.000761032104492\r\nX-Ratelimit-Limit: 0\r\nX-Ratelimit-Remaining: 0\r\nX-Ratelimit-Reset: 0\r\n\r\n{\n  \"origin\": \"172.18.0.1, 46.240.145.17\"\n}\n"
tyk-gateway_1    | time="Nov 29 21:11:29" level=debug msg="Could not get session detail, key not found" err="key not found" inbound-key="****05fc"
tyk-gateway_1    | time="Nov 29 21:11:29" level=debug msg="No session for org, skipping"
tyk-gateway_1    | panic: runtime error: invalid memory address or nil pointer dereference
tyk-gateway_1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6b652a]
tyk-gateway_1    |
tyk-gateway_1    | goroutine 742458 [running]:
tyk-gateway_1    | net/http.(*Response).Write(0x0, 0x1541180, 0xc4201a01c0, 0x17c, 0xc420b88b60)
tyk-gateway_1    | 	/usr/local/go/src/net/http/response.go:234 +0x3a
tyk-gateway_1    | main.(*SuccessHandler).RecordHit(0xc420187968, 0xc420637300, 0x0, 0xc8, 0xc420637500, 0x0)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/handler_success.go:115 +0x9cb

tyk-gateway_1    | created by main.(*RedisCacheMiddleware).ProcessRequest
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/mw_redis_cache.go:261 +0x1487

compose_tyk-gateway_1 exited with code 2
```

**Comment by lonelycode** [comment]
@ilijabojanovic I just tried this on Tyk Cloud:

1. Create an API and enable caching
2. Add an endpoint that is cached (e.g. get)
3. Create a key to access this API with
4. Send a request to the gateway, see the headers, there is no `x-tyk-cached-response` header
5. Send a second request: get a `x-tyk-cached-response` header:

```
curl -v "https://tyk-inc-portal-test.cloud.tyk.io/cacheme/get?auth=xxxx"
* Hostname was NOT found in DNS cache
*   Trying 34.200.195.179...
* Connected to tyk-inc-portal-test.cloud.tyk.io (34.200.195.179) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: CN=*.cloud.tyk.io
*        start date: 2017-02-06 00:00:00 GMT
*        expire date: 2018-03-06 12:00:00 GMT
*        subjectAltName: tyk-inc-portal-test.cloud.tyk.io matched
*        issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*        SSL certificate verify ok.
> GET /cacheme/get?auth=xxxxHTTP/1.1
> User-Agent: curl/7.35.0
> Host: tyk-inc-portal-test.cloud.tyk.io
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Date: Wed, 29 Nov 2017 21:50:40 GMT
* Server meinheld/0.6.1 is not blacklisted
< Server: meinheld/0.6.1
< Via: 1.1 vegur
< X-Powered-By: Flask
< X-Processed-Time: 0.001305103302
< X-Ratelimit-Limit: -1
< X-Ratelimit-Remaining: -1
< X-Ratelimit-Reset: 1511994854
< X-Tyk-Cached-Response: 1
< Content-Length: 495
< Connection: keep-alive
<
{
  "args": {
    "auth": "xxxx"
  },
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.35.0",
    "X-Scheme": "https",
    "X-Test": "hello"
  },
  "origin": "203.211.126.161, 203.211.126.161, 172.30.2.234, 172.30.0.152, 54.172.196.251",
  "url": "http://httpbin.org/get?auth=55d5927329415b000100003bf4971f18f1a74527987134859e261613"
}
* Connection #0 to host tyk-inc-portal-test.cloud.tyk.io left intact
```

When I tested with the "Cache all safe requests" it did not work, but a specific endpoint did. Also, the gateway should have 500 errored if it crashed, and cloud isn't crashing, it is servicing the requests.

So it looks like it is working.

Do you have detailed recording enabled? [It looks like that is causing the crash](https://github.com/TykTechnologies/tyk/blob/master/handler_success.go#L108)?
