### ISSUE TITLE
Page not found during setup

### ISSUE THREAD

**Issue by kangaroozal** [TykTechnologies/tyk#142]
The following gist was working only a few days ago: https://gist.github.com/lonelycode/4f645c4733faaa74d8fd

Now when I run that same gist I receive the following error on line: https://gist.github.com/lonelycode/4f645c4733faaa74d8fd#file-tyk_quickstart-sh-L53

```
...
Pulling latest containers
latest: Pulling from library/redis
Digest: sha256:4f80d4304d2e83fdc72fc23a457a901e0b8fe1a4aca163d52ca67a02b06b07af
Status: Image is up to date for redis:latest
latest: Pulling from library/mongo
Digest: sha256:223d59692269be18696be5c4f48e3d4117c7f11e175fe760f6b575387abc1bba
Status: Image is up to date for mongo:latest
latest: Pulling from tykio/tyk-gateway
Digest: sha256:a9f461726eb9f1b20f1b9df0e533eedefbcf52d9d2e85328cf4a45e30cba634a
Status: Image is up to date for tykio/tyk-gateway:latest
latest: Pulling from tykio/tyk-dashboard
Digest: sha256:817fa70efb8eb417b97777c345635a6e8773b612505241916be16f911ac44980
Status: Image is up to date for tykio/tyk-dashboard:latest
latest: Pulling from tykio/tyk-host-manager
Digest: sha256:adb24932ff8f5b3273bbc5ec63f971f4ab6935d11005053b26eef9f1c271362c
Status: Image is up to date for tykio/tyk-host-manager:latest
Setting up Mongo and Redis
5cb75fb611523069c8baa6fd085e2212baa3278d0e244b3cc943c281ebd1ef32
d52c243f825a28364642701325f2397791a6f8c54c7161200daef81923ce55a2
Setting up Tyk gateway
93d9fa238aafd87cac358397ed0b5d608923b3b3305a2331a404e3a11765d337
Setting up Tyk dashboard
c43f87b506884d0635fd54f6498d4212314202e7cfed0b2fdaf2f8be365fa83c
Setting up NginX and Host Manager
e347ef4d37b246684eb5d0cc2350da9c7509b39458080f354866193108cb47d9
Creating Organisation
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)
ORGID:

```

When I attempt to navigate to http://$HOST_IP:3000 I get a page not found error. 

Any advice to point me in the right direction would be awesome!

**Comment by lonelycode** [comment]
Wow that gist is ancient and hasn't been maintained in a loooong time. 

It also assumes a certain version of Tyk (0.8 I think), suggest you take a look at our official QuickStart for docker which uses docker compose to bootstrap everything:

**Comment by lonelycode** [comment]
Forgot to add the link: https://tyk.io/v1.9/setup/docker/

**Comment by kangaroozal** [comment]
Awesome! thank you so much for the rapid response!
