### ISSUE TITLE
Gateway panics on advanced url rewrite

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#1420]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Gateway panics on url rewrite mach
**What is the expected behavior?**
Gateway should not panic
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Import Api definition 
2. Trigger call to /get?
3. Observe gateway log

Error:
```
tyk-gateway_1    | time="Jan 23 15:19:00" level=debug msg="Rewriter active"
tyk-gateway_1    | time="Jan 23 15:19:00" level=debug msg="/rewrite/get?show_env=1"
tyk-gateway_1    | time="Jan 23 15:19:00" level=debug msg="Inbound path: /rewrite/get?show_env=1"
tyk-gateway_1    | time="Jan 23 15:19:00" level=debug msg="[STORE] SET Raw key is: 5a61d6e6bc26e7032439ce2008408b5621764b8bbac3b9f6a1680ed4"
tyk-gateway_1    | time="Jan 23 15:19:00" level=debug msg="[STORE] Setting key: apikey-f998c5ef"
tyk-gateway_1    | time="Jan 23 15:19:00" level=debug msg="[STORE] SET Raw key is: 5a61d6e6bc26e7032439ce2008408b5621764b8bbac3b9f6a1680ed4"
tyk-gateway_1    | time="Jan 23 15:19:00" level=debug msg="[STORE] Setting key: apikey-f998c5ef"
tyk-gateway_1    | 2018/01/23 15:19:00 http: panic serving 172.18.0.1:37054: runtime error: invalid memory address or nil pointer dereference
tyk-gateway_1    | goroutine 34505 [running]:
tyk-gateway_1    | net/http.(*conn).serve.func1(0xc42044a460)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1697 +0xd0
tyk-gateway_1    | panic(0xd3b120, 0x1646550)
tyk-gateway_1    | 	/usr/local/go/src/runtime/panic.go:491 +0x283
tyk-gateway_1    | regexp.(*Regexp).get(0x0, 0x7d16b71c750d051)
tyk-gateway_1    | 	/usr/local/go/src/regexp/regexp.go:211 +0x26
tyk-gateway_1    | regexp.(*Regexp).doExecute(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42042c79a, 0x1, 0x0, 0x2, ...)
tyk-gateway_1    | 	/usr/local/go/src/regexp/exec.go:420 +0x40
tyk-gateway_1    | regexp.(*Regexp).FindString(0x0, 0xc42042c79a, 0x1, 0xc420ec6420, 0x0)
tyk-gateway_1    | 	/usr/local/go/src/regexp/regexp.go:750 +0xd0
tyk-gateway_1    | github.com/TykTechnologies/tyk/apidef.(*StringRegexMap).Check(0xc420e14530, 0xc42042c79a, 0x1, 0x8, 0xc420ec64a8)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/apidef/api_definitions.go:458 +0x43
tyk-gateway_1    | main.checkQueryString(0xc42066f800, 0xc4211ca180, 0xc420655400, 0x0, 0xc420655440)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/mw_url_rewrite.go:334 +0x110
tyk-gateway_1    | main.urlRewrite(0xc420ad28d0, 0xc42066f800, 0x17, 0x1, 0x1, 0xb)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/mw_url_rewrite.go:63 +0x13fc
tyk-gateway_1    | main.(*URLRewriteMiddleware).ProcessRequest(0xc420668500, 0x167c640, 0xc42107f500, 0xc42066f800, 0x0, 0x0, 0x1d, 0x4150e7, 0xc420e14c40)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/mw_url_rewrite.go:280 +0x1e1
tyk-gateway_1    | main.createMiddleware.func1.1(0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:81 +0x5a3
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc421600100, 0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1    | main.createMiddleware.func1.1(0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:95 +0x76d
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc421600140, 0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1    | main.createMiddleware.func1.1(0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:95 +0x76d
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc421600180, 0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1    | main.createMiddleware.func1.1(0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:95 +0x76d
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc4216001c0, 0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1    | main.createMiddleware.func1.1(0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:95 +0x76d
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc421600200, 0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1    | main.createMiddleware.func1.1(0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:95 +0x76d
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc421600240, 0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1    | main.createMiddleware.func1.1(0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:95 +0x76d
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc421600280, 0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1    | main.createMiddleware.func1.1(0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:95 +0x76d
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc4216002c0, 0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1    | main.createMiddleware.func1.1(0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:95 +0x76d
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc421600300, 0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1    | main.createMiddleware.func1.1(0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:95 +0x76d
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc421600340, 0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc421117440, 0x167c640, 0xc42107f500, 0xc42066f800)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0xed
tyk-gateway_1    | main.mainHandler.ServeHTTP(0x167c640, 0xc42107f500, 0xc42066f600)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/main.go:1299 +0x73
tyk-gateway_1    | main.(*mainHandler).ServeHTTP(0x175c7a8, 0x167c640, 0xc42107f500, 0xc42066f600)
tyk-gateway_1    | 	<autogenerated>:1 +0x52
tyk-gateway_1    | net/http.serverHandler.ServeHTTP(0xc42050b2b0, 0x167c640, 0xc42107f500, 0xc42066f600)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:2619 +0xb4
tyk-gateway_1    | net/http.(*conn).serve(0xc42044a460, 0x167d600, 0xc4215e7400)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1801 +0x71d
tyk-gateway_1    | created by net/http.(*Server).Serve
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:2720 +0x288
tyk-gateway_1    | time="Jan 23 15:19:01" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID"
```
Api def:
```
{
    "id": "5a66599add7232030627665a",
    "name": "rewrite",
    "slug": "rewrite",
    "api_id": "c7dd1b71c7e74f8b48e86d4f88457605",
    "org_id": "5a61d6e6bc26e7032439ce20",
    "use_keyless": false,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": "Authorization",
        "use_certificate": false
    },
    "use_basic_auth": false,
    "use_mutual_tls_auth": false,
    "client_certificates": [],
    "upstream_certificates": {},
    "enable_jwt": false,
    "use_standard_auth": true,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "default_version": "",
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {
                    "url_rewrites": [
                        {
                            "path": "/get",
                            "method": "GET",
                            "match_pattern": "/get",
                            "rewrite_to": "/anything",
                            "triggers": [
                                {
                                    "on": "all",
                                    "options": {
                                        "header_matches": {},
                                        "query_val_matches": {
                                            "show_env": {
                                                "match_rx": "1"
                                            }
                                        },
                                        "path_part_matches": {},
                                        "session_meta_matches": {},
                                        "payload_matches": {
                                            "match_rx": ""
                                        }
                                    },
                                    "rewrite_to": "2"
                                }
                            ]
                        }
                    ]
                },
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/rewrite/",
        "target_url": "https://httpbin.org/",
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "port_data_path": "",
            "target_path": "",
            "use_target_list": false,
            "cache_timeout": 0,
            "endpoint_returns_list": false
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 300,
        "enable_cache": true,
        "cache_all_safe_requests": true,
        "cache_response_codes": [
            200
        ],
        "enable_upstream_cache_control": false,
        "cache_control_ttl_header": ""
    },
    "session_lifetime": 0,
    "active": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false,
    "config_data": {},
    "tag_headers": [],
    "global_rate_limit": {
        "rate": 0,
        "per": 0
    },
    "strip_auth_data": false
}
```
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master

**Comment by asoorm** [comment]
I get same panic. Investigating now
