### ISSUE TITLE
Dashboard 1.5, gw 2.5 panic dies when custom_domain pattern w/ regex specified 

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1433]
db 1.5, gw 2.5. (running on docker quick start setup)

Prior to 1.5/2.5 we make use of "custom domains" (domain property in JSON) that leverages some regex to which looks like this (this is currently configured in our hybrid setup)

```
"domain": "{fqdn:(my.domain.com|(api|test-api|gggateway).my.otherdomain.com)}",
```

When we load up the new dashboard in hybrid, the custom domain is not editable

When we run the local docker quick start, and import one of these working API defs from our hybrid account that contains such a custom domain declaration, it is imported fine and the "custom domain" dialog shows it in the editable field (i.e. `{fqdn:(my.domain.com|(api|test-api|gggateway).my.otherdomain.com)}`, however on the gateway... it dies with

```
2018-01-26T16:56:54.226371008Z time="Jan 26 16:56:54" level=info msg="Tracking hostname" api_name="/my/api/1.0" domain="{fqdn:(my.domain.com|(api|test-api|gggateway).my.otherdomain.com)}"
2018-01-26T16:56:54.226386501Z time="Jan 26 16:56:54" level=info msg="Tracking hostname" api_name="Portal Assets" domain=www.tyk-portal-test.com
2018-01-26T16:56:54.226398195Z time="Jan 26 16:56:54" level=info msg="Tracking hostname" api_name="Portal API" domain=www.tyk-portal-test.com
2018-01-26T16:56:54.226409490Z time="Jan 26 16:56:54" level=info msg="Tracking hostname" api_name=Portal domain=www.tyk-portal-test.com
2018-01-26T16:56:54.226420885Z time="Jan 26 16:56:54" level=info msg="Sub-router created for domain" domain="{fqdn:(my.domain.com|(api|test-api|gggateway).my.otherdomain.com)}"
2018-01-26T16:56:54.228738683Z panic: route {fqdn:(my.domain.com|(api|test-api|gggateway).my.otherdomain.com)} contains capture groups in its regexp. Only non-capturing groups are accepted: e.g. (?:pattern) instead of (pattern)
2018-01-26T16:56:54.228788260Z
2018-01-26T16:56:54.228807550Z goroutine 291 [running]:
2018-01-26T16:56:54.228821244Z github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.newRouteRegexp(0xc420280780, 0x43, 0x1, 0xc420971ac8, 0x40020971a98, 0x10)
2018-01-26T16:56:54.228837236Z 	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/regexp.go:115 +0x11e9
2018-01-26T16:56:54.228852829Z github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Route).addRegexpMatcher(0xc4210c4870, 0xc420280780, 0x43, 0x1, 0xc420723990, 0xc4210c4870)
2018-01-26T16:56:54.229341996Z 	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/route.go:185 +0xd0
2018-01-26T16:56:54.229374881Z github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Route).Host(0xc4210c4870, 0xc420280780, 0x43, 0x1)
2018-01-26T16:56:54.229393072Z 	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/route.go:289 +0x4f
2018-01-26T16:56:54.229407565Z github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).Host(0xc420a973e0, 0xc420280780, 0x43, 0x1)
2018-01-26T16:56:54.229455942Z 	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:282 +0xc8
2018-01-26T16:56:54.229474933Z github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Route).Subrouter(...)
2018-01-26T16:56:54.229489027Z 	/src/github.com/TykTechnologies/tyk/api_loader.go:600
2018-01-26T16:56:54.229503420Z main.loadApps(0xc420959780, 0x4, 0x4, 0xc420a973e0)
2018-01-26T16:56:54.229518313Z 	/src/github.com/TykTechnologies/tyk/api_loader.go:600 +0x8e9
2018-01-26T16:56:54.229534205Z main.loadGlobalApps(0xc420a973e0)
2018-01-26T16:56:54.229549998Z 	/src/github.com/TykTechnologies/tyk/api_loader.go:528 +0xf2
2018-01-26T16:56:54.229564991Z main.doReload()
2018-01-26T16:56:54.229580083Z 	/src/github.com/TykTechnologies/tyk/main.go:671 +0x218
2018-01-26T16:56:54.229597075Z main.reloadLoop(0xc4205a3b60)
2018-01-26T16:56:54.229614467Z 	/src/github.com/TykTechnologies/tyk/main.go:697 +0xa4
2018-01-26T16:56:54.229627161Z created by main.start
2018-01-26T16:56:54.229643453Z 	/src/github.com/TykTechnologies/tyk/main.go:1207 +0xbe
```

Also after this, the editable field in the dashboard gives us the error (post import) when editing the custom domain field "Please enter a valid hostname value"

This is a breaking change for us preventing a possible upgrade and/or further R&D for the new 2.5 features

**Comment by buger** [comment]
I see, maybe we updated 3rd party library to the new version and it changed behavior. 

But frankly this is undocumented change, and first time its usage like this :)

Have you tried suggestion in error message, and replacing all (...) regexp groups with (?:...) (adding ?: to each?

**Comment by bitsofinfo** [comment]
yeah it is, @lonelycode gave us this pointer (regex in the domain field) as a way to do what we needed a while back

Let me try the change suggested

**Comment by bitsofinfo** [comment]
Also to clarify this is not affecting us in prod, just a local dev thing as I test 2.5 prior to any upgrades

**Comment by bitsofinfo** [comment]
@buger that works (non-capture groups), gw does not die

however the dashboard client side validation error is still there: `Please enter a valid hostname value`

**Comment by buger** [comment]
Got it, will be included in next Dashboard patch release, with ETA about 2 weeks.

**Comment by ilijabojanovic** [comment]
Verified

**Comment by bitsofinfo** [comment]
@buger we still see this when trying to start a 2.5.1 gateway against a hybrid account w/ pre-existing definitions containing this custom domain regex syntax. We have yet to update all defs w/ non-matching groups @paltryeffort

**Comment by buger** [comment]
I see I confused you a bit. Panic indeed not solved, but UI bug was fixed. I closed this because panic happens quite deep in stack and quite rare case, but yeah, better re-open it.

**Comment by bitsofinfo** [comment]
Is the panic scheduled to be fixed in an upcoming patch?

**Comment by buger** [comment]
Most likely

**Comment by bitsofinfo** [comment]
Reason being is that we need to do some upgrade to tyk 2.5.x gateways but we can't.

When we bring up 2.5.1 gateways they die because of this panic, due to the regex in the custom domain for our api defs, which was legitimate prior to 2.5 (we are currently running gateways 2.3.13)

Likewise we cannot edit that custom domain field in our hybrid dashboard, and even if we could, due to that JS validation error it won't accept it

We can't export and reimport the api-defs because that would cause a service interruption between the delete and re-export (have to export/import cause there is no ability to edit the domain the ui)

So we are sort of at a standstill waiting for all this to be resolved. Chicken before the egg....

**Comment by buger** [comment]
I see, but frankly, you should be able to update your API definition domain to new regexp even now. It should be supported by current gateways.

**Comment by bitsofinfo** [comment]
Where? its not editable in the cloud dashboard when logged into hybrid, just shown statically (in grey) at the top

![gateway](https://user-images.githubusercontent.com/1743646/36038212-4ad27fa4-0d7c-11e8-8cc8-53f93c72a7f2.png)

**Comment by buger** [comment]
While its true that domain field not visible, I assume that previously you set it via Dashboard API. 
Fix included to 1.5.1 dashboard fixed field validation, but not showing domain field in the UI.

**Comment by bitsofinfo** [comment]
Yes we set it via the dashboard API (long prior to 1.5.x) which requires us to export the api def, delete the api def (causes a production outage) then re-import it with the `domain` attribute adjusted. We can no longer use that procedure as we are now in production.

**Comment by lonelycode** [comment]
@bitsofinfo on that last comment - why do you need to delete the definition - if you use the Tyk dashboard apis to GET and then PUT the JSON you should be able to hot-change the definition.

The export/import buttons probably aren’t the best thing to use here as they are more for backup and initial setup.

**Comment by bitsofinfo** [comment]
Agreed, however our DevOps guys are juggling several things and just using the Dashboard at this point to manage these (not the apis).

**Comment by bitsofinfo** [comment]
not stale

**Comment by andyo-tyk** [comment]
Closing this as not reported again in 3.x or (current LTS) 4.x gateway builds.

We recommend you update to a supported build of Tyk (see https://tyk.io/docs/upgrading-tyk/) and, if you still have this problem, please re-open the issue.

Thank you for your support.
