### ISSUE TITLE
Dashboard only returns 404 (Not Found)

### ISSUE THREAD

**Issue by nilstgmd** [TykTechnologies/tyk#149]
Hi,

I've tried to setup tyk locally following the [blog post](https://tyk.io/blog/running-tyk-with-docker/) and the [QuickStart](https://tyk.io/v1.9/setup/docker/). I run on OS X with Docker Machine.

Using the tyk-gateway through the API work fine. However, I have some trouble getting the Dashboard up and running. Calling `http://<docker-host-ip>:3000/` will always return `404 page not found
`.

Here is my `docker ps` output:
```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                           NAMES
c2a42f978e0d        tykio/tyk-host-manager   "/opt/tyk-dashboard/h"   About an hour ago   Up About an hour    443/tcp, 0.0.0.0:8888->80/tcp   tyk_nginx
64b67fdeafd2        tykio/tyk-dashboard      "/opt/tyk-dashboard/t"   About an hour ago   Up About an hour    0.0.0.0:3000->3000/tcp          tyk_dashboard
6208326e3f80        tykio/tyk-gateway        "/opt/tyk-gateway/tyk"   About an hour ago   Up About an hour    0.0.0.0:8080->8080/tcp          tyk_gateway
16d21a2d8197        mongo                    "/entrypoint.sh mongo"   2 hours ago         Up 2 hours          27017/tcp                       tyk_mongo
aa679de33f37        redis                    "/entrypoint.sh redis"   2 hours ago         Up 2 hours          6379/tcp                        tyk_redis
```

`docker logs 64b67fdeafd2` just gives me the normal output:

```
time="2015-12-10T14:12:03Z" level=info msg="Using /opt/tyk-dashboard/tyk_analytics.conf for configuration"
time="2015-12-10T14:12:03Z" level=info msg="Creating new Redis connection pool"
time="2015-12-10T14:12:03Z" level=info msg="Tyk Analytics Dashboard 0.9.7.0"
time="2015-12-10T14:12:03Z" level=info msg="Copyright Martin Buhr 2015"
time="2015-12-10T14:12:03Z" level=info msg="https://www.tyk.io"
time="2015-12-10T14:12:03Z" level=info msg="Listening on port: 3000"
time="2015-12-10T14:12:03Z" level=info msg="Loading routes..."
time="2015-12-10T14:12:03Z" level=info msg="--> Standard listener (http)"
```

Connecting to the container works just fine, and `netstat` show that it is listening on port `3000` (I'm curious about `tcp6`):

```
root@64b67fdeafd2:/opt/tyk-dashboard# netstat -a
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 64b67fdeafd2:39774      mongo:27017             ESTABLISHED
tcp        0      0 64b67fdeafd2:39776      mongo:27017             ESTABLISHED
tcp        0      0 64b67fdeafd2:59785      redis:6379              ESTABLISHED
tcp6       0      0 [::]:3000               [::]:*                  LISTEN
tcp6       0      0 64b67fdeafd2:3000       192.168.99.1:57367      ESTABLISHED
```

Modifying my `/etc/hosts` to use the hostname as mentioned in the QuickStart doesn't solve the problem. 

I've tried both ways, doing it manually with Docker and with the `setup.sh`, with the same result. `setup.sh` seams to have some trouble while executing:

```
Detected a Docker VM...
Docker host address explicitly set.
Using tyk_dashboard.tyk_dashboard.docker as Tyk host address.
Docker portal domain address explicitly set.
Using www.tyk-portal-test.com as Tyk host address.
tr: Illegal byte sequence
Creating Organisation
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", l line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)
ORGID:
Adding new user
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)
USER AUTH:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)
NEW ID:
Setting password
Setting up the portal domain

DONE
====
Login at http://tyk_dashboard.tyk_dashboard.docker:3000/
User: @test.com
Pass: test123
```

Is that anything you are aware of? Anything I could try to solve this and get the dashboard up and running?

Thanks.

-- Nils

**Comment by lonelycode** [comment]
You seem to be running a really old version of the quickstart... the tyk host manager is no longer run as part of this script. 

Also, that blog post is terribly out of date (note to self: update it)

I would suggest destroying all of your containers, then:

```
cd tyk_quickstart
git pull -u

docker pull tykio/tyk-dashboard:latest
docker pull tykio/tyk-gateway:latest

docker-compose up -d
./setup.sh <docker-host-ip> <portal-domain.com>

```

Also, we *just* updated the docker setup guide with an even newer version that uses the docker ambassador pattern, so the instructions have changed slightly, I suggest revisiting the setup guide :-)

**Comment by nilstgmd** [comment]
Hey @lonelycode , thanks for the fast support. Finally, after removing everything done before and use `docker-compose`, I was able to also access the dashboard.

However, the `setup.sh` didn't run completely successful.

```
$ ./setup.sh 192.168.99.100 tyk_dashboard.tyk_dashboard.docker 
Detected a Docker VM...
Docker host address explicitly set.
Using 192.168.99.100 as Tyk host address.
Docker portal domain address explicitly set.
Using tyk_dashboard.tyk_dashboard.docker as Tyk host address.
tr: Illegal byte sequence
Creating Organisation
ORGID: 5669b09e9ee2920001000001
Adding new user
USER AUTH: User object validation failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'users'
NEW ID:
Setting password
Setting up the portal domain
{"Status":"OK","Message":"Org updated","Meta":null}
DONE
====
Login at http://192.168.99.100:3000/
User: @test.com
Pass: test123
```

After executing the user/org creation manually, I was able to login.

**Comment by lonelycode** [comment]
That's a little odd, you may have some other problems down the line since the new Docker install no longer uses the tyk_dashboard.tyk_dashboard.docker anymore :-)

**Comment by nilstgmd** [comment]
Could be. Anyway, thanks for the support.
