### ISSUE TITLE
Pined cert with domain name crashes gateway

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#1591]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When we add cert pin and for host name type httpbin.org, gateway crashes
**What is the expected behavior?**
Gateway should not crash
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Start gateway in SSL mode
2. Create api with Mutual tls
3. Add cert pin
4. In Domain name type httpbin.org and save
5. Trigger call to that api

Actual:
Gateway will crash

Here debug log:
```
tyk-gateway_1          | time="Apr  4 19:33:56" level=debug msg="[STORE] SET Raw key is: 5ac4d8cf866db00010e7e972c841ce5d231244e1bc907b15e3a9ff80"
tyk-gateway_1          | time="Apr  4 19:33:56" level=debug msg="[STORE] Setting key: apikey-0a3663eb"
tyk-gateway_1          | time="Apr  4 19:33:56" level=debug msg="Getting exp for key: analytics-tyk-system-analytics"
tyk-gateway_1          | panic: interface conversion: interface {} is *tls.Certificate, not string
tyk-gateway_1          |
tyk-gateway_1          | goroutine 213974 [running]:
tyk-gateway_1          | github.com/TykTechnologies/tyk/certs.(*CertificateManager).ListPublicKeys(0xc4204fac30, 0xc420328bb0, 0x1, 0x1, 0xc420328bb0, 0x1, 0x1)
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/certs/manager.go:294 +0x8e4
tyk-gateway_1          | main.getPinnedPublicKeys(0xc4202ddee0, 0xb, 0xc420872d00, 0xb, 0xc4202ddeec, 0x3)
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/cert.go:173 +0x33a
tyk-gateway_1          | main.dialTLSPinnedCheck.func1(0xe87921, 0x3, 0xc4202ddee0, 0xf, 0x5, 0xc4202ddee0, 0xf, 0xc420904550)
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/cert.go:113 +0x107
tyk-gateway_1          | net/http.(*Transport).dialConn(0xc4208444b0, 0x16e3bc0, 0xc42078e880, 0x0, 0xc4203fac60, 0x5, 0xc4202ddee0, 0xf, 0x0, 0x0, ...)
tyk-gateway_1          | 	/usr/local/go/src/net/http/transport.go:1033 +0x334
tyk-gateway_1          | net/http.(*Transport).getConn.func4(0xc4208444b0, 0x16e3bc0, 0xc42078e880, 0xc4208f7530, 0xc420ab4360)
tyk-gateway_1          | 	/usr/local/go/src/net/http/transport.go:943 +0x78
tyk-gateway_1          | created by net/http.(*Transport).getConn
tyk-gateway_1          | 	/usr/local/go/src/net/http/transport.go:942 +0x393
```
https://www.screencast.com/t/nT8nAlYy9Rn

Api def:
```
{
    "id": "5ac4fda5866db000296af383",
    "name": "api",
    "slug": "api",
    "api_id": "49d5b6c79b45454a61d191905cfb720c",
    "org_id": "5ac4d8cf866db00010e7e972",
    "use_keyless": false,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": true,
        "param_name": "auth",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": "Authorization",
        "use_certificate": true
    },
    "use_basic_auth": false,
    "use_mutual_tls_auth": true,
    "client_certificates": [
        "5ac4d8cf866db00010e7e9728b327b5f995eafb14b56dfa2f3b2e24452b506d4baff25da4d0163e3514c994c"
    ],
    "upstream_certificates": {},
    "pinned_public_keys": {
        "httpbin.org": "5ac4d8cf866db00010e7e9729a7a0e3c12156333f39e3e124a00c1cec878e3e986fd16b51d6778325867aa37"
    },
    "enable_jwt": false,
    "use_standard_auth": true,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "base_identity_provided_by": "auth_token",
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "default_version": "",
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {},
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/api/",
        "target_url": "https://httpbin.org/",
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "port_data_path": "",
            "target_path": "",
            "use_target_list": false,
            "cache_timeout": 0,
            "endpoint_returns_list": false
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false,
        "cache_control_ttl_header": ""
    },
    "session_lifetime": 0,
    "active": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "enable_ip_blacklisting": false,
    "blacklisted_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false,
    "config_data": {},
    "tag_headers": [],
    "global_rate_limit": {
        "rate": 0,
        "per": 0
    },
    "strip_auth_data": false
}
```
Related to: #1537 
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master

**Comment by buger** [comment]
I assume you tried uploading tls certificate as public key.
