### ISSUE TITLE
Credentials are incorrect, please try again after  bootstrap.sh

### ISSUE THREAD

**Issue by angusonesky** [TykTechnologies/tyk#170]
I was following 1.9 vagrant steps to setup: https://tyk.io/v1.9/setup/vagrant-setup/

I only did one customization that relplace XXX.XXX.XXX.XXX to `my-awesome-portal-dashboard.com`
```
sudo /opt/tyk-dashboard/install/setup.sh --listenport=3000 --redishost=localhost --redisport=6379 --mongo=mongodb://localhost/tyk_analytics --tyk_api_hostname=$HOSTNAME --tyk_node_hostname=http://localhost --tyk_node_port=8080 --portal_root=/portal --domain="my-awesome-portal-dashboard.com"
```
```
vagrant@precise64:~$ sudo /opt/tyk-dashboard/install/bootstrap.sh my-awesome-portal-dashboard.com
Creating Organisation
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ORGID:
Adding new user
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
USER AUTH:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
NEW ID:
Setting password

DONE
====
Login at http://my-awesome-portal-dashboard.com:3000/
User: xdkziqprxp@default.com
Pass: test123
```

It return an error message `Credentials are incorrect, please try again` when it using above URL, User, Password.  Any idea about this ? Any log file I should refer to ?

# The gateway status also strange. Any hints for this ?  Any log file I should refer to ?
```shell
vagrant@precise64:~$ sudo service tyk-dashboard status
tyk-dashboard start/running, process 2843
vagrant@precise64:~$ sudo service tyk-gateway status
tyk-gateway stop/waiting
```
```
# /var/log/syslog
Jan 17 05:24:50 precise64 kernel: [ 6172.347779] init: tyk-gateway main process (2928) terminated with status 2
Jan 17 05:24:50 precise64 kernel: [ 6172.347808] init: tyk-gateway main process ended, respawning
Jan 17 05:24:51 precise64 kernel: [ 6172.371629] init: tyk-gateway main process (2933) terminated with status 2
```

**Comment by lonelycode** [comment]
I don't think you did that right, the domain needs to actually resolve to the dashboard, otherwise the API calls will fail and the bootstrap script will fail.

See the community forum for stuff like this because it's not a bug and lots of people have reported it.

As for the services, did you actually start them?

Log files are where you would expect them to be /var/log or /var/log/upstart

**Comment by angusonesky** [comment]
Hi there,  I will use the community in the future. 

I had tried to start gateway and dashboard service, 
```
vagrant@precise64:/opt/tyk-dashboard$ sudo service tyk-gateway start
tyk-gateway start/running, process 36
vagrant@precise64:/opt/tyk-dashboard$ sudo service tyk-gateway status
tyk-gateway stop/waiting
```

but gateway seem can't be started.  this is part of log.  let me know if you want the rest of log
```
sudo tail -f tyk-gateway.log

INFO[0000] Hostname set:
panic: open /etc/tyk/templates/error.json: no such file or directory

goroutine 1 [running]:
html/template.Must(0x0, 0x7f8987b0b770, 0xc820258b40, 0x0)
	/usr/local/go/src/html/template/template.go:330 +0x4b
main.setupGlobals()
	/home/tyk/go/src/github.com/lonelycode/tyk/main.go:130 +0xb66
main.init.1()
	/home/tyk/go/src/github.com/lonelycode/tyk/main.go:818 +0x81a
main.init()
	/home/tyk/go/src/github.com/lonelycode/tyk/version.go:3 +0x6be

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/getsentry/raven-go.(*Client).worker(0xc8200edb80)
	/home/tyk/go/src/github.com/getsentry/raven-go/client.go:415 +0x60
created by github.com/getsentry/raven-go.newClient
	/home/tyk/go/src/github.com/getsentry/raven-go/client.go:304 +0x192

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select]:
github.com/pmylund/go-cache.(*janitor).Run(0xc820105e60, 0xc820119170)
	/home/tyk/go/src/github.com/pmylund/go-cache/cache.go:946 +0x13d
created by github.com/pmylund/go-cache.runJanitor
	/home/tyk/go/src/github.com/pmylund/go-cache/cache.go:964 +0x81

goroutine 8 [runnable]:
main.(*HostCheckerManager).CheckActivePollerLoop(0x10dfd60)
	/home/tyk/go/src/github.com/lonelycode/tyk/host_checker_manager.go:92
created by main.(*HostCheckerManager).Start
	/home/tyk/go/src/github.com/lonelycode/tyk/host_checker_manager.go:81 +0x3f
```

**Comment by lonelycode** [comment]
So the error you have there is because setup.sh wasn't run before starting Tyk, so it assumed installation files were in /etc which they aren't. That panicked the binary and so nothing ran.

You need the domain to be valid outside vagrant, inside shouldn't matter.
