### ISSUE TITLE
Api proxy feature is broken

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#1792]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When we enable proxy for api and send traffic to that api gateway panics.
**What is the expected behavior?**
Gateway should proxy traffic over proxy server
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create api
2. Add proxy url in api definition
3. Send traffic to that api

Gateway error:
```
tyk-gateway_1  | 2018/06/26 12:59:29 http: panic serving 172.18.0.1:41882: runtime error: invalid memory address or nil pointer dereference
tyk-gateway_1  | goroutine 33906 [running]:
tyk-gateway_1  | net/http.(*conn).serve.func1(0xc429e87360)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1697 +0xd0
tyk-gateway_1  | panic(0xd9ef80, 0x1787420)
tyk-gateway_1  | 	/usr/local/go/src/runtime/panic.go:491 +0x283
tyk-gateway_1  | github.com/TykTechnologies/tyk/certs.(*CertificateManager).ListPublicKeys(0xc4204f7320, 0xc429ebda60, 0x1, 0x1, 0xc429ebda60, 0x1, 0x1)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/certs/manager.go:317 +0x538
tyk-gateway_1  | main.getPinnedPublicKeys(0xec1d51, 0x1, 0xc429417200, 0x0, 0x0, 0x0)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/cert.go:206 +0x3f1
tyk-gateway_1  | main.verifyPeerCertificatePinnedCheck(0xc429417200, 0xc429e92c00, 0x0)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/cert.go:105 +0x14b
tyk-gateway_1  | main.httpTransport(0x0, 0x17bcc60, 0xc4261bcc40, 0xc429e76900, 0xc429f5b360, 0x0, 0x0)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/reverse_proxy.go:444 +0x1ae
tyk-gateway_1  | main.(*ReverseProxy).WrappedServeHTTP(0xc429f5b360, 0x17bcc60, 0xc4261bcc40, 0xc429e76900, 0x0, 0x0)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/reverse_proxy.go:497 +0x1d7
tyk-gateway_1  | main.(*ReverseProxy).ServeHTTP(0xc429f5b360, 0x17bcc60, 0xc4261bcc40, 0xc429e76900, 0x0)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/reverse_proxy.go:362 +0x165
tyk-gateway_1  | main.(*SuccessHandler).ServeHTTP(0xc429f6ee40, 0x17bcc60, 0xc4261bcc40, 0xc429e76900, 0x0)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/handler_success.go:273 +0x2a7
tyk-gateway_1  | main.(*DummyProxyHandler).ServeHTTP(0xc429f6ee40, 0x17bcc60, 0xc4261bcc40, 0xc429e76900)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/api_loader.go:480 +0x4b
tyk-gateway_1  | main.createMiddleware.func1.1(0x17bcc60, 0xc4261bcc40, 0xc429e76900)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:101 +0x729
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc429f5df40, 0x17bcc60, 0xc4261bcc40, 0xc429e76900)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1  | main.createMiddleware.func1.1(0x17bcc60, 0xc4261bcc40, 0xc429e76900)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:101 +0x729
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc429f5df80, 0x17bcc60, 0xc4261bcc40, 0xc429e76900)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1  | main.createMiddleware.func1.1(0x17bcc60, 0xc4261bcc40, 0xc429e76900)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/middleware.go:101 +0x729
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc429f5dfc0, 0x17bcc60, 0xc4261bcc40, 0xc429e76900)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1918 +0x44
tyk-gateway_1  | github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc429e60d20, 0x17bcc60, 0xc4261bcc40, 0xc429e76900)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0xed
tyk-gateway_1  | main.mainHandler.ServeHTTP(0x17bcc60, 0xc4261bcc40, 0xc429e76600)
tyk-gateway_1  | 	/develop/go/src/github.com/TykTechnologies/tyk/main.go:1162 +0x73
tyk-gateway_1  | main.(*mainHandler).ServeHTTP(0x189e280, 0x17bcc60, 0xc4261bcc40, 0xc429e76600)
tyk-gateway_1  | 	<autogenerated>:1 +0x52
tyk-gateway_1  | net/http.serverHandler.ServeHTTP(0xc42095e1a0, 0x17bcc60, 0xc4261bcc40, 0xc429e76600)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:2619 +0xb4
tyk-gateway_1  | net/http.(*conn).serve(0xc429e87360, 0x17bdc20, 0xc429fe84c0)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1801 +0x71d
tyk-gateway_1  | created by net/http.(*Server).Serve
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:2720 +0x288
tyk-gateway_1  | time="Jun 26 12:59:36" level=info msg="RPC is alive"
```
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master/release-2.7 branch

**Comment by buger** [comment]
Should be fixed
