### ISSUE TITLE
Python coprocess error

### ISSUE THREAD

**Issue by altaurog** [TykTechnologies/tyk#1804]
**Do you want to request a *feature* or report a *bug*?**
possibly a bug

**What is the current behavior?**
unable to initialize coprocess dispatcher:
```
[Jul  4 14:33:34]  INFO Connection dropped, reconnecting...
[Jul  4 14:33:34]  WARN coprocess: Python path prefix isn't set (check "python_path_prefix" in tyk.conf)
[Jul  4 14:33:34]  INFO python: Setting PYTHONPATH to 'coprocess/python:coprocess/python/proto:middleware/bundles'
[Jul  4 14:33:34]  INFO python: Initializing interpreter, Py_Initialize()
Traceback (most recent call last):
  File "/opt/tyk-gateway/coprocess/python/dispatcher.py", line 6, in <module>
    from tyk.object import TykCoProcessObject
  File "/opt/tyk-gateway/coprocess/python/tyk/object.py", line 1, in <module>
    from tyk.session import TykSession
  File "/opt/tyk-gateway/coprocess/python/tyk/session.py", line 1, in <module>
    import coprocess_session_state_pb2 as session_state_pb
  File "/opt/tyk-gateway/coprocess/python/proto/coprocess_session_state_pb2.py", line 41, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'
[Jul  4 14:33:34] ERROR coprocess: can't initialize a dispatcher
[Jul  4 14:33:34] ERROR coprocess: can't initialize a dispatcher
```

**What is the expected behavior?**
should be able to use python coprocess middleware

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Build and run docker image (dockerfile below)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
building pr #1802

Dockerfile:
```
FROM ubuntu:14.04 as tykbuild

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true
ENV DEBCONF_NOWARNINGS=yes
RUN sed -i 's/restricted\|universe\|multiverse//g;/UNSUPPORTED/q' /etc/apt/sources.list \
  && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 16126D3A3E5C1192 40976EAF437D05B5 \
  && apt-get update -qq -y \
  && apt-get install -qq -y --no-install-recommends software-properties-common \
  && add-apt-repository -y ppa:gophers/archive \
  && apt-get update -qq -y \
  && apt-get install -y \
    build-essential \
    ca-certificates \
    git \
    golang-1.9 \
    libpython3.4-dev \
    python3-dev \
    python3-setuptools \
    python3-setuptools \
  && rm -rf /var/lib/apt/lists/*

ADD https://bootstrap.pypa.io/get-pip.py /build/
RUN python3 /build/get-pip.py \
  && python3 -m pip install wheel

ADD https://github.com/google/protobuf/releases/download/v3.1.0/protobuf-python-3.1.0.tar.gz /build/
RUN cd /build/ \
  && tar xf protobuf-python-3.1.0.tar.gz \
  && cd /build/protobuf-3.1.0 \
  && ./configure -prefix=/usr \
  && make \
  && make install \
  && cd python \
  && python3 setup.py build --cpp_implementation \
  && python3 setup.py install --cpp_implementation \
  && python3 setup.py bdist_wheel --cpp_implementation

RUN /usr/lib/go-1.9/bin/go get -d github.com/TykTechnologies/tyk

RUN cd /root/go/src/github.com/TykTechnologies/tyk \
  && git fetch https://github.com/asoorm/tyk.git 1801-support-slice-interface-valToString \
  && git checkout -b 1801-support-slice-interface-valToString FETCH_HEAD \
  && /usr/lib/go-1.9/bin/go get \
  && /usr/lib/go-1.9/bin/go build -tags 'coprocess python'

FROM ubuntu:14.04

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true
ENV DEBCONF_NOWARNINGS=yes
RUN sed -i 's/restricted\|universe\|multiverse//g;/UNSUPPORTED/q' /etc/apt/sources.list \
  && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 16126D3A3E5C1192 40976EAF437D05B5 \
  && apt-get update -qq -y \
  && apt-get install -y ca-certificates libpython3.4

COPY --from=tykbuild /usr/lib/libprotobuf.so* /usr/lib/
COPY --from=tykbuild /build/get-pip.py /build/protobuf-3.1.0/python/dist/protobuf-3.1.0-cp34-cp34m-linux_x86_64.whl /install/
COPY --from=tykbuild /root/go/src/github.com/TykTechnologies/tyk/tyk /usr/bin/tyk
COPY --from=tykbuild /root/go/src/github.com/TykTechnologies/tyk/coprocess /opt/tyk-gateway/coprocess

RUN python3 /install/get-pip.py \
  && python3 -m pip install wheel \
  && python3 -m pip install /install/protobuf-3.1.0-cp34-cp34m-linux_x86_64.whl

COPY tyk-gateway /opt/tyk-gateway

VOLUME ["/opt/tyk-gateway/"]
WORKDIR /opt/tyk-gateway/

CMD ["/usr/bin/tyk", "--conf=tyk.conf"]
```

**Comment by matiasinsaurralde** [comment]
Can you share your tyk.conf?

**Comment by altaurog** [comment]
Sure!  I am not sure why it doesn’t pick up `"python_path_prefix"`, but it’s the same as `$PWD` and it seems to have found what it needed.
```
{
  "listen_port": 8180,
  "secret": "verysecret",
  "template_path": "templates/",
  "middleware_path": "middleware/",
  "app_path": "apps/",
  "coprocess_options": {
    "enable_coprocess": true
  },
  "python_path_prefix": "/opt/tyk-gateway",
  "enable_bundle_downloader": true,
  "bundle_base_url": "http://localhost:8081/",
  "storage": {
    "type": "redis",
    "host": "localhost",
    "port": 6379,
    "username": "",
    "password": "",
    "database": 0,
    "optimisation_max_idle": 100
  },
  "policies": {
    "policy_source": "file",
    "policy_record_name": "policies/policies.json"
  },
  "health_check": {
    "enable_health_checks": false
  }
}
```

**Comment by matiasinsaurralde** [comment]
@altaurog `python_path_prefix` should be inside `coprocess_options`, the log line should be more specific (will change this).
The error you're getting is related to the `protobuf` Python module you're using. Can you share the version?
```
$ pip3 show protobuf
```
Also your Python version:
```
$ python -V
```
Thanks!

**Comment by altaurog** [comment]
`"python_path_prefix"` isn’t mentioned in the documentation at all, as far as I can tell.  `"coprocess_options"` isn’t listed on the [Tyk Gateway Configuration Options page](https://tyk.io/docs/configure/tyk-gateway-configuration-options/) either.

As you can see in the Dockerfile, I built protobuf according to [the instructions to which you referred me](https://tyk.io/docs/customise-tyk/plugins/rich-plugins/python/), although I suppose I could also try just `pip install protobuf`.

```
$ sudo docker run --rm -it tyk-python:test-1 python3 -m pip show protobuf
Name: protobuf
Version: 3.1.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: New BSD License
Location: /usr/local/lib/python3.4/dist-packages
Requires: six, setuptools
Required-by: 

$ sudo docker run --rm -it tyk-python:test-1 python3 -V
Python 3.4.3
```

**Comment by altaurog** [comment]
In the meantime, I realized we can do pretty much all we need with the javascript middleware, so we’ll be moving forward with that.

**Comment by matiasinsaurralde** [comment]
@altaurog Good
This will be helpful for debugging the issue as well: were you building Tyk using the current `master`?
Thanks!

**Comment by joshblakeley** [comment]
@matiasinsaurralde @marksou is there a docs improvement to make off the back of this?

**Comment by altaurog** [comment]
@matiasinsaurralde essentially yes.  Here’s the build part of the Dockerfile:
```
RUN /usr/lib/go-1.9/bin/go get -d github.com/TykTechnologies/tyk

RUN cd /root/go/src/github.com/TykTechnologies/tyk \
  && git fetch https://github.com/asoorm/tyk.git 1801-support-slice-interface-valToString \
  && git checkout -b 1801-support-slice-interface-valToString FETCH_HEAD \
  && /usr/lib/go-1.9/bin/go get \
  && /usr/lib/go-1.9/bin/go build -tags 'coprocess python'
```
