### ISSUE TITLE
Generating Keys via the Dashboard Fails and Causes Error

### ISSUE THREAD

**Issue by aftershockdan** [TykTechnologies/tyk#1843]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Attempting to create a key using the dashboard fails and causes a Go panic

**What is the expected behavior?**
Creating keys through the dashboard succeeds normally

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Login to tyk dashboard -> Keys -> Add Key -> Create -> Error message box with the text "undefined" pops up

Server error logs then show:
```
time="Jul 26 01:29:38" level=error msg="Failed to create request"
time="Jul 26 01:29:38" level=error msg="parse 10.28.14.30:80/tyk/keys/create: first path segment in URL cannot contain colon"
ERROR 2018/07/26 01:29:38.908284 panic_handler.go:26: PANIC
URL: /api/keys
ERROR: runtime error: invalid memory address or nil pointer dereference
STACK:
    goroutine 255314 [running]:
    github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*Router).handlePanic(0xc4204a4750, 0xc420604480, 0xc4206044a0, 0xb56e40, 0x13e36d0)
        /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:273 +0x47a
    github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*Router).ServeHTTP.func1(0xc4204a4750, 0xc420604480)
        /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:43 +0x6f
    panic(0xb56e40, 0x13e36d0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
    main.(*TykApi).PrepareRequest(0x1409de0, 0xc30dea, 0x4, 0xc421aa61a0, 0x1e, 0x10900e0, 0xc42039b260, 0x12)
        /src/github.com/TykTechnologies/tyk-analytics/tyk_api_wrapper.go:55 +0x9a
    main.(*TykApi).CreateKey(0x1409de0, 0x0, 0x408f400000000000, 0x408f400000000000, 0x404e000000000000, 0x0, 0xffffffffffffffff, 0x5b592402, 0xffffffffffffffff, 0xffffffffffffffff, ...)
        /src/github.com/TykTechnologies/tyk-analytics/tyk_api_wrapper.go:184 +0x174
    main.(*KeyData).Create(0xc4207449b8, 0xc42209, 0x17)
        /src/github.com/TykTechnologies/tyk-analytics/model_keys.go:197 +0x79
    main.(*APIContext).CreateKey(0xc42052b520, 0x109e1e0, 0xc420604480, 0xc4206044a0)
        /src/github.com/TykTechnologies/tyk-analytics/api_keys.go:213 +0x580
    reflect.Value.call(0xb378e0, 0xcb69f0, 0x13, 0xc30ca2, 0x4, 0xc420745350, 0x3, 0x3, 0x13ecd70, 0xc139e0, ...)
        /usr/local/go/src/reflect/value.go:434 +0x905
    reflect.Value.Call(0xb378e0, 0xcb69f0, 0x13, 0xc420745350, 0x3, 0x3, 0xb90e40, 0xc42028fc80, 0x0)
        /usr/local/go/src/reflect/value.go:302 +0xa4
    github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.middlewareStack.func1(0x109e1e0, 0xc420604480, 0xc4206044a0)
        /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:135 +0x37f
    main.(*APIContext).InstrumentationMW(0xc42052b520, 0x109e1e0, 0xc420604480, 0xc4206044a0, 0xc4203892f0)
        /src/github.com/TykTechnologies/tyk-analytics/instrumentation_helpers.go:48 +0x94
    reflect.Value.call(0xb4a4c0, 0xcb6cc8, 0x13, 0xc30ca2, 0x4, 0xc420745878, 0x4, 0x4, 0xc4205ee900, 0xb4e780, ...)
        /usr/local/go/src/reflect/value.go:434 +0x905
    reflect.Value.Call(0xb4a4c0, 0xcb6cc8, 0x13, 0xc420745878, 0x4, 0x4, 0x531c5d, 0x13e, 0xc420447ac0)
        /usr/local/go/src/reflect/value.go:302 +0xa4
    github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*middlewareHandler).invoke(0xc42051db90, 0xc2f580, 0xc42052b520, 0x16, 0x109e1e0, 0xc420604480, 0xc4206044a0, 0xc4203892f0)
        /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:155 +0x1e3
    github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.middlewareStack.func1(0x109e1e0, 0xc420604480, 0xc4206044a0)
        /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:144 +0x1b0
    main.GoCraftHttphandlerFunc.func1(0x1098420, 0xc420604480, 0xc4206b4800)
        /src/github.com/TykTechnologies/tyk-analytics/main.go:594 +0x43
    net/http.HandlerFunc.ServeHTTP(0xc4206e51d0, 0x1098420, 0xc420604480, 0xc4206b4800)
        /usr/local/go/src/net/http/server.go:1918 +0x44
    github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf.(*CSRFHandler).handleSuccess(0xc420745da8, 0x1098420, 0xc420604480, 0xc4206b4800)
        /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf/handler.go:180 +0x51
    github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf.(*CSRFHandler).ServeHTTP(0xc420745da8, 0x1098420, 0xc420604480, 0xc4206b4800)
        /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf/handler.go:173 +0x28c
    main.CSRFMiddleware(0x109e1e0, 0xc420604480, 0xc4206044a0, 0xc4203892f0)
        /src/github.com/TykTechnologies/tyk-analytics/main.go:615 +0x1ca
    main.(*APIContext).CSRFAPIMiddleware(0xc42052b520, 0x109e1e0, 0xc420604480, 0xc4206044a0, 0xc4203892f0)
        /src/github.com/TykTechnologies/tyk-analytics/main.go:621 +0x86
    reflect.Value.call(0xb4a4c0, 0xcb69d0, 0x13, 0xc30ca2, 0x4, 0xc420746308, 0x4, 0x4, 0x32, 0xb4e780, .
```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
gateway: v2.7.0, dashboard: v1.7.0 - Yes, it did work in my testing with the previous version of Tyk gateway and dashboard

**Comment by ilijabojanovic** [comment]
@aftershockdan Hi, could you please share yours tyk_analytics.conf file?

**Comment by aftershockdan** [comment]
Hi @ilijabojanovic, sure the conf is as follows:
```
{
    "listen_port": 3000,
    "tyk_api_config": {
        "Host": "http://tyk-gateway",
        "Port": "8080",
        "Secret": "$SECRET"
    },
    "shared_node_secret": "$SECRET",
    "mongo_url": "mongodb://mongo:27017/tyk_analytics",
    "license_key": "$KEY",
    "page_size": 10,
    "admin_secret": "$ADMIN_SECRET",
    "redis_port": 6379,
    "redis_host": "redis",
    "redis_password": "",
    "force_api_defaults": false,
    "notify_on_change": true,
    "license_owner": "NA",
    "hash_keys": true,
    "email_backend": {},
    "hide_listen_path": false,
    "use_sentry": false,
    "sentry_code": "",
    "sentry_js_code": "",
    "show_org_id": true,
    "enable_duplicate_slugs": true,
    "host_config" : {
        "override_hostname": "",
        "disable_org_slug_prefix": true,
        "enable_host_names": false,
        "hostname": "",
        "portal_domains": {},
        "portal_root_path": "/portal"
    },
    "http_server_options": {
        "use_ssl": false,
        "certificates": [
            {}
        ]
    },
    "ui": {
        "login_page": {},
        "nav" : {},
        "uptime": {},
        "portal": {},
        "designer": {}
    },
    "home_dir": "/opt/tyk-dashboard",
    "enable_aggregate_lookups": true,
    "aggregate_lookup_cutoff": "01/07/2016"
}
```

We also configure the dashboard using env variables as well:
```
- name: TYK_DB_TYKAPI_HOST
    value: "$(GATEWAY_SERVICE_HOST)"
- name: TYK_DB_TYKAPI_PORT
    value: "$(GATEWAY_SERVICE_PORT)"
- name: TYK_DB_MONGOURL
    value: "mongodb://mongo-0.mongo/tyk_analytics"
- name: TYK_DB_REDISHOST
    value: "10.0.0.3"
- name: TYK_DB_REDISPORT
    value: "6379"
```

**Comment by ilijabojanovic** [comment]
@aftershockdan for some reason dashboard locates gateway on this address:
10.28.14.30:80 without protocol.
if you are using env variables gateway host must have protocol e.g http://10.28.14.30 or http://tyk-gateway

**Comment by aftershockdan** [comment]
Ahh, ok yeah I didn't realize we needed the protocol there. I updated the env variable to:
```
- name: TYK_DB_TYKAPI_HOST
  value: "http://$(GATEWAY_SERVICE_HOST)"
```
And everything works now. Thanks for the quick help!
