### ISSUE TITLE
Panic with wrong ID

### ISSUE THREAD

**Issue by veger** [TykTechnologies/tyk#190]
Hello,

I am writing some code that makes use of the advanced Tyk (dashboard) API in order to retrieve an API definition with `/api/apis/<id>`.

When `<id>` in an illegal key, e.g. one number too long (or short), I get the following panic situation in the dashboard log file:

```
URL: /api/apis/56b21f6fee74a2100b0000032
ERROR: Invalid input to ObjectIdHex: "56b21f6fee74a2100b0000032"
STACK:
goroutine 1885 [running]:
github.com/gocraft/web.(*Router).handlePanic(0xc8200b3ef0, 0xc82017c840, 0xc82017c860, 0x9341c0, 0xc8203cc660)
        /home/tyk/go/src/github.com/gocraft/web/router_serve.go:251 +0x348
github.com/gocraft/web.(*Router).ServeHTTP.func1(0xc8200b3ef0, 0xc82017c840)
        /home/tyk/go/src/github.com/gocraft/web/router_serve.go:43 +0x68
gopkg.in/mgo.v2/bson.ObjectIdHex(0xc82036445e, 0x19, 0x0, 0x0)
        /home/tyk/go/src/gopkg.in/mgo.v2/bson/bson.go:175 +0x210
main.(*ApiDefinition).GetApiByInternalId(0xc820209b00, 0xc8203e63c0, 0x18, 0xc82036445e, 0x19, 0x10c)
        /home/tyk/go/src/github.com/lonelycode/tyk-analytics/ModelApiDefintion.go:126 +0x19c
main.(*APIContext).GetApiDetail(0xc8200201a8, 0x7f541d701ad8, 0xc82017c840, 0xc82017c860)
        /home/tyk/go/src/github.com/lonelycode/tyk-analytics/ApiApiManagement.go:126 +0x111
reflect.Value.call(0x9ab4e0, 0xc14c88, 0x13, 0xae5118, 0x4, 0xc82019ab88, 0x3, 0x3, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x9ab4e0, 0xc14c88, 0x13, 0xc82019ab88, 0x3, 0x3, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:300 +0xb1
github.com/gocraft/web.middlewareStack.func1(0x7f541d701ad8, 0xc82017c840, 0xc82017c860)
        /home/tyk/go/src/github.com/gocraft/web/router_serve.go:113 +0xace
main.(*APIContext).ApiAuthorisationRequired(0xc8200201a8, 0x7f541d701ad8, 0xc82017c840, 0xc82017c860, 0xc8203cc470)
        /home/tyk/go/src/github.com/lonelycode/tyk-analytics/Main.go:409 +0x15e
reflect.Value.call(0x9db5a0, 0xc14ba8, 0x13, 0xae5118, 0x4, 0xc82019b0d0, 0x4, 0x4, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x9db5a0, 0xc14ba8, 0x13, 0xc82019b0d0, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:300 +0xb1
github.com/gocraft/web.(*middlewareHandler).invoke(0xc8202861e0, 0xae22a0, 0xc8200201a8, 0x16, 0x7f541d701ad8, 0xc82017c840, 0xc82017c860, 0xc8203cc470)
        /home/tyk/go/src/github.com/gocraft/web/router_serve.go:133 +0x281
github.com/gocraft/web.middlewareStack.func1(0x7f541d701ad8, 0xc82017c840, 0xc82017c860)
        /home/tyk/go/src/github.com/gocraft/web/router_serve.go:122 +0x1a0
github.com/gocraft/web.StaticMiddlewareFromDir.func1(0x7f541d701ad8, 0xc82017c840, 0xc82017c860, 0xc8203cc470)
        /home/tyk/go/src/github.com/gocraft/web/static_middleware.go:30 +0x17d
github.com/gocraft/web.(*middlewareHandler).invoke(0xc820281ef0, 0xaaa040, 0xc8200201a0, 0x16, 0x7f541d701ad8, 0xc82017c840, 0xc82017c860, 0xc8203cc470)
        /home/tyk/go/src/github.com/gocraft/web/router_serve.go:131 +0x6e
github.com/gocraft/web.middlewareStack.func1(0x7f541d701ad8, 0xc82017c840, 0xc82017c860)
        /home/tyk/go/src/github.com/gocraft/web/router_serve.go:122 +0x1a0
github.com/gocraft/web.StaticMiddlewareFromDir.func1(0x7f541d701ad8, 0xc82017c840, 0xc82017c860, 0xc8203cc470)
        /home/tyk/go/src/github.com/gocraft/web/static_middleware.go:30 +0x17d
github.com/gocraft/web.(*middlewareHandler).invoke(0xc820281ec0, 0xaaa040, 0xc8200201a0, 0x16, 0x7f541d701ad8, 0xc82017c840, 0xc82017c860, 0xc8203cc470)
        /home/tyk/go/src/github.com/gocraft/web/router_serve.go:131 +0x6e
github.com/gocraft/web.middlewareStack.func1(0x7f541d701ad8, 0xc82017c840, 0xc82017c860)
        /home/tyk/go/src/github.com/gocraft/web/router_serve.go:122 +0x1a0
github.com/gocraft/web.(*Router).ServeHTTP(0xc8200b3ef0, 0x7f541d701a78, 0xc820288b00, 0xc820301260)
        /home/tyk/go/src/github.com/gocraft/web/router_serve.go:48 +0x355
net/http.(*ServeMux).ServeHTTP(0xc820281b60, 0x7f541d701a78, 0xc820288b00, 0xc820301260)
        /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc820255200, 0x7f541d701a78, 0xc820288b00, 0xc820301260)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8202894a0)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by lonelycode** [comment]
Thanks for reporting. Basically that ID isn't valid so it throws a wobbly. We'll need to validate inbound IDs better.

**Comment by veger** [comment]
The reason of the wobbly (golang panic/expection?) is clear, but I would assume that inbound data is checked for validity and reported back when this is not the case. In this situation the response could be identical to the response of the API not being available (as this is basically the case).

I just wanted to report the issue, so you know its existence. For me it is not an issue as I tend/try to use correct ids... ;)

**Comment by mvdan** [comment]
@veger this panic affects the analytics/dashboard Go code, not the open source gateway. As such, I've moved the issue to our internal repo.

I'm closing this for now, but we'll post a comment once it is fixed.

**Comment by jvisker** [comment]
Was the issue ever resolved?

**Comment by veger** [comment]
Not that I know of, the ticket got closed and there was never a feedback that it now is working (I moved away from Tyk a long time ago as I changed jobs so I can/could not check).
