### ISSUE TITLE
Javascript Middleware crash with Tyke Gateway 2.4.3

### ISSUE THREAD

**Issue by Pinpin31** [TykTechnologies/tyk#1915]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Starting a gateway with javascript middleware api definition crash :

```
time="Sep 18 15:54:21" level=info msg="Detected 1 APIs"                                                                 
Etime="Sep 18 15:54:21" level=info msg="Loading API configurations."                                                     
ftime="Sep 18 15:54:21" level=info msg="Tracking hostname" api_name="Tyk Test API" domain="(no host)"                    
Mtime="Sep 18 15:54:21" level=info msg="Loading API" api_name="Tyk Test API"                                             
ttime="Sep 18 15:54:21" level=warning msg="The Health Checker is deprecated and we do no longer recommend its use."      
`time="Sep 18 15:54:21" level=info msg="Loading JS File: middleware/couchdb_auth_middleware.js"                          
Hpanic: runtime error: invalid memory address or nil pointer dereference                                                 
G[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbb8469]                                                  
                                                                                                                         
goroutine 306 [running]:                                                                                                 
Imain.(*JSVM).LoadJSPaths(0xc420250158, 0xc42040d380, 0x1, 0x1, 0x0, 0x0)                                                
@       /src/github.com/TykTechnologies/tyk/mw_js_plugin.go:346 +0x5b9                                                   
�main.processSpec(0xc4202500e0, 0xc420480150, 0x133b7c0, 0xc420275860, 0x133b7c0, 0xc420275880, 0x133b7c0, 0xc4202758a0, 
0x133b6e0, 0xc420583da0, ...)                                                                                            
>       /src/github.com/TykTechnologies/tyk/api_loader.go:217 +0xc8d                                                     
~main.loadApps.func3(0xc420480210, 0xc42000e110, 0xc420480150, 0xdf641a, 0x7, 0x1, 0xdf6dac, 0x7, 0xc420580000, 0xdfa25b,
 ...)                                                                                                                    
>       /src/github.com/TykTechnologies/tyk/api_loader.go:608 +0x268                                                     
created by main.loadApps                                                                                                 
>       /src/github.com/TykTechnologies/tyk/api_loader.go:611 +0xe68
```

**What is the expected behavior?**
No crash :)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
The tyk conf :

```
{
  "listen_port": 8080,
  "secret": "352d20ee67be67f6340b4c0605b044b7",
  "template_path": "/opt/tyk-gateway/templates",
  "tyk_js_path": "/opt/tyk-gateway/js/tyk.js",
  "middleware_path": "/opt/tyk-gateway/middleware",
  "use_db_app_configs": false,
  "app_path": "/opt/tyk-gateway/apps/",
  "storage": {
    "type": "redis",
    "host": "redis",
    "port": 6379,
    "username": "",
    "password": "",
    "database": 0,
    "optimisation_max_idle": 100
  },
  "enable_analytics": false,
  "analytics_config": {
    "type": "csv",
    "csv_dir": "/tmp",
    "mongo_url": "",
    "mongo_db_name": "",
    "mongo_collection": "",
    "purge_delay": -1,
    "ignored_ips": []
  },
  "health_check": {
    "enable_health_checks": true,
    "health_check_value_timeouts": 60
  },
  "optimisations_use_async_session_write": true,
  "enable_non_transactional_rate_limiter": true,
  "enable_sentinel_rate_limiter": false,
  "allow_master_keys": false,
  "policies": {
    "policy_source": "file",
    "policy_record_name": "/opt/tyk-gateway/policies/policies.json"
  },
  "hash_keys": true,
  "close_connections": true,
  "http_server_options": {
    "enable_websockets": true
  },
  "allow_insecure_configs": true,
  "coprocess_options": {"enable_coprocess": true,
    "coprocess_grpc_server": ""
  },
  "enable_bundle_downloader": true,
  "bundle_base_url": "",
  "global_session_lifetime": 100,
  "force_global_session_lifetime": false,
  "max_idle_connections_per_host": 100,
  "enable_jsvm":true
}

```

The api definition :

```
{
    "name": "Tyk Test API",
    "api_id": "1",
    "org_id": "default",
    "definition": {
        "location": "header",
        "key": "version"
    },
    "auth": {
        "auth_header_name": "authorization"
    },
    "custom_middleware": {
    "post": [
        {
          "name": "couchdb_auth_middleware",
          "path": "middleware/couchdb_auth_middleware.js",
          "require_session": true
        }
       ],
        "driver":"otto"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "3000-01-02 15:04",
                "use_extended_paths": true,
                "extended_paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                }
            }
        }
    },
    "proxy": {
        "listen_path": "/tyk-api-test/",
        "target_url": "http://httpbin.org",
        "strip_listen_path": true
    },
    "enable_batch_request_support": true
}
```

Sample JS middleware :

```
var couchdb = new TykJS.TykMiddleware.NewMiddleware({});

 couchdb.NewProcessRequest(function(request, session, spec) {
log("Middleware initialised");

   return couchdb.ReturnData(request, session.meta_data);
});
```

I try with docker.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
v2.4.3

It works with the latest version.

**Comment by joshblakeley** [comment]
Hi
2.4 is more than two versions back so we wont patch it - if you can move to a newer version of the gateway then that would be the best course of action.

Thanks

**Comment by buger** [comment]
Pls ensure that `/opt/tyk-gateway/js/tyk.js` is a valid file. Stacktrace itself points that JSVM was not initialized, can you show Tyk startup log?

**Comment by Pinpin31** [comment]
@joshblakeley 
Yes we schedule to the 2.7 version for this instance. We have anothers instances already migrate in 2.7.

@buger 
Good point. The tyk startup log complain on file tyk.js :

```
time="Sep 18 15:54:21" level=error msg="Could not load user's TykJS: open /opt/tyk-gateway/js/tyk.js: no such file or directory"
```
Where is this file on standard installation ?

**Comment by buger** [comment]
👌
