### ISSUE TITLE
Python plugin loader is broken

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2021]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Python plugin loader is broken if plugin has more then 2 files
**What is the expected behavior?**
Plugin should be loaded without issues
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create api definiton 
2. Add plugin bundle in api definition
3. Save API

Console errors:

Python 3.6 version
```
[Dec 11 14:47:42]  INFO main: API reload complete
[Dec 11 14:47:42] ERROR python: Middleware initialization error: load_module() missing 2 required positional arguments: 'filename' and 'details'
```

On python 3.5 version we have gateway crash:
```
yk-gateway_1          |
tyk-gateway_1          | goroutine 84289 [chan receive]:
tyk-gateway_1          | main.(*DefaultSessionManager).updateWorker(0xc4233bf9e0)
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:146 +0xa2
tyk-gateway_1          | created by main.(*DefaultSessionManager).Init
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:138 +0x3ff
tyk-gateway_1          |
tyk-gateway_1          | goroutine 84290 [chan receive]:
tyk-gateway_1          | main.(*DefaultSessionManager).updateWorker(0xc4233bf9e0)
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:146 +0xa2
tyk-gateway_1          | created by main.(*DefaultSessionManager).Init
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:138 +0x3ff
tyk-gateway_1          |
tyk-gateway_1          | goroutine 84291 [chan receive]:
tyk-gateway_1          | main.(*DefaultSessionManager).updateWorker(0xc4233bf9e0)
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:146 +0xa2
tyk-gateway_1          | created by main.(*DefaultSessionManager).Init
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:138 +0x3ff
tyk-gateway_1          |
tyk-gateway_1          | goroutine 84292 [chan receive]:
tyk-gateway_1          | main.(*DefaultSessionManager).updateWorker(0xc4233bf9e0)
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:146 +0xa2
tyk-gateway_1          | created by main.(*DefaultSessionManager).Init
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:138 +0x3ff
tyk-gateway_1          |
tyk-gateway_1          | goroutine 84293 [chan receive]:
tyk-gateway_1          | main.(*DefaultSessionManager).updateWorker(0xc4233bf9e0)
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:146 +0xa2
tyk-gateway_1          | created by main.(*DefaultSessionManager).Init
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:138 +0x3ff
tyk-gateway_1          |
tyk-gateway_1          | goroutine 84294 [chan receive]:
tyk-gateway_1          | main.(*DefaultSessionManager).updateWorker(0xc4233bf9e0)
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:146 +0xa2
tyk-gateway_1          | created by main.(*DefaultSessionManager).Init
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:138 +0x3ff
tyk-gateway_1          |
tyk-gateway_1          | goroutine 84331 [select]:
tyk-gateway_1          | github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache.(*janitor).Run(0xc4229264b0, 0xc4234fbc40)
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1037 +0x13c
tyk-gateway_1          | created by github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache.runJanitor
tyk-gateway_1          | 	/develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1056 +0x75
tyk-gateway_1          |
tyk-gateway_1          | rax    0x0
tyk-gateway_1          | rbx    0x5d
tyk-gateway_1          | rcx    0x7f32ee4a9428
tyk-gateway_1          | rdx    0x6
tyk-gateway_1          | rdi    0x3b4
tyk-gateway_1          | rsi    0x3bb
tyk-gateway_1          | rbp    0x7f32ea7b9da0
tyk-gateway_1          | rsp    0x7f32ea7b9a08
tyk-gateway_1          | r8     0xe
tyk-gateway_1          | r9     0x0
tyk-gateway_1          | r10    0x8
tyk-gateway_1          | r11    0x206
tyk-gateway_1          | r12    0x5d
tyk-gateway_1          | r13    0x7f32ea7b9bb8
tyk-gateway_1          | r14    0x7f32ea7b9bb8
tyk-gateway_1          | r15    0x2
tyk-gateway_1          | rip    0x7f32ee4a9428
tyk-gateway_1          | rflags 0x206
tyk-gateway_1          | cs     0x33
tyk-gateway_1          | fs     0x0
```
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Release-2.8 branch. Master and 2.7 branch are fine
[bundle-python-two-modules.zip](https://github.com/TykTechnologies/tyk/files/2667920/bundle-python-two-modules.zip)

**Comment by buger** [comment]
Looks like fix was not merged in this branch

**Comment by ilijabojanovic** [comment]
Verified
