### ISSUE TITLE
setup.sh ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by Dimitri-UNHCR** [TykTechnologies/tyk#212]
I am trying to get TYK running with Docker.

Everything is running ok, except for the ./setup.sh command which gives me the follwoing error:

$ ./setup.sh 127.0.0.1 www.tyk-portal-test.com
Detected a Docker VM...
Docker host address explicitly set.
Using 127.0.0.1 as Tyk host address.
Docker portal domain address explicitly set.
Using www.tyk-portal-test.com as Tyk host address.
Creating Organisation
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python2\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\python2\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\python2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python2\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ORG ID:
Adding new user
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python2\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\python2\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\python2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python2\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python2\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\python2\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\python2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python2\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by lonelycode** [comment]
What is the IP address of your Docker VM? Are you in OSX or in Linux?

**Comment by Dimitri-UNHCR** [comment]
How do I get this?

**Comment by Dimitri-UNHCR** [comment]
I am in Windows 10 PRO

**Comment by lonelycode** [comment]
Well, if you are running Linux, docker is usually on 127.0.0.1, but if you are on OSX, then you'll need to query an environment variable that's set it kitematic, just open a terminal and run:

````
~> echo $DOCKER_HOST
```

I have absolutely no idea how to get the IP in windows, [but a quick google search](https://docs.docker.com/engine/installation/windows/#container-port-redirection) tells me it's likely to be: `192.168.59.103`, of course you can always just check VirtualBox and see what the VM's IP is there.

When you explicitly set the host address in the setup.sh command, you told the script to assume Tyk was on 127.0.0.1, and therefore run all the API bootstrap commands against it, and they failed.

BTW - by replying by email you are exposing your email address in all of your comments.

**Comment by Dimitri-UNHCR** [comment]
$ echo $DOCKER_HOST
tcp://192.168.99.100:2376

Do I have to use this address in my hosts file for www.tyk-portal-test.com?
I.e. 192.168.99.100 www.tyk-portal-test.com?

**Comment by lonelycode** [comment]
Hosts file:

```
192.168.99.100    www.tyk-portal-test.com
```

Then

```
./setup.sh 192.168.99.100 www.tyk-portal-test.com
```

**Comment by Dimitri-UNHCR** [comment]
Thanks a lot! It worked!
