### ISSUE TITLE
Tyk loop: Gateway panic when use debug feature for intenal endpoint

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2159]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When use debug feature on endpoint with enabled looping gateway panics
**What is the expected behavior?**
Gateway should not panic
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Import api definitions from ticket
2. Open API definition
3. Go to debug tab
4. Send debug call to /get endpoint 

Actual:
Gateway panic in console log

Here is log:
```
[Mar 12 10:56:04]  INFO main: API reload complete
2019/03/12 10:56:08 http: panic serving 127.0.0.1:58450: runtime error: invalid memory address or nil pointer dereference
goroutine 613 [running]:
net/http.(*conn).serve.func1(0xc420e9c280)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x19b1180, 0x2290690)
	/usr/local/go/src/runtime/panic.go:502 +0x229
main.(*DummyProxyHandler).ServeHTTP(0xc420c954e0, 0x1cbf740, 0xc4210ad1c0, 0xc4213d8200)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/api_loader.go:507 +0x39e
main.createMiddleware.func1.1(0x1cbf740, 0xc4210ad1c0, 0xc4213d8200)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/middleware.go:116 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4210ad080, 0x1cbf740, 0xc4210ad1c0, 0xc4213d8200)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x1cbf740, 0xc4210ad1c0, 0xc4213d8200)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/middleware.go:116 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4210ad0c0, 0x1cbf740, 0xc4210ad1c0, 0xc4213d8200)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x1cbf740, 0xc4210ad1c0, 0xc4213d8200)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/middleware.go:116 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4210ad100, 0x1cbf740, 0xc4210ad1c0, 0xc4213d8200)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x1cbf740, 0xc4210ad1c0, 0xc4213d8200)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/middleware.go:116 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4210ad140, 0x1cbf740, 0xc4210ad1c0, 0xc4213d8200)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x1cbf740, 0xc4210ad1c0, 0xc4213d8200)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/middleware.go:116 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4210ad180, 0x1cbf740, 0xc4210ad1c0, 0xc4213d8200)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.traceHandler(0x1cbf700, 0xc42043a000, 0xc42136a900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/tracing.go:123 +0x925
net/http.HandlerFunc.ServeHTTP(0x1b89250, 0x1cbf700, 0xc42043a000, 0xc42136a900)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4209bc4e0, 0x1cbf700, 0xc42043a000, 0xc42136a900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0xed
main.InstrumentationMW.func1(0x1cbf700, 0xc42043a000, 0xc42136a500)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/instrumentation_handlers.go:54 +0xa0
net/http.HandlerFunc.ServeHTTP(0xc420c89700, 0x1cbf700, 0xc42043a000, 0xc42136a500)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.controlAPICheckClientCertificate.func1(0x1cbf700, 0xc42043a000, 0xc42136a500)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/main.go:339 +0x20a
net/http.HandlerFunc.ServeHTTP(0xc420c89720, 0x1cbf700, 0xc42043a000, 0xc42136a500)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.checkIsAPIOwner.func1(0x1cbf700, 0xc42043a000, 0xc42136a500)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/main.go:417 +0x1c2
net/http.HandlerFunc.ServeHTTP(0xc420f68de0, 0x1cbf700, 0xc42043a000, 0xc42136a500)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.stripSlashes.func1(0x1cbf700, 0xc42043a000, 0xc42136a400)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/main.go:325 +0x136
net/http.HandlerFunc.ServeHTTP(0xc420c89740, 0x1cbf700, 0xc42043a000, 0xc42136a400)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.StripPrefix.func1(0x1cbf700, 0xc42043a000, 0xc42136a300)
	/usr/local/go/src/net/http/server.go:1986 +0x19a
net/http.HandlerFunc.ServeHTTP(0xc420f68e10, 0x1cbf700, 0xc42043a000, 0xc42136a300)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4209bc480, 0x1cbf700, 0xc42043a000, 0xc42136a300)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0xed
main.mainHandler.ServeHTTP(0x1cbf700, 0xc42043a000, 0xc42136a100)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/main.go:1203 +0x81
net/http.serverHandler.ServeHTTP(0xc4200b6270, 0x1cbf700, 0xc42043a000, 0xc42136a100)
	/usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc420e9c280, 0x1cc0980, 0xc420ed7240)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2798 +0x27b
```

Api definition:
```
{
    "id": "5c8780039633d70601740c89",
    "name": "api",
    "slug": "api",
    "api_id": "3ae79af7cb144bea58ac7dac31e39d64",
    "org_id": "5c82cfaa9633d70afd898c92",
    "use_keyless": true,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": "Authorization",
        "use_certificate": false
    },
    "use_basic_auth": false,
    "basic_auth": {
        "disable_caching": false,
        "cache_ttl": 0
    },
    "use_mutual_tls_auth": false,
    "client_certificates": [],
    "upstream_certificates": {},
    "pinned_public_keys": {},
    "enable_jwt": false,
    "use_standard_auth": false,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "jwt_issued_at_validation_skew": 0,
    "jwt_expires_at_validation_skew": 0,
    "jwt_not_before_validation_skew": 0,
    "jwt_skip_kid": false,
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "hmac_allowed_algorithms": [],
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version",
        "strip_path": false
    },
    "version_data": {
        "not_versioned": true,
        "default_version": "",
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {
                    "url_rewrites": [
                        {
                            "path": "get",
                            "method": "GET",
                            "match_pattern": "get",
                            "rewrite_to": "tyk://loop/anything",
                            "triggers": [],
                            "MatchRegexp": null
                        }
                    ],
                    "internal": [
                        {
                            "path": "get",
                            "method": "GET"
                        }
                    ]
                },
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/api/",
        "target_url": "http://httpbin.org/",
        "disable_strip_slash": false,
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "port_data_path": "",
            "target_path": "",
            "use_target_list": false,
            "cache_timeout": 0,
            "endpoint_returns_list": false
        },
        "transport": {
            "ssl_insecure_skip_verify": false,
            "ssl_ciphers": [],
            "ssl_min_version": 0,
            "proxy_url": ""
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false,
        "cache_control_ttl_header": ""
    },
    "session_lifetime": 0,
    "active": true,
    "internal": false,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "enable_ip_blacklisting": false,
    "blacklisted_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "certificates": [],
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false,
    "config_data": {},
    "tag_headers": [],
    "global_rate_limit": {
        "rate": 0,
        "per": 0
    },
    "strip_auth_data": false
}
```

Internal api:
```
{
    "id": "5c8780149633d70601740c8a",
    "name": "loop",
    "slug": "loop",
    "api_id": "4912c61f1a7548e844af0769424c9c3f",
    "org_id": "5c82cfaa9633d70afd898c92",
    "use_keyless": false,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": "Authorization",
        "use_certificate": false
    },
    "use_basic_auth": false,
    "basic_auth": {
        "disable_caching": false,
        "cache_ttl": 0
    },
    "use_mutual_tls_auth": false,
    "client_certificates": [],
    "upstream_certificates": {},
    "pinned_public_keys": {},
    "enable_jwt": false,
    "use_standard_auth": true,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "jwt_issued_at_validation_skew": 0,
    "jwt_expires_at_validation_skew": 0,
    "jwt_not_before_validation_skew": 0,
    "jwt_skip_kid": false,
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "hmac_allowed_algorithms": [],
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version",
        "strip_path": false
    },
    "version_data": {
        "not_versioned": true,
        "default_version": "",
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {
                    "internal": []
                },
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/loop/",
        "target_url": "http://httpbin.org/",
        "disable_strip_slash": false,
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "port_data_path": "",
            "target_path": "",
            "use_target_list": false,
            "cache_timeout": 0,
            "endpoint_returns_list": false
        },
        "transport": {
            "ssl_insecure_skip_verify": false,
            "ssl_ciphers": [],
            "ssl_min_version": 0,
            "proxy_url": ""
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false,
        "cache_control_ttl_header": ""
    },
    "session_lifetime": 0,
    "active": true,
    "internal": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "enable_ip_blacklisting": false,
    "blacklisted_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "certificates": [],
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false,
    "config_data": {},
    "tag_headers": [],
    "global_rate_limit": {
        "rate": 0,
        "per": 0
    },
    "strip_auth_data": false
}
```
Image:
![Screen Shot 2019-03-12 at 11 37 05 AM](https://user-images.githubusercontent.com/8557292/54194095-bd7a6900-44bb-11e9-8f0a-26ffa9769016.png)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master/Release-2.8

**Comment by ilijabojanovic** [comment]
Verified
