### ISSUE TITLE
Tyk crashes when service discovery is used in combination with mesosphere/marathon

### ISSUE THREAD

**Issue by veger** [TykTechnologies/tyk#218]
We are trying to enable service discovery for our APIs.

We are using [Mesosphere/Marathon](https://mesosphere.github.io/marathon/), which returns the following JSON for one of our services:
```
{
 "tasks": [{
  "id": "myservice.7fc21d4c-eabb-11e5-b381-066c48d09c8f",
  "host": "ec2-xxx-xxx-xxx-xxx.eu-XXXXX.compute.amazonaws.com",
  "ipAddresses": [],
  "ports": [31909],
  "startedAt": "2016-03-15T14:37:55.941Z",
  "stagedAt": "2016-03-15T14:37:52.792Z",
  "version": "2016-03-15T14:37:52.726Z",
  "slaveId": "d70867df-fdb2-4889-abeb-0829c742fded-S2",
  "appId": "/myservice"
 }]
}
```

We are using the following service discovery options:
```
target_list: true
data_path: tasks.host
port_data_path: tasks.ports[0]
```
(but also tried all kinds of other variations)

For any of these variations Tyk crashes with
```

2016/03/15 15:17:15 http: panic serving 172.31.46.212:40034: interface conversion: interface is nil, not string
goroutine 240 [running]:
net/http.(*conn).serve.func1(0xc8203c8a50, 0x7f62a6bf6070, 0xc820029750)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
main.(*ServiceDiscovery).GetObject(0xc8200ca590, 0xc820475990, 0x0, 0x0)
	/home/tyk/go/src/github.com/lonelycode/tyk/service_discovery.go:114 +0xa3
main.(*ServiceDiscovery).GetHostname(0xc8200ca590, 0xc820475990, 0x0, 0x0)
	/home/tyk/go/src/github.com/lonelycode/tyk/service_discovery.go:126 +0x73
main.(*ServiceDiscovery).GetSubObjectFromList(0xc8200ca590, 0xc820475750, 0x2)
	/home/tyk/go/src/github.com/lonelycode/tyk/service_discovery.go:183 +0x446
main.(*ServiceDiscovery).ProcessRawData(0xc8200ca590, 0xc8201dcd80, 0x175, 0x0, 0x0, 0x0, 0x0)
	/home/tyk/go/src/github.com/lonelycode/tyk/service_discovery.go:238 +0x695
main.(*ServiceDiscovery).GetTarget(0xc8200ca590, 0xc8205684e0, 0x5a, 0x0, 0x0, 0x0, 0x0)
	/home/tyk/go/src/github.com/lonelycode/tyk/service_discovery.go:271 +0xc4
main.GetURLFromService(0xc8201e4a00, 0x0, 0x0, 0x0, 0x0)
	/home/tyk/go/src/github.com/lonelycode/tyk/tyk_reverse_proxy_clone.go:29 +0x1a6
main.TykNewSingleHostReverseProxy.func1(0xc8203c36c0)
	/home/tyk/go/src/github.com/lonelycode/tyk/tyk_reverse_proxy_clone.go:102 +0x71
main.(*ReverseProxy).WrappedServeHTTP(0xc820572840, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0, 0x56e82700, 0x0)
	/home/tyk/go/src/github.com/lonelycode/tyk/tyk_reverse_proxy_clone.go:359 +0x4e0
main.(*ReverseProxy).ServeHTTP(0xc820572840, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0, 0xc820474fd0)
	/home/tyk/go/src/github.com/lonelycode/tyk/tyk_reverse_proxy_clone.go:293 +0x4a
main.SuccessHandler.ServeHTTP(0xc8202797e0, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0, 0x0)
	/home/tyk/go/src/github.com/lonelycode/tyk/handler_success.go:264 +0x47f
main.DummyProxyHandler.ServeHTTP(0xc8202797e0, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/handler_proxy.go:13 +0x42
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572980, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc8205729c0, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572a00, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572a40, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572a80, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572ac0, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572b00, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572b40, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572bc0, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572c40, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572c80, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572cc0, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572d00, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
main.CreateMiddleware.func1.1(0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware.go:54 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc820572d40, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8203f1450, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/home/tyk/go/src/github.com/gorilla/mux/mux.go:98 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc8205b2bd0, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc820377620, 0x7f62a6bfb048, 0xc8203c8bb0, 0xc8203c35e0)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8203c8a50)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

What are we doing wrong??? And are there other experiences with the combination of Tyk and Mesosphere/Marathon?

Additionally, it is **nasty** that the complete gateway crashes (breaking our **complete** application) on such issues. Is there anything to do in order to prevent crashes and get log errors???

**Comment by lonelycode** [comment]
We've never tested against mesosphere, here's all the tested integrations and data structures we explicitly support:

https://github.com/TykTechnologies/tyk/blob/master/service_discovery_test.go

Should help in finding a combination that works.

The Service Discovery client needs to handle dynamic, un-typed JSON objects based on rules provided by the user, you are right it should not crash, but runtime type-assertions are brittle without reflection, which I'd rather avoid. There's probably catches that could go (in we have some in place already) to stop execution before a panic occurs.

Of course, you can always pitch in and help out with some of the type assertions if you'd like to contribute :-)

**Comment by JosephEarl** [comment]
I think Mesosphere cannot be done with the current configuration options:

* The endpoint returns a list, but it is inside an element "tasks"
* However the list inside tasks is not nested inside a string, so parentPath cannot be used
* The ports is an array

**Comment by veger** [comment]
We were wondering about this too... But didn't have time to take a better look at it since I wrote this report.

Thank you very much for your effort in adding the required changes, we will certainly take a look at it soon and fix our servers.
