### ISSUE TITLE
2.7.7 signal SIGSEGV: segmentation violation code

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#2192]
Tyk 2.7.7 hybrid

Seeing this on bootup

```
me    | time="Apr  3 16:10:19" level=debug msg="Using RPC cache purge"
me    | time="Apr  3 16:10:19" level=debug msg="Getting exp for key: analytics-tyk-system-analytics"
me    | time="Apr  3 16:10:19" level=debug msg="Getting exp for key: analytics-tyk-system-analytics"
me    | time="Apr  3 16:10:20" level=error msg="No gRPC URL is set"
me    | time="Apr  3 16:10:20" level=debug msg="Notifier will not work in hybrid mode"
me    | time="Apr  3 16:10:20" level=debug msg="Storage Engine already initialised..."
me    | panic: runtime error: invalid memory address or nil pointer dereference
me    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa41f46]
me    |
me    | goroutine 605 [running]:
me    | github.com/TykTechnologies/tyk/vendor/github.com/lonelycode/gorpc.(*DispatcherClient).Call(0x0, 0xe7150e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
me    | 	/src/github.com/TykTechnologies/tyk/vendor/github.com/lonelycode/gorpc/dispatcher.go:446 +0x26
me    | main.(*RPCPurger).PurgeCache(0xc42098efc8)
me    | 	/src/github.com/TykTechnologies/tyk/rpc_analytics_purger.go:45 +0x5f
me    | main.RPCPurger.PurgeLoop(0x1045420, 0xc42044b9c0, 0xc4201428a0)
me    | 	/src/github.com/TykTechnologies/tyk/rpc_analytics_purger.go:39 +0x42
me    | created by main.setupGlobals.func2
me    | 	/src/github.com/TykTechnologies/tyk/main.go:164 +0xb8
me    | 2019/04/03 16:10:20.411503 [INFO] (runner) child process died
me    | 2019/04/03 16:10:20.610822 [ERR] (cli) child process died with exit code 2
me    | time="Apr  3 16:11:43" level=debug msg="Received DRL data: {21e3e29c41b4 solo-XXXX-5bbf-43ed-b98e-XXXX 1 0 }"
```

**Comment by joshblakeley** [comment]
Hi can you share your gateway config please

**Comment by bitsofinfo** [comment]
Please see the tyk.conf in support ticket 3160

**Comment by joshblakeley** [comment]
Thanks

**Comment by joshblakeley** [comment]
Can you set the analytics_config block to just this:
```
"analytics_config": {
        "type": "rpc"
    },
```

**Comment by bitsofinfo** [comment]
Is this a required change from 2.6.x?

**Comment by joshblakeley** [comment]
No required change but the hybrid configuration should only need that one field as a minimum - the other are optional - im trying to see if we can isolate the panic cause as we have not seen this issue in any of our hybrid QA envs

**Comment by bitsofinfo** [comment]
appears to have booted up OK now w/ that change

**Comment by joshblakeley** [comment]
Closing this for now let me know if you have any more trouble
