### ISSUE TITLE
Logstash logger panics when accessing Keys API

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2250]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Enabling logstash and querying `/tyk/keys` gives:
```
May 2 11:48:24 ovh-sb1udgtwf8 tyk-python: 2019/05/02 11:48:24 http: panic serving 10.156.216.26:37498: interface conversion: error is *os.SyscallError, not syscall.Errno
May 2 11:48:24 ovh-sb1udgtwf8 tyk-python: goroutine 773111 [running]:
May 2 11:48:24 ovh-sb1udgtwf8 tyk-python: net/http.(*conn).serve.func1(0xc4206761e0)
May 2 11:48:24 ovh-sb1udgtwf8 tyk-python: /usr/local/go/src/net/http/server.go:1726 +0xd0
May 2 11:48:24 ovh-sb1udgtwf8 tyk-python: panic(0xdce0c0, 0xc42269be80)
May 2 11:48:24 ovh-sb1udgtwf8 tyk-python: /usr/local/go/src/runtime/panic.go:502 +0x229
May 2 11:48:24 ovh-sb1udgtwf8 tyk-python: github.com/TykTechnologies/tyk/vendor/github.com/netbrain/goautosocket.(*TCPClient).Write(0xc420095770, 0xc422be8000, 0x99, 0x10c, 0x0, 0x0, 0x0)
May 2 11:48:24 ovh-sb1udgtwf8 tyk-python: /src/github.com/TykTechnologies/tyk/vendor/github.com/netbrain/goautosocket/tcp_client.go:299 +0x3a5
```
**What is the expected behavior?**
It should not panic
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See above
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
1.7.1 and higher

**Comment by buger** [comment]
I've forked goautosocket library and fix error handling there https://github.com/TykTechnologies/goautosocket
