### ISSUE TITLE
Dashboard v0.9.7.3 on Docker Hub

### ISSUE THREAD

**Issue by byrnedo** [TykTechnologies/tyk#229]
Would be nice if the mini patch was up on the hub. Or is it up there as 0.9.7.2?

**Comment by lonelycode** [comment]
The docker images are built off our APT repositories, since the patch is not available there it won't show up on docker hub. Suggest using 0.9.7.2 and mounting binary from the patch into the container

**Comment by byrnedo** [comment]
Ok, can do. 

Just fyi, trying the 'mailgun' email provider with 0.9.7.2 gave me this:

```
ime="2016-03-31T08:44:40Z" level=warning msg="USING SORT: approved" 
time="2016-03-31T08:44:43Z" level=warning msg="USING SORT: approved" 
time="2016-03-31T08:44:46Z" level=warning msg="Destroying existing key: 8195e2b4" 
time="2016-03-31T08:44:46Z" level=warning msg="Deleting HASHED key" 
time="2016-03-31T08:44:46Z" level=warning msg="&{DELETE http://tyk-gateway.service.consul:8080/tyk/keys/8195e2b4?api_id=7b393528bfca4549506b7083657d76e8&hashed=1 HTTP/1.1 1 1 map[X-Tyk-Authorization:[hImj4S27MlcVH+2u0S8riQwQ5rIao5QKbEV0C2MLJ04]] <nil> 0 [] false tyk-gateway.service.consul:8080 map[] map[] <nil> map[]   <nil> <nil>}" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x471cb3]

goroutine 174 [running]:
main.NotifyUserByEmailOfKeyRequestSuccess(0xc82008b040, 0xc8202f8580, 0x38, 0x0, 0x0)
	/home/tyk/go/src/github.com/lonelycode/tyk-analytics/PortalEmailMethods.go:60 +0x363
created by main.KeyRequestHelper.NotifyParties
	/home/tyk/go/src/github.com/lonelycode/tyk-analytics/PortalKeyRequestHandler.go:102 +0x2ec

goroutine 1 [IO wait]:

```

**Comment by lonelycode** [comment]
Yeah, it won't work with 0.9.7.2, since the email library isn't part of that build. But yeah, ugly error, will look into cleaning up.

**Comment by byrnedo** [comment]
Thanks for the info, will close this.
