### ISSUE TITLE
TestGetPaginatedClientTokens test fails

### ISSUE THREAD

**Issue by furkansenharputlu** [TykTechnologies/tyk#2344]
This test sometimes fails with a panic in 1.11 builds.
https://travis-ci.org/TykTechnologies/tyk/builds/543610257?utm_source=github_status&utm_medium=notification
```=== RUN   TestGetPaginatedClientTokens/Get_list_of_tokens_with_a_page_query_param_lesser_than_0
time="Jun 10 07:28:14" level=info msg="Getting client tokens sorted list:oauth-client-tokens.71b878ba-a17e-4abb-b8fe-9d4abb82ec53" 
2019/06/10 07:28:14 http: panic serving 127.0.0.1:39496: runtime error: slice bounds out of range
goroutine 65090 [running]:
net/http.(*conn).serve.func1(0xc001157720)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1746 +0x17c
panic(0x15c6ea0, 0x26ec410)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/runtime/panic.go:513 +0x1b9
github.com/TykTechnologies/tyk/gateway.(*RedisOsinStorageInterface).GetPaginatedClientTokens(0xc0007784e0, 0xc000fe721e, 0x24, 0x1, 0x0, 0x15bb180, 0x17ccff0, 0xc00227fb38, 0xb04691, 0xc000a7d178)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/oauth_manager.go:594 +0x83f
github.com/TykTechnologies/tyk/gateway.oAuthClientTokensHandler(0x1be66a0, 0xc0000f1ce0, 0xc000f9c500)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/api.go:1679 +0x263
net/http.HandlerFunc.ServeHTTP(0x17c98e8, 0x1be66a0, 0xc0000f1ce0, 0xc000f9c500)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00122b080, 0x1be66a0, 0xc0000f1ce0, 0xc000f9c500)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0x17f
github.com/TykTechnologies/tyk/gateway.InstrumentationMW.func1(0x1be66a0, 0xc0000f1ce0, 0xc000f9c300)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/instrumentation_handlers.go:54 +0xdc
net/http.HandlerFunc.ServeHTTP(0xc000b52f20, 0x1be66a0, 0xc0000f1ce0, 0xc000f9c300)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
github.com/TykTechnologies/tyk/gateway.controlAPICheckClientCertificate.func1(0x1be66a0, 0xc0000f1ce0, 0xc000f9c300)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/server.go:355 +0xf5
net/http.HandlerFunc.ServeHTTP(0xc000b52f40, 0x1be66a0, 0xc0000f1ce0, 0xc000f9c300)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
github.com/TykTechnologies/tyk/gateway.checkIsAPIOwner.func1(0x1be66a0, 0xc0000f1ce0, 0xc000f9c300)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/server.go:433 +0x218
net/http.HandlerFunc.ServeHTTP(0xc000f433b0, 0x1be66a0, 0xc0000f1ce0, 0xc000f9c300)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
github.com/TykTechnologies/tyk/gateway.stripSlashes.func1(0x1be66a0, 0xc0000f1ce0, 0xc000f9c300)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/server.go:341 +0x1fc
net/http.HandlerFunc.ServeHTTP(0xc000b52f60, 0x1be66a0, 0xc0000f1ce0, 0xc000f9c300)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
net/http.StripPrefix.func1(0x1be66a0, 0xc0000f1ce0, 0xc000f9c200)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:2003 +0x35c
net/http.HandlerFunc.ServeHTTP(0xc000f433e0, 0x1be66a0, 0xc0000f1ce0, 0xc000f9c200)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00122b020, 0x1be66a0, 0xc0000f1ce0, 0xc000f9c200)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0x17f
github.com/TykTechnologies/tyk/gateway.mainHandler.ServeHTTP(0x1be66a0, 0xc0000f1ce0, 0xc000f9c000)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/server.go:1246 +0xd7
net/http.serverHandler.ServeHTTP(0xc00009da00, 0x1be66a0, 0xc0000f1ce0, 0xc000f9c000)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:2741 +0xc5
net/http.(*conn).serve(0xc001157720, 0x1be7b20, 0xc002be13c0)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1847 +0x80b
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:2851 +0x4c6
time="Jun 10 07:28:14" level=info msg="Getting client tokens sorted list:oauth-client-tokens.71b878ba-a17e-4abb-b8fe-9d4abb82ec53" 
2019/06/10 07:28:14 http: panic serving 127.0.0.1:39500: runtime error: slice bounds out of range
goroutine 90841 [running]:
net/http.(*conn).serve.func1(0xc00183aaa0)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1746 +0x17c
panic(0x15c6ea0, 0x26ec410)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/runtime/panic.go:513 +0x1b9
github.com/TykTechnologies/tyk/gateway.(*RedisOsinStorageInterface).GetPaginatedClientTokens(0xc0007784e0, 0xc00144637e, 0x24, 0x1, 0x0, 0x15bb180, 0x17ccff0, 0xc001b4db38, 0xb04691, 0xc000f99058)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/oauth_manager.go:594 +0x83f
github.com/TykTechnologies/tyk/gateway.oAuthClientTokensHandler(0x1be66a0, 0xc0026030a0, 0xc00171c400)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/api.go:1679 +0x263
net/http.HandlerFunc.ServeHTTP(0x17c98e8, 0x1be66a0, 0xc0026030a0, 0xc00171c400)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00122b080, 0x1be66a0, 0xc0026030a0, 0xc00171c400)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0x17f
github.com/TykTechnologies/tyk/gateway.InstrumentationMW.func1(0x1be66a0, 0xc0026030a0, 0xc00171c200)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/instrumentation_handlers.go:54 +0xdc
net/http.HandlerFunc.ServeHTTP(0xc000b52f20, 0x1be66a0, 0xc0026030a0, 0xc00171c200)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
github.com/TykTechnologies/tyk/gateway.controlAPICheckClientCertificate.func1(0x1be66a0, 0xc0026030a0, 0xc00171c200)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/server.go:355 +0xf5
net/http.HandlerFunc.ServeHTTP(0xc000b52f40, 0x1be66a0, 0xc0026030a0, 0xc00171c200)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
github.com/TykTechnologies/tyk/gateway.checkIsAPIOwner.func1(0x1be66a0, 0xc0026030a0, 0xc00171c200)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/server.go:433 +0x218
net/http.HandlerFunc.ServeHTTP(0xc000f433b0, 0x1be66a0, 0xc0026030a0, 0xc00171c200)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
github.com/TykTechnologies/tyk/gateway.stripSlashes.func1(0x1be66a0, 0xc0026030a0, 0xc00171c200)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/server.go:341 +0x1fc
net/http.HandlerFunc.ServeHTTP(0xc000b52f60, 0x1be66a0, 0xc0026030a0, 0xc00171c200)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
net/http.StripPrefix.func1(0x1be66a0, 0xc0026030a0, 0xc00171c100)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:2003 +0x35c
net/http.HandlerFunc.ServeHTTP(0xc000f433e0, 0x1be66a0, 0xc0026030a0, 0xc00171c100)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1964 +0x52
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00122b020, 0x1be66a0, 0xc0026030a0, 0xc00171c100)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0x17f
github.com/TykTechnologies/tyk/gateway.mainHandler.ServeHTTP(0x1be66a0, 0xc0026030a0, 0xc000c73f00)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/gateway/server.go:1246 +0xd7
net/http.serverHandler.ServeHTTP(0xc00009da00, 0x1be66a0, 0xc0026030a0, 0xc000c73f00)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:2741 +0xc5
net/http.(*conn).serve(0xc00183aaa0, 0x1be7b20, 0xc0013cf6c0)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:1847 +0x80b
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/net/http/server.go:2851 +0x4c6
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x143844e]````

**Comment by furkansenharputlu** [comment]
Fixed by #2345
