### ISSUE TITLE
Timeout on service discovery endpoint causes panic

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2382]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behaviour?**
Panick when url is not accessable/available etc.

```Failed target lookup: Get https://blabla.com/app: dial tcp 52.209.145.203:443: i/o timeout"
2019/07/05 22:23:58 http: panic serving 172.20.0.1:50350: runtime error: invalid memory address or nil pointer dereference
```

**What is the expected behavior?**
If the SD is not available, Tyk should handle the timeout without panicking

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create an api with an SD to a non-existing endpoint and call this api

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
1.8.1

**Comment by letzya** [comment]
Full panic
``````
time="Jul  5 22:23:58" level=error msg="[PROXY] [SERVICE DISCOVERY] Failed target lookup: Get https://apidev.hiveo.fr/eureka/apps/organisation: dial tcp 52.209.145.203:443: i/o timeout"
2019/07/05 22:23:58 http: panic serving 172.20.0.1:50350: runtime error: invalid memory address or nil pointer dereference
goroutine 713959 [running]:
net/http.(*conn).serve.func1(0xc425f170e0)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0xdc1ca0, 0x16a96f0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/TykTechnologies/tyk/apidef.(*HostList).Len(0x0, 0x0)
	/src/github.com/TykTechnologies/tyk/apidef/host_list.go:51 +0x2b
main.nextTarget(0x0, 0xc429b24a80, 0x2, 0x2, 0xc422bd78c0, 0xf04ef3)
	/src/github.com/TykTechnologies/tyk/reverse_proxy.go:118 +0xa6
main.TykNewSingleHostReverseProxy.func2(0xc426fc1800)
	/src/github.com/TykTechnologies/tyk/reverse_proxy.go:208 +0x85
main.(*ReverseProxy).WrappedServeHTTP(0xc421868fa0, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00, 0x1, 0x0)
	/src/github.com/TykTechnologies/tyk/reverse_proxy.go:601 +0x574
main.(*ReverseProxy).ServeHTTP(0xc421868fa0, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00, 0x19)
	/src/github.com/TykTechnologies/tyk/reverse_proxy.go:376 +0x148
main.(*SuccessHandler).ServeHTTP(0xc429ad71e0, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00, 0x0)
	/src/github.com/TykTechnologies/tyk/handler_success.go:322 +0x235
main.(*DummyProxyHandler).ServeHTTP(0xc429ad71e0, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/api_loader.go:529 +0x62d
main.createMiddleware.func1.1(0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/middleware.go:119 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4233a0340, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/middleware.go:119 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4233a0380, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/middleware.go:119 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4233a03c0, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/middleware.go:119 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4233a0400, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/middleware.go:119 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4233a0440, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/middleware.go:119 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4233a0480, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/middleware.go:119 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4233a04c0, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/middleware.go:119 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4233a0500, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/middleware.go:119 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4233a0540, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
main.createMiddleware.func1.1(0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/middleware.go:119 +0xe8f
net/http.HandlerFunc.ServeHTTP(0xc4233a0580, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/vendor/github.com/rs/cors/cors.go:190 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc429ad7200, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4215af6e0, 0x10d7840, 0xc4202a61c0, 0xc426fc0f00)
	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0xed
main.mainHandler.ServeHTTP(0x10d7840, 0xc4202a61c0, 0xc426fc0d00)
	/src/github.com/TykTechnologies/tyk/main.go:1211 +0x81
net/http.serverHandler.ServeHTTP(0xc4202be4e0, 0x10d7840, 0xc4202a61c0, 0xc426fc0d00)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc425f170e0, 0x10d8a80, 0xc422d08440)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b```
