### ISSUE TITLE
Enforced timeout causes panics

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2420]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When we have enabled enforced timeout plugin on some endpoint, gateway panics in logs
**What is the expected behavior?**
Gateway should not panics
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create api definition 
2. Enable enforced timeout on some endpoint 
3. Trigger call to that endpoint

Actual:
Gateway panics

Here is log:
```
tyk-gateway_1    | 2019/07/23 19:15:06 http: panic serving 172.19.0.1:59098: interface conversion: interface {} is *int, not *float64
tyk-gateway_1    | goroutine 2531 [running]:
tyk-gateway_1    | net/http.(*conn).serve.func1(0xc4209f4b40)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1726 +0xd0
tyk-gateway_1    | panic(0xf6a040, 0xc420016200)
tyk-gateway_1    | 	/usr/local/go/src/runtime/panic.go:502 +0x229
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.(*ReverseProxy).CheckHardTimeoutEnforced(0xc4201f7770, 0xc42088f500, 0xc42094cf00, 0x7566286e6f697463, 0x74696177202c636e)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/reverse_proxy.go:419 +0x1c7
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.(*ReverseProxy).WrappedServeHTTP(0xc4201f7770, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00, 0x1, 0x0)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/reverse_proxy.go:549 +0x2485
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.(*ReverseProxy).ServeHTTP(0xc4201f7770, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00, 0x17)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/reverse_proxy.go:395 +0x148
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.(*SuccessHandler).ServeHTTP(0xc4206a7640, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00, 0x0)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/handler_success.go:307 +0x235
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.(*DummyProxyHandler).ServeHTTP(0xc4206a7640, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/api_loader.go:525 +0x63d
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40a00, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40a40, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40a80, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40ac0, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40b00, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40b40, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40b80, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40bc0, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40c00, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40c40, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40c80, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40cc0, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40d00, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40d40, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40d80, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40dc0, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:154 +0xac1
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420a40e00, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420897b60, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cf00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0xed
tyk-gateway_1    | github.com/TykTechnologies/tyk/gateway.mainHandler.ServeHTTP(0x12c3aa0, 0xc4200d8fc0, 0xc42094cd00)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/gateway/server.go:1253 +0xa5
tyk-gateway_1    | net/http.serverHandler.ServeHTTP(0xc4201d81a0, 0x12c3aa0, 0xc4200d8fc0, 0xc42094cd00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:2697 +0xbc
tyk-gateway_1    | net/http.(*conn).serve(0xc4209f4b40, 0x12c4e60, 0xc420a41140)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1830 +0x651
tyk-gateway_1    | created by net/http.(*Server).Serve
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:2798 +0x27b
```
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master (ac44ab6385b2f3df6d5f9c0ea5584bcce18523ab)

**Comment by gernest** [comment]
I already submitted a  fix for  this in #2410
