### ISSUE TITLE
Panic creating new developer

### ISSUE THREAD

**Issue by byrnedo** [TykTechnologies/tyk#249]
I created a developer and got:

```
RROR 2016/04/27 14:06:02.078347 panic_handler.go:26: PANIC
URL: /api/portal/developers/false
ERROR: Invalid input to ObjectIdHex: "false"
STACK:
goroutine 194 [running]:
github.com/gocraft/web.(*Router).handlePanic(0xc82025a840, 0xc820015680, 0xc8200156a0, 0xa60f80, 0xc8204d9480)
    /home/tyk/go/src/github.com/gocraft/web/router_serve.go:251 +0x34e
github.com/gocraft/web.(*Router).ServeHTTP.func1(0xc82025a840, 0xc820015680)
    /home/tyk/go/src/github.com/gocraft/web/router_serve.go:43 +0x68
panic(0xa60f80, 0xc8204d9480)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
gopkg.in/mgo.v2/bson.ObjectIdHex(0xc82026193e, 0x5, 0x0, 0x0)
    /home/tyk/go/src/gopkg.in/mgo.v2/bson/bson.go:175 +0x210
main.(*APIContext).DeletePortalDeveloper(0xc82021d2f8, 0x7fc3e9902ab8, 0xc820015680, 0xc8200156a0)
    /home/tyk/go/src/github.com/lonelycode/tyk-analytics/PortalAPIMethods.go:719 +0x102
reflect.Value.call(0xaf26a0, 0xde5ed0, 0x13, 0xc70d58, 0x4, 0xc820420ac8, 0x3, 0x3, 0x0, 0x0, ...)
    /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0xaf26a0, 0xde5ed0, 0x13, 0xc820420ac8, 0x3, 0x3, 0x0, 0x0, 0x0)
    /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/gocraft/web.middlewareStack.func1(0x7fc3e9902ab8, 0xc820015680, 0xc8200156a0)
    /home/tyk/go/src/github.com/gocraft/web/router_serve.go:113 +0xad4
main.(*APIContext).ApiAuthorisationRequired(0xc82021d2f8, 0x7fc3e9902ab8, 0xc820015680, 0xc8200156a0, 0xc8204d9370)
    /home/tyk/go/src/github.com/lonelycode/tyk-analytics/Main.go:425 +0x37b
reflect.Value.call(0xb2e1a0, 0xde5e38, 0x13, 0xc70d58, 0x4, 0xc820421060, 0x4, 0x4, 0x0, 0x0, ...)
    /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0xb2e1a0, 0xde5e38, 0x13, 0xc820421060, 0x4, 0x4, 0x0, 0x0, 0x0)
    /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/gocraft/web.(*middlewareHandler).invoke(0xc820345a70, 0xc6d840, 0xc82021d2f8, 0x16, 0x7fc3e9902ab8, 0xc820015680, 0xc8200156a0, 0xc8204d9370)
    /home/tyk/go/src/github.com/gocraft/web/router_serve.go:133 +0x286
github.com/gocraft/web.middlewareStack.func1(0x7fc3e9902ab8, 0xc820015680, 0xc8200156a0)
    /home/tyk/go/src/github.com/gocraft/web/router_serve.go:122 +0x1a5
github.com/gocraft/web.StaticMiddlewareFromDir.func1(0x7fc3e9902ab8, 0xc820015680, 0xc8200156a0, 0xc8204d9370)
    /home/tyk/go/src/github.com/gocraft/web/static_middleware.go:23 +0x66e
github.com/gocraft/web.(*middlewareHandler).invoke(0xc820345200, 0xc2b200, 0xc82021d2e8, 0x16, 0x7fc3e9902ab8, 0xc820015680, 0xc8200156a0, 0xc8204d9370)
    /home/tyk/go/src/github.com/gocraft/web/router_serve.go:131 +0x6e
github.com/gocraft/web.middlewareStack.func1(0x7fc3e9902ab8, 0xc820015680, 0xc8200156a0)
    /home/tyk/go/src/github.com/gocraft/web/router_serve.go:122 +0x1a5
github.com/gocraft/web.StaticMiddlewareFromDir.func1(0x7fc3e9902ab8, 0xc820015680, 0xc8200156a0, 0xc8204d9370)
    /home/tyk/go/src/github.com/gocraft/web/static_middleware.go:23 +0x66e
github.com/gocraft/web.(*middlewareHandler).invoke(0xc8203451d0, 0xc2b200, 0xc82021d2e8, 0x16, 0x7fc3e9902ab8, 0xc820015680, 0xc8200156a0, 0xc8204d9370)
    /home/tyk/go/src/github.com/gocraft/web/router_serve.go:131 +0x6e
github.com/gocraft/web.middlewareStack.func1(0x7fc3e9902ab8, 0xc820015680, 0xc8200156a0)
    /home/tyk/go/src/github.com/gocraft/web/router_serve.go:122 +0x1a5
github.com/gocraft/web.(*Router).ServeHTTP(0xc82025a840, 0x7fc3e9902a58, 0xc8202336c0, 0xc820441420)
    /home/tyk/go/src/github.com/gocraft/web/router_serve.go:48 +0x355
net/http.(*ServeMux).ServeHTTP(0xc820344e70, 0x7fc3e9902a58, 0xc8202336c0, 0xc820441420)
    /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820348f00, 0x7fc3e9902a58, 0xc8202336c0, 0xc820441420)
    /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820086700)
    /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2137 +0x44e

```

**Comment by lonelycode** [comment]
How did you create the developer? Also, did you have a fully functioning portal in place?

**Comment by byrnedo** [comment]
I just went via the gui.

Filled out email/pass and then create.

Yeah, I can visit my portal and all, it is the same installation
experiencing
https://community.tyk.io/t/developers-api-key-not-honoring-associated-policies/657/20
though.

**Comment by lonelycode** [comment]
There's something really wrong with the user that is generating objects in the GUI, and it's wrecking havoc on your install.

**Comment by byrnedo** [comment]
Anything in particular I should look at in mongo to check?
From tyk_analytics_users collection ( the access key is changed )
```
{ "_id" : ObjectId("56f3e529ca6272c7bb342554"), "firstname" : "Donal", "lastname" : "Byrne", "emailaddress" : "donal@xxx", "password" : "$2a$1blahablahblah", "orgid" : "56f3e529fb9231000a000001", "active" : true, "accesskey" : "bd5d58514944a5434eb20be4d324011a" }
```

**Comment by mvdan** [comment]
@byrnedo this panic affects the analytics/dashboard Go code, not the open source gateway. As such, I've moved the issue to our internal repo.

I'm closing this for now, but we'll post a comment once it is fixed.
