### ISSUE TITLE
Tcp proxy crashes gateway

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2511]
**Branch/Environment/Version**
- Branch/Version: Release-1.9
- Environment: All

**Describe the bug**
When we create tcp proxy api def it kills gateway on reload

**Reproduction steps**

1. Add tcp proxy api over dashboard 

**Actual behavior**
Gateway will crash 

Here is def:

```
{
  "api_model": {},
  "api_definition": {
    "api_id": "c68b6204b00a4c0a6cfd8100dd51e82f",
    "jwt_issued_at_validation_skew": 0,
    "upstream_certificates": {},
    "use_keyless": true,
    "enable_coprocess_auth": false,
    "base_identity_provided_by": "",
    "custom_middleware": {
      "pre": [],
      "post": [],
      "post_key_auth": [],
      "auth_check": {
        "name": "",
        "path": "",
        "require_session": false,
        "raw_body_only": false
      },
      "response": [],
      "driver": "",
      "id_extractor": {
        "extract_from": "",
        "extract_with": "",
        "extractor_config": {}
      }
    },
    "disable_quota": false,
    "custom_middleware_bundle": "",
    "cache_options": {
      "cache_timeout": 60,
      "enable_cache": true,
      "cache_all_safe_requests": false,
      "cache_response_codes": [],
      "enable_upstream_cache_control": false,
      "cache_control_ttl_header": ""
    },
    "enable_ip_blacklisting": false,
    "tag_headers": [],
    "jwt_scope_to_policy_mapping": {},
    "pinned_public_keys": {},
    "expire_analytics_after": 0,
    "domain": "",
    "openid_options": {
      "providers": [],
      "segregate_by_client": false
    },
    "jwt_policy_field_name": "",
    "enable_proxy_protocol": false,
    "jwt_default_policies": [],
    "active": true,
    "jwt_expires_at_validation_skew": 0,
    "config_data": {},
    "notifications": {
      "shared_secret": "",
      "oauth_on_keychange_url": ""
    },
    "jwt_client_base_field": "",
    "auth": {
      "use_param": false,
      "param_name": "",
      "use_cookie": false,
      "cookie_name": "",
      "auth_header_name": "",
      "use_certificate": false,
      "validate_signature": false,
      "signature": {
        "algorithm": "",
        "header": "",
        "secret": "",
        "allowed_clock_skew": 0,
        "error_code": 0,
        "error_message": ""
      }
    },
    "check_host_against_uptime_tests": false,
    "auth_provider": {
      "name": "",
      "storage_engine": "",
      "meta": {}
    },
    "blacklisted_ips": [],
    "hmac_allowed_clock_skew": -1,
    "dont_set_quota_on_create": false,
    "uptime_tests": {
      "check_list": [],
      "config": {
        "expire_utime_after": 0,
        "service_discovery": {
          "use_discovery_service": false,
          "query_endpoint": "",
          "use_nested_query": false,
          "parent_data_path": "",
          "data_path": "",
          "cache_timeout": 60
        },
        "recheck_wait": 0
      }
    },
    "enable_jwt": false,
    "do_not_track": false,
    "name": "raw",
    "slug": "raw",
    "oauth_meta": {
      "allowed_access_types": [],
      "allowed_authorize_types": [],
      "auth_login_redirect": ""
    },
    "CORS": {
      "enable": false,
      "max_age": 24,
      "allow_credentials": false,
      "exposed_headers": [],
      "allowed_headers": [],
      "options_passthrough": false,
      "debug": false,
      "allowed_origins": [],
      "allowed_methods": []
    },
    "event_handlers": {
      "events": {}
    },
    "proxy": {
      "target_url": "http://httpbin.org/",
      "service_discovery": {
        "endpoint_returns_list": false,
        "cache_timeout": 0,
        "parent_data_path": "",
        "query_endpoint": "",
        "use_discovery_service": false,
        "_sd_show_port_path": false,
        "target_path": "",
        "use_target_list": false,
        "use_nested_query": false,
        "data_path": "",
        "port_data_path": ""
      },
      "check_host_against_uptime_tests": false,
      "transport": {
        "ssl_insecure_skip_verify": false,
        "ssl_ciphers": [],
        "ssl_min_version": 0,
        "proxy_url": ""
      },
      "target_list": [],
      "preserve_host_header": false,
      "strip_listen_path": true,
      "enable_load_balancing": false,
      "listen_path": "/raw/",
      "disable_strip_slash": false
    },
    "client_certificates": [],
    "use_basic_auth": false,
    "version_data": {
      "not_versioned": true,
      "default_version": "",
      "versions": {
        "Default": {
          "name": "Default",
          "expires": "",
          "paths": {
            "ignored": [],
            "white_list": [],
            "black_list": []
          },
          "use_extended_paths": true,
          "extended_paths": {
            "ignored": [],
            "white_list": [],
            "black_list": [],
            "transform": [],
            "transform_response": [],
            "transform_jq": [],
            "transform_jq_response": [],
            "transform_headers": [],
            "transform_response_headers": [],
            "hard_timeouts": [],
            "circuit_breakers": [],
            "url_rewrites": [],
            "virtual": [],
            "size_limits": [],
            "method_transforms": [],
            "track_endpoints": [],
            "do_not_track_endpoints": [],
            "validate_json": [],
            "internal": []
          },
          "global_headers": {},
          "global_headers_remove": [],
          "global_size_limit": 0,
          "override_target": ""
        }
      }
    },
    "jwt_scope_claim_name": "",
    "use_standard_auth": false,
    "session_lifetime": 0,
    "hmac_allowed_algorithms": [],
    "disable_rate_limit": false,
    "definition": {
      "location": "header",
      "key": "x-api-version",
      "strip_path": false
    },
    "use_oauth2": false,
    "jwt_source": "",
    "jwt_signing_method": "",
    "jwt_not_before_validation_skew": 0,
    "use_go_plugin_auth": false,
    "jwt_identity_base_field": "",
    "allowed_ips": [],
    "request_signing": {
      "is_enabled": false,
      "secret": "",
      "key_id": "",
      "algorithm": ""
    },
    "org_id": "5d7fcd609633d7ba7c5f3f50",
    "enable_ip_whitelisting": false,
    "global_rate_limit": {
      "rate": 0,
      "per": 0
    },
    "protocol": "tcp",
    "enable_context_vars": false,
    "tags": [],
    "basic_auth": {
      "disable_caching": false,
      "cache_ttl": 0,
      "extract_from_body": false,
      "body_user_regexp": "",
      "body_password_regexp": ""
    },
    "listen_port": 0,
    "session_provider": {
      "name": "",
      "storage_engine": "",
      "meta": {}
    },
    "strip_auth_data": false,
    "id": "5d7ff1da9633d7bc3d5246ae",
    "certificates": [],
    "enable_signature_checking": false,
    "use_openid": false,
    "internal": false,
    "jwt_skip_kid": false,
    "enable_batch_request_support": false,
    "response_processors": [],
    "use_mutual_tls_auth": false
  },
  "hook_references": [],
  "is_site": false,
  "sort_by": 0,
  "user_group_owners": [],
  "user_owners": []
}
```

**Expected behavior**
Gateway should not crash

**Logs (debug mode or log file):**
Here is console error:
```
[Sep 16 22:34:34]  INFO main: API bind on custom port:0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4897136]

goroutine 403 [running]:
github.com/TykTechnologies/tyk/tcp.(*Proxy).AddDomainHandler(0x0, 0x0, 0x0, 0xc000307be0, 0x13, 0x0)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/tcp/tcp.go:74 +0x26
github.com/TykTechnologies/tyk/gateway.(*proxyMux).addTCPService(0xc000bf43d8, 0xc000c0c000, 0x0)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:160 +0xd1
github.com/TykTechnologies/tyk/gateway.loadTCPService(0xc000c0c000, 0xc000bf43d8)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/api_loader.go:608 +0x3e
github.com/TykTechnologies/tyk/gateway.loadApps(0xc0009d0a28, 0x1, 0x1)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/api_loader.go:654 +0x471
github.com/TykTechnologies/tyk/gateway.loadGlobalApps()
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/api_loader.go:539 +0xe5
github.com/TykTechnologies/tyk/gateway.DoReload()
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/server.go:668 +0x199
github.com/TykTechnologies/tyk/gateway.reloadLoop(0xc0001c3140)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/server.go:686 +0x9a
created by github.com/TykTechnologies/tyk/gateway.start
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/server.go:1154 +0x3c8
```

**Comment by jay-deshmukh** [comment]
@ilijabojanovic , I think this is happening because you are setting port (`listen_port`) `0` like
https://github.com/TykTechnologies/tyk/issues/2480 .

**Comment by buger** [comment]
@jay-deshmukh UI also should add validation, and "require" no zero port for TCP APIs.
