### ISSUE TITLE
TCP Proxy: TCP proxy api causes panics for get token

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2589]
**Branch/Environment/Version**
- Branch/Version: Release-1.9
- Environment: All

**Describe the bug**
When we create tcp api with custom port, gateway panics on get token

**Reproduction steps**
1. Create TCP api with custom port e.g 7000
2. Ok keys page create new token for some api
3. On keys page search that token

**Actual behavior**
Gateway panics:
```
2019/10/04 12:44:27 http: panic serving 127.0.0.1:53255: runtime error: invalid memory address or nil pointer dereference
goroutine 74211 [running]:
net/http.(*conn).serve.func1(0xc00115ba40)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x4bb3040, 0x59a4ed0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/TykTechnologies/tyk/gateway.(*DefaultSessionManager).SessionDetail(0xc001a31560, 0xc00011cfce, 0x78, 0x747942a8006e4900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/auth_manager.go:307 +0x65e
github.com/TykTechnologies/tyk/gateway.handleGetDetail(0xc00011cfce, 0x78, 0xc00011d04e, 0x20, 0xffffffffffffff00, 0x0, 0x0, 0x0)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/api.go:439 +0x21d
github.com/TykTechnologies/tyk/gateway.keyHandler(0x502fce0, 0xc001edc000, 0xc001abc900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/api.go:878 +0x5bc
net/http.HandlerFunc.ServeHTTP(0x4daf870, 0x502fce0, 0xc001edc000, 0xc001abc900)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001146c60, 0x502fce0, 0xc001edc000, 0xc001abc900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0xf1
github.com/TykTechnologies/tyk/gateway.InstrumentationMW.func1(0x502fce0, 0xc001edc000, 0xc001abc700)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/instrumentation_handlers.go:57 +0xa0
net/http.HandlerFunc.ServeHTTP(0xc001cc1ba0, 0x502fce0, 0xc001edc000, 0xc001abc700)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/TykTechnologies/tyk/gateway.controlAPICheckClientCertificate.func1(0x502fce0, 0xc001edc000, 0xc001abc700)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/server.go:383 +0x20a
net/http.HandlerFunc.ServeHTTP(0xc001cc1bc0, 0x502fce0, 0xc001edc000, 0xc001abc700)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/TykTechnologies/tyk/gateway.checkIsAPIOwner.func1(0x502fce0, 0xc001edc000, 0xc001abc700)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/server.go:471 +0x1c3
net/http.HandlerFunc.ServeHTTP(0xc001b766f0, 0x502fce0, 0xc001edc000, 0xc001abc700)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/TykTechnologies/tyk/gateway.stripSlashes.func1(0x502fce0, 0xc001edc000, 0xc001abc700)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/server.go:369 +0x130
net/http.HandlerFunc.ServeHTTP(0xc001cc1be0, 0x502fce0, 0xc001edc000, 0xc001abc700)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.StripPrefix.func1(0x502fce0, 0xc001edc000, 0xc001abc600)
	/usr/local/go/src/net/http/server.go:2003 +0x18b
net/http.HandlerFunc.ServeHTTP(0xc001b76720, 0x502fce0, 0xc001edc000, 0xc001abc600)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001146ae0, 0x502fce0, 0xc001edc000, 0xc001abc600)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0xf1
github.com/TykTechnologies/tyk/gateway.(*handleWrapper).ServeHTTP(0xc000208230, 0x502fce0, 0xc001edc000, 0xc001abc400)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:41 +0x170
net/http.serverHandler.ServeHTTP(0xc000178410, 0x502fce0, 0xc001edc000, 0xc001abc400)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00115ba40, 0x5031060, 0xc000760fc0)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```
Dashboard:
```
[Oct  4 12:48:22] ERROR Get https://www.tyk-test.com:8181/tyk/keys/eyJvcmciOiI1ZDk0ODQ1Nzk2MzNkNzNkYTEyZTI0MGMiLCJpZCI6ImNjNDc0M2JjNGM5YTRhOTI4NGJjODJkM2JjZTBkYjI5IiwiaCI6Im11cm11cjY0In0=?api_id=0a1a1b23e90742544f9a0201ad6c659c&org_id=5d9484579633d73da12e240c: EOF
[Oct  4 12:48:22] ERROR Key detail request failed
```

**Expected behavior**
Gateway should not panics

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**
Api def:
```
{
    "id": "5d9723349633d70569e51a0d",
    "name": "tcp",
    "slug": "tcp",
    "listen_port": 7000,
    "protocol": "tcp",
    "enable_proxy_protocol": false,
    "api_id": "0a1a1b23e90742544f9a0201ad6c659c",
    "org_id": "5d9484579633d73da12e240c",
    "use_keyless": true,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": "",
        "use_certificate": false,
        "validate_signature": false,
        "signature": {
            "algorithm": "",
            "header": "",
            "secret": "",
            "allowed_clock_skew": 0,
            "error_code": 0,
            "error_message": ""
        }
    },
    "use_basic_auth": false,
    "basic_auth": {
        "disable_caching": false,
        "cache_ttl": 0,
        "extract_from_body": false,
        "body_user_regexp": "",
        "body_password_regexp": ""
    },
    "use_mutual_tls_auth": false,
    "client_certificates": [],
    "upstream_certificates": {},
    "pinned_public_keys": {},
    "enable_jwt": false,
    "use_standard_auth": false,
    "use_go_plugin_auth": false,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "jwt_default_policies": [],
    "jwt_issued_at_validation_skew": 0,
    "jwt_expires_at_validation_skew": 0,
    "jwt_not_before_validation_skew": 0,
    "jwt_skip_kid": false,
    "jwt_scope_to_policy_mapping": {},
    "jwt_scope_claim_name": "",
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "hmac_allowed_algorithms": [],
    "request_signing": {
        "is_enabled": false,
        "secret": "",
        "key_id": "",
        "algorithm": ""
    },
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version",
        "strip_path": false
    },
    "version_data": {
        "not_versioned": true,
        "default_version": "",
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {},
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/tcp/",
        "target_url": "http://httpbin.org/",
        "disable_strip_slash": false,
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "port_data_path": "",
            "target_path": "",
            "use_target_list": false,
            "cache_timeout": 0,
            "endpoint_returns_list": false
        },
        "transport": {
            "ssl_insecure_skip_verify": false,
            "ssl_ciphers": [],
            "ssl_min_version": 0,
            "proxy_url": ""
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false,
            "raw_body_only": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false,
        "cache_control_ttl_header": ""
    },
    "session_lifetime": 0,
    "active": true,
    "internal": false,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "enable_ip_blacklisting": false,
    "blacklisted_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "certificates": [],
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false,
    "config_data": {},
    "tag_headers": [],
    "global_rate_limit": {
        "rate": 0,
        "per": 0
    },
    "strip_auth_data": false
}
```

**Comment by buger** [comment]
It was happening if TCP api was used for smth Redis related. Most likely in your installation it was the first API in list, and when you accessed keys, it was used as api_id param. On my installation I was not able to replicate exactly this issue, however just creating a key with TCP proxy in access rules, caused similar panic.
