### ISSUE TITLE
ObjectPostProcess errors

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#2837]
**Branch/Environment/Version**
- Branch/Version: All
- Environment: All

**Describe the bug**
We've found that under some scenarios, `ObjectPostProcess` fails due to errors related to URL parsing. It would be useful to handle errors when calling `url. ParseRequestURI` (see [here](https://github.com/TykTechnologies/tyk/blob/master/gateway/coprocess.go#L196)).

**Reproduction steps**

1. Create a Python bundle with the following code:
```python
from tyk.decorators import *
print("middleware.py is loaded")
@Hook
def myhook(request, session, spec):
  print("myhook called")
  request.object.url = ''
  return request, session
```
2. Deploy and attach the bundle to an API.
3. Call the API, `runtime error: invalid memory address or nil pointer dereference` will show up, caused by an error in `url. ParseRequestURI`, which returns a `nil` value.

**Potential fix/enhancement:** https://github.com/TykTechnologies/tyk/pull/2638

**Comment by ilijabojanovic** [comment]
On release-2.9 e784fa5530e189f9872bb91d2a79f0aff9e937ae

This issue is still visible.

Please see log:

```
INFO coprocess: Reloading middlewares
myhook called
None
[Jan 27 14:02:46] ERROR Failed to post-process request object api_id=02d12e63e25d46d854cf20d8de6c0c3b api_name=test2 error=parse : empty url mw=CoProcessMiddleware org_id=5dcaa92a9633d70d2397e557 origin=127.0.0.1 path=/test2/anything
2020/01/27 14:02:46 http: panic serving 127.0.0.1:64368: runtime error: invalid memory address or nil pointer dereference
goroutine 533 [running]:
net/http.(*conn).serve.func1(0xc0000c6aa0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x4c6b460, 0x5a79d50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/TykTechnologies/tyk/gateway.(*ErrorHandler).HandleError(0xc000795e48, 0x50e48a0, 0xc000406700, 0xc0001da200, 0x4e00127, 0x10, 0x1f4, 0x50cc801)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/handler_error.go:111 +0x104a
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x50e48a0, 0xc000406700, 0xc0001da200)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/middleware.go:137 +0x639
net/http.HandlerFunc.ServeHTTP(0xc001b9ce00, 0x50e48a0, 0xc000406700, 0xc0001da200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0016665a0, 0x50e48a0, 0xc000406700, 0xc0001da200)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0x104
github.com/TykTechnologies/tyk/gateway.(*handleWrapper).ServeHTTP(0xc000496008, 0x50e48a0, 0xc000406700, 0xc001378100)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:41 +0x1b4
net/http.serverHandler.ServeHTTP(0xc0000cee00, 0x50e48a0, 0xc000406700, 0xc001378100)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000c6aa0, 0x50ea1e0, 0xc0017be080)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

In attach is testing bundle:
[bundle-url.zip](https://github.com/TykTechnologies/tyk/files/4117221/bundle-url.zip)

**Comment by matiasinsaurralde** [comment]
@ilijabojanovic I'm not getting the runtime error:
```
[Jan 29 09:17:47]  INFO Checking security policy: Open api_id=3 api_name=Tyk Test API org_id=default
[Jan 29 09:17:47]  INFO gateway: API Loaded api_id=3 api_name=Tyk Test API org_id=default server_name=-- user_id=-- user_ip=--
[Jan 29 09:17:47]  INFO host-check-mgr: Loading uptime tests...
[Jan 29 09:17:47]  INFO main: Initialised API Definitions
[Jan 29 09:17:47]  INFO main: API reload complete
myhook called
[Jan 29 09:17:52] ERROR Failed to post-process request object api_id=3 api_name=Tyk Test API error=parse : empty url mw=CoProcessMiddleware org_id=default origin=127.0.0.1 path=/quickstart/headers
```
And the Curl response looks like this (expected):
```
% curl http://localhost:8080/quickstart/headers
{
    "error": "Middleware error"
}% 
```

I'm assuming that in your test scenario, analytics are enabled so the error is a different one: `ErrorHandler` isn't able to access the URL (because it's `nil`), it happens in `handler_error.go`:

```go
        ip := request.RealIP(r)
        if e.Spec.GlobalConfig.StoreAnalytics(ip) {
                t := time.Now()

                addVersionHeader(w, r, e.Spec.GlobalConfig)

                version := e.Spec.getVersionFromRequest(r)
                if version == "" {
                        version = "Non Versioned"
                }

                if e.Spec.Proxy.StripListenPath {
                        r.URL.Path = e.Spec.StripListenPath(r, r.URL.Path)
                }

                // This is an odd bugfix, will need further testing
                r.URL.Path = "/" + r.URL.Path
                if strings.HasPrefix(r.URL.Path, "//") {
                        r.URL.Path = strings.TrimPrefix(r.URL.Path, "/")
                }
```

**Comment by matiasinsaurralde** [comment]
I was able to reproduce the above issue, it happens when `do_not_track` is set to `false` and analytics are enabled. I will extend the PR to cover this case.

**Comment by matiasinsaurralde** [comment]
Added an additional commit to cover analytics issue: https://github.com/TykTechnologies/tyk/pull/2859
