### ISSUE TITLE
Delete oauth client generates panic errors 

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2940]
**Branch/Environment/Version**
- Branch/Version: Release-2.9
- Environment: All

**Describe the bug**
When we try to delete oauth client gateway panics. This is visible only on oauth api's which has mixed type policy.

**Reproduction steps**

1. Create oauth api
2. Create standard token api
3. Create policy and attach oauth and standard apis on that policy
4. Create ouath client
5. Delete that oauth client  

**Actual behavior**
When we delete auth client gateway panics:
```
[Mar 19 10:47:28]  INFO Getting client ID:a5b450ec6f0340f2a252e861a161a7ce
[Mar 19 10:47:28]  INFO Getting client tokens sorted list:oauth-client-tokens.a5b450ec6f0340f2a252e861a161a7ce
[Mar 19 10:47:28]  INFO Getting client tokens sorted list:oauth-client-tokens.a5b450ec6f0340f2a252e861a161a7ce
2020/03/19 10:47:58 http: panic serving 127.0.0.1:57968: runtime error: invalid memory address or nil pointer dereference
goroutine 381 [running]:
net/http.(*conn).serve.func1(0xc000cde1e0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x4c738e0, 0x5a88cd0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/TykTechnologies/tyk/gateway.handleDeleteOAuthClient(0xc0008042db, 0x20, 0xc0008042ba, 0x20, 0xc0014ce098, 0x50b31b8, 0x4dcbda0)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/api.go:1862 +0xb2
github.com/TykTechnologies/tyk/gateway.oAuthClientHandler(0x50f17c0, 0xc000aee000, 0xc000aac600)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/api.go:1745 +0x1ba
net/http.HandlerFunc.ServeHTTP(0x4e9cd70, 0x50f17c0, 0xc000aee000, 0xc000aac600)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001b20060, 0x50f17c0, 0xc000aee000, 0xc000aac600)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0x104
github.com/TykTechnologies/tyk/gateway.InstrumentationMW.func1(0x50f17c0, 0xc000aee000, 0xc000aac400)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/instrumentation_handlers.go:57 +0x111
net/http.HandlerFunc.ServeHTTP(0xc001926800, 0x50f17c0, 0xc000aee000, 0xc000aac400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/TykTechnologies/tyk/gateway.controlAPICheckClientCertificate.func1(0x50f17c0, 0xc000aee000, 0xc000aac400)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/server.go:411 +0x1fe
net/http.HandlerFunc.ServeHTTP(0xc001926820, 0x50f17c0, 0xc000aee000, 0xc000aac400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/TykTechnologies/tyk/gateway.checkIsAPIOwner.func1(0x50f17c0, 0xc000aee000, 0xc000aac400)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/server.go:505 +0x1c3
net/http.HandlerFunc.ServeHTTP(0xc001b1ed50, 0x50f17c0, 0xc000aee000, 0xc000aac400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/TykTechnologies/tyk/gateway.stripSlashes.func1(0x50f17c0, 0xc000aee000, 0xc000aac400)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/server.go:397 +0x130
net/http.HandlerFunc.ServeHTTP(0xc001926840, 0x50f17c0, 0xc000aee000, 0xc000aac400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.StripPrefix.func1(0x50f17c0, 0xc000aee000, 0xc000aac300)
	/usr/local/go/src/net/http/server.go:2046 +0x18a
net/http.HandlerFunc.ServeHTTP(0xc001b1ed80, 0x50f17c0, 0xc000aee000, 0xc000aac300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001b20000, 0x50f17c0, 0xc000aee000, 0xc000aac300)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0x104
github.com/TykTechnologies/tyk/gateway.(*handleWrapper).ServeHTTP(0xc0000c4108, 0x50f17c0, 0xc000aee000, 0xc000aac100)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:41 +0x1b4
net/http.serverHandler.ServeHTTP(0xc0003d6000, 0x50f17c0, 0xc000aee000, 0xc000aac100)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000cde1e0, 0x50f7180, 0xc001e8c640)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

Dashboard logs:
```
[Mar 19 10:47:58] ERROR Failed to delete key
[Mar 19 10:47:58] ERROR Delete https://www.tyk-test.com:8181/tyk/oauth/clients/634919c924ff4767715a25dc171b348b/a5b450ec6f0340f2a252e861a161a7ce: EOF
[Mar 19 10:47:58] ERROR App request failed
[Mar 19 10:47:58] ERROR Couldn't delete OAuth client client_id=a5b450ec6f0340f2a252e861a161a7ce org_id=5dcaa92a9633d70d2397e557 policy_id=5dd25f079633d708123d6341
```
**Expected behavior**
We should not have any errors

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by ilijabojanovic** [comment]
Verified
