### ISSUE TITLE
[TT-1956] Quota counter does not work on tokens with limits per api

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2970]
**Branch/Environment/Version**
- Branch/Version: Stable/Release-2.9
- Environment: All

**Describe the bug**

**Reproduction steps**
1. Create api1
2. Create api2
3. Create policy and add api1 and api2
4. On policy enable Limits per api
5. Add quota limit on api1 e.g 40 in 1 hour
6. Add quota limit on api2 e.g 200 in 1 hour
7. Generate token with attached policy
8. Send some traffic to api1

**Actual behavior**
Quota is calculated only on first hit, after that quota remaining the same.
**NOTE:** if we send big traffic and token reach rate limits, that will crash gateway too.

**Expected behavior**
Remaining quota should be always calculated and displayed in response header

**Screenshots/Video**
![quota](https://user-images.githubusercontent.com/8557292/77761201-f7230100-7037-11ea-9c90-11c89c9dbb50.gif)

**Logs (debug mode or log file):**
```
goroutine 2794 [runnable]:
vendor/golang.org/x/crypto/curve25519.ladderstep(0xc0034916a8)
	/usr/local/go/src/vendor/golang.org/x/crypto/curve25519/ladderstep_amd64.s:13 +0x178d
vendor/golang.org/x/crypto/curve25519.mladder(0xc0034917e0, 0xc0034917b8, 0xc003491798)
	/usr/local/go/src/vendor/golang.org/x/crypto/curve25519/mont25519_amd64.go:52 +0x137
vendor/golang.org/x/crypto/curve25519.scalarMult(0xc003ee1c40, 0xc003c75d80, 0xc003491850)
	/usr/local/go/src/vendor/golang.org/x/crypto/curve25519/mont25519_amd64.go:71 +0xe3
vendor/golang.org/x/crypto/curve25519.ScalarMult(...)
	/usr/local/go/src/vendor/golang.org/x/crypto/curve25519/doc.go:15
crypto/tls.(*x25519Parameters).SharedKey(0xc003c75d80, 0xc0037579a7, 0x20, 0x39, 0xc003c75d80, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/key_schedule.go:200 +0xb8
crypto/tls.(*serverHandshakeStateTLS13).processClientHello(0xc003491aa8, 0x400ecb6, 0x0)
	/usr/local/go/src/crypto/tls/handshake_server_tls13.go:216 +0x665
crypto/tls.(*serverHandshakeStateTLS13).handshake(0xc003491aa8, 0xc003d4c800, 0x0)
	/usr/local/go/src/crypto/tls/handshake_server_tls13.go:46 +0x37
crypto/tls.(*Conn).serverHandshake(0xc005bb6a80, 0x4d6ca4af, 0xc004cbabf8)
	/usr/local/go/src/crypto/tls/handshake_server.go:53 +0xe7
crypto/tls.(*Conn).Handshake(0xc005bb6a80, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1364 +0x23a
net/http.(*conn).serve(0xc00286bc20, 0x50eca80, 0xc00023b680)
	/usr/local/go/src/net/http/server.go:1783 +0x19d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e

goroutine 2689 [sleep]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:310
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:105 +0x157
github.com/TykTechnologies/tyk/vendor/github.com/paulbellamy/ratecounter.(*RateCounter).scheduleDecrement(0xc0002d2060, 0x1)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/paulbellamy/ratecounter/ratecounter.go:29 +0x2f
created by github.com/TykTechnologies/tyk/vendor/github.com/paulbellamy/ratecounter.(*RateCounter).Incr
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/paulbellamy/ratecounter/ratecounter.go:25 +0x51

goroutine 2704 [runnable]:
github.com/TykTechnologies/tyk/vendor/github.com/paulbellamy/ratecounter.(*RateCounter).scheduleDecrement(0xc0002d2060, 0x1)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/paulbellamy/ratecounter/ratecounter.go:28
created by github.com/TykTechnologies/tyk/vendor/github.com/paulbellamy/ratecounter.(*RateCounter).Incr
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/paulbellamy/ratecounter/ratecounter.go:25 +0x51
```

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by andyo-tyk** [comment]
This feature enhancement was raised by Tyk and is tracked internally.
