### ISSUE TITLE
failed to create api key with specific api_id

### ISSUE THREAD

**Issue by tonywangcn** [TykTechnologies/tyk#2982]
Docker image 
tykio/tyk-gateway:latest
DIGEST:sha256:e765389063a02ff46809bfe3a7412b7309534be15964f68ce2565d380af494e9

**Describe the bug**
Failed to create a key with this api_id "ed6ec2c2073007898a3ca71bea61ab7c", it works well with any longer or shorter than this one.

**Reproduction steps**

1. post to "/tyk/keys/create"

post body 

```
{
    "allowance": 10,
    "rate": 2,
    "per": 10,
    "expires": -1,
    "quota_max": 10,
    "quota_renewal_rate": 3600,
    "access_rights": {
      "ed6ec2c2073007898a3ca71bea61ab7c": {
        "api_id": "ed6ec2c2073007898a3ca71bea61ab7c"
      }
    }
  }
```

**Actual behavior**

Could not get any response

**Expected behavior**

200 response with ok status

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**

time="Apr 01 11:38:45" level=info msg="Reset quota for key." inbound-key="****ef35" key=quota-af9ea981 prefix=auth-mgr
2020/04/01 11:38:45 http: panic serving 172.20.0.1:56554: runtime error: invalid memory address or nil pointer dereference
goroutine 700 [running]:
net/http.(*conn).serve.func1(0xc00032e500)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x1623060, 0x23c6060)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/TykTechnologies/tyk/gateway.(*DefaultSessionManager).ResetQuota(0xc000aa1110, 0xc00048a760, 0x20, 0xc0003a68c0, 0xc0003a6800)
	/go/src/github.com/TykTechnologies/tyk/gateway/auth_manager.go:200 +0x350
github.com/TykTechnologies/tyk/gateway.createKeyHandler(0x1a9e1e0, 0xc0005e28c0, 0xc00076e700)
	/go/src/github.com/TykTechnologies/tyk/gateway/api.go:1265 +0x1f4d
net/http.HandlerFunc.ServeHTTP(0x18372e8, 0x1a9e1e0, 0xc0005e28c0, 0xc00076e700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00074cd20, 0x1a9e1e0, 0xc0005e28c0, 0xc00076e700)
	/go/src/vendor/github.com/gorilla/mux/mux.go:150 +0x105
github.com/TykTechnologies/tyk/gateway.InstrumentationMW.func1(0x1a9e1e0, 0xc0005e28c0, 0xc00076e500)
	/go/src/github.com/TykTechnologies/tyk/gateway/instrumentation_handlers.go:57 +0x11e
net/http.HandlerFunc.ServeHTTP(0xc000b10620, 0x1a9e1e0, 0xc0005e28c0, 0xc00076e500)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.controlAPICheckClientCertificate.func1(0x1a9e1e0, 0xc0005e28c0, 0xc00076e500)
	/go/src/github.com/TykTechnologies/tyk/gateway/server.go:386 +0x202
net/http.HandlerFunc.ServeHTTP(0xc000b10640, 0x1a9e1e0, 0xc0005e28c0, 0xc00076e500)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.checkIsAPIOwner.func1(0x1a9e1e0, 0xc0005e28c0, 0xc00076e500)
	/go/src/github.com/TykTechnologies/tyk/gateway/server.go:475 +0x1cc
net/http.HandlerFunc.ServeHTTP(0xc000aa1740, 0x1a9e1e0, 0xc0005e28c0, 0xc00076e500)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.stripSlashes.func1(0x1a9e1e0, 0xc0005e28c0, 0xc00076e500)
	/go/src/github.com/TykTechnologies/tyk/gateway/server.go:372 +0x130
net/http.HandlerFunc.ServeHTTP(0xc000b10680, 0x1a9e1e0, 0xc0005e28c0, 0xc00076e500)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.StripPrefix.func1(0x1a9e1e0, 0xc0005e28c0, 0xc00076e400)
	/usr/local/go/src/net/http/server.go:2034 +0x18d
net/http.HandlerFunc.ServeHTTP(0xc000aa17d0, 0x1a9e1e0, 0xc0005e28c0, 0xc00076e400)
	/usr/local/go/src/net/http/server.go:1995 +0x44
vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00074ccc0, 0x1a9e1e0, 0xc0005e28c0, 0xc00076e400)
	/go/src/vendor/github.com/gorilla/mux/mux.go:150 +0x105
github.com/TykTechnologies/tyk/gateway.(*handleWrapper).ServeHTTP(0xc0000ba538, 0x1a9e1e0, 0xc0005e28c0, 0xc00076e100)
	/go/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:41 +0x16f
net/http.serverHandler.ServeHTTP(0xc00064f790, 0x1a9e1e0, 0xc0005e28c0, 0xc00076e100)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00032e500, 0x1aa2ba0, 0xc000b54bc0)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

**Configuration (tyk config file):**
The same one, https://github.com/TykTechnologies/tyk-pro-docker-demo/blob/master/confs/tyk.conf

**Additional context**

**Comment by christtyk** [comment]
Thanks for the report, we'll check it out!
