### ISSUE TITLE
Can't create Gelf logger 

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#309]
When my config file add as following:

```
"use_sentry": true,
"use_syslog": true,
"use_graylog": true,
"use_logstash": true,
```

```
[Oct 28 10:43:12]  INFO Connection dropped, connecting..  |----> pos=tyk/redis_cluster_handler.go|(_RedisClusterStorageManager).GetKey:118
[Oct 28 10:43:12]  INFO host-check-mgr: Starting Poller  |----> pos=tyk/host_checker_manager.go|(_HostCheckerManager).CheckActivePollerLoop:106
INFO[0000] Can't create Gelf logger                       |----> pos=tyk/vendor/github.com/Sirupsen/logrus/exported.go|com/tyk/vendor/github.com/Sirupsen/logrus.WithField:62 err=dial udp: missing address
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7bb05b]

goroutine 1 [running]:
panic(0xc7f740, 0xc420010100)
    /mnt/shared/go/src/runtime/panic.go:500 +0x1a1
derbysoft.com/tyk/vendor/github.com/lonelycode/logrus-graylog-hook.(_Writer).WriteMessage(0x0, 0xc42014e780, 0x0, 0x20)
    /mnt/shared/go-T/src/derbysoft.com/tyk/vendor/github.com/lonelycode/logrus-graylog-hook/gelf_writer.go:179 +0xbb
derbysoft.com/tyk/vendor/github.com/lonelycode/logrus-graylog-hook.(_GraylogHook).sendEntry(0xc4202d02d0, 0xc42044a280, 0x122d748, 0x33, 0x5e0)
    /mnt/shared/go-T/src/derbysoft.com/tyk/vendor/github.com/lonelycode/logrus-graylog-hook/graylog_hook.go:179 +0x699
derbysoft.com/tyk/vendor/github.com/lonelycode/logrus-graylog-hook.(_GraylogHook).Fire(0xc4202d02d0, 0xc42044a100, 0x0, 0x0)
    /mnt/shared/go-T/src/derbysoft.com/tyk/vendor/github.com/lonelycode/logrus-graylog-hook/graylog_hook.go:91 +0x29c
derbysoft.com/tyk/vendor/github.com/Sirupsen/logrus.LevelHooks.Fire(0xc42017d680, 0xc4180f3604, 0xc42044a100, 0xc4200cf6b0, 0x31)
    /mnt/shared/go-T/src/derbysoft.com/tyk/vendor/github.com/Sirupsen/logrus/hooks.go:28 +0x8b
derbysoft.com/tyk/vendor/github.com/Sirupsen/logrus.Entry.log(0xc4201cb140, 0xc4201586f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc39f04, 0xc42044a0c0, ...)
    /mnt/shared/go-T/src/derbysoft.com/tyk/vendor/github.com/Sirupsen/logrus/entry.go:90 +0x10d
derbysoft.com/tyk/vendor/github.com/Sirupsen/logrus.(_Entry).Info(0xc42044a000, 0xc42017bc30, 0x2, 0x2)
    /mnt/shared/go-T/src/derbysoft.com/tyk/vendor/github.com/Sirupsen/logrus/entry.go:131 +0x9a
main.initialiseSystem(0xc4203c6390)
    /mnt/shared/go-T/src/derbysoft.com/tyk/main.go:1504 +0xc70
main.main()
    /mnt/shared/go-T/src/derbysoft.com/tyk/main.go:1630 +0x112
```

**Comment by mvdan** [comment]
@penhauer-xiao apologies for the late reply - does this still happen with 2.3.x? If so, could you please post a new crash log?
