### ISSUE TITLE
Send a proper error when API doesn't exist

### ISSUE THREAD

**Issue by mNantern** [TykTechnologies/tyk#313]
When we try to create a new client on an api that doesn't exist, Tyk crashes with an invalid memory address:

```
time="Oct 28 14:01:21" level=error msg="Failed to create OAuth client" apiID=toto err="API doesn't exist" status=fail 
2016/10/28 14:01:21 http: panic serving [::1]:36016: runtime error: invalid memory address or nil pointer dereference
goroutine 2861846 [running]:
net/http.(*conn).serve.func1(0xc82f56c180)
    /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xd25820, 0xc82000e0a0)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
main.createOauthClient(0x7f77d4255510, 0xc82ee6c410, 0xc82f766380)
    /home/tyk/go/src/github.com/lonelycode/tyk/api.go:1480 +0xfca
main.CheckIsAPIOwner.func1(0x7f77d4255510, 0xc82ee6c410, 0xc82f766380)
    /home/tyk/go/src/github.com/lonelycode/tyk/middleware_api_security_handler.go:24 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc8271b03e0, 0x7f77d4255510, 0xc82ee6c410, 0xc82f766380)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc828e99860, 0x7f77d4255510, 0xc82ee6c410, 0xc82f766380)
    /home/tyk/go/src/github.com/gorilla/mux/mux.go:98 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc82c8175f0, 0x7f77d4255510, 0xc82ee6c410, 0xc82f766380)
    /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc8256d8600, 0x7f77d4255510, 0xc82ee6c410, 0xc82f766380)
    /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82f56c180)
    /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2137 +0x44e
```

```
curl -v -X POST -H "Content-Type: application/json" -H "x-tyk-authorization: xxxxxxx" -d '{ "api_id": "toto", "redirect_uri": "http://localhost:7000" }' http://localhost:8082/tyk/oauth/clients/create
* About to connect() to localhost port 8082 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8082 (#0)
> POST /tyk/oauth/clients/create HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8082
> Accept: */*
> Content-Type: application/json
> x-tyk-authorization: 352d20ee67be67f6341b4c0605b044b8
> Content-Length: 61
> 
* upload completely sent off: 61 out of 61 bytes
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

Tyk 2.2

**Comment by lonelycode** [comment]
This Ian fixed in v2.3

**Comment by kohrVid** [comment]
Hi,

Do you still get this error when you create clients without a valid API? If so, could you please confirm as to whether you're using the latest version of the Tyk Gateway (v2.3)? If this is no longer a problem, would it be all right if we closed this issue?

Kind regards,
Jess @ Tyk

**Comment by mvdan** [comment]
@mNantern I'm closing this issue now - if you're still having the same problem or would like any more help, feel free to reopen with more information.

Thanks.
