### ISSUE TITLE
Concurrent map writes

### ISSUE THREAD

**Issue by tetratorus** [TykTechnologies/tyk#3227]
**Branch/Environment/Version**
2.9
- Environment: On-prem

**Describe the bug**
Gateway panic when having high number of requests due to concurrent map writes

**Reproduction steps**
Add org rate limit, load test gateway

**Actual behavior**
Gateway panics with concurrent map writes
session_manager.go
https://github.com/TykTechnologies/tyk/blob/a10b1d2497bd94d935e753e932e8d19056e44b82/gateway/session_manager.go#L327,
access to the cached version of the user session object references the same pointer to the AccessRights map, which, upon concurrent map writes from goroutines, panics the entire gateway

**Expected behavior**
should not panic

**Comment by buger** [comment]
any chance you can post a panic, showing the issue?

**Comment by goughy000** [comment]
From latest Tyk docker image
```
time="Aug 13 10:52:47" level=info msg="Tyk API Gateway v2.9.4.3" prefix=main
```

```
fatal error: concurrent map writes

goroutine 1097 [running]:
runtime.throw(0x17b889b, 0x15)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000913b78 sp=0xc000913b48 pc=0x9b6b52
runtime.mapassign_faststr(0x160be40, 0xc0002b3470, 0xc0004789a0, 0xb, 0xc000183888)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x42a fp=0xc000913be0 sp=0xc000913b78 pc=0x99c22a
github.com/TykTechnologies/tyk/gateway.BaseMiddleware.ApplyPolicies(0xc00012a400, 0x1ab2e60, 0xc000122380, 0xc000294620, 0xc0009153e0, 0x1, 0x0)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:470 +0x1010 fp=0xc000914bd8 sp=0xc000913be0 pc=0x1415390
github.com/TykTechnologies/tyk/gateway.BaseMiddleware.CheckSessionAndIdentityForValidKey(0xc00012a400, 0x1ab2e60, 0xc000122380, 0xc000294620, 0xc000915b70, 0xc00062ad00, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:573 +0x118a fp=0xc000915930 sp=0xc000914bd8 pc=0x1417e1a
github.com/TykTechnologies/tyk/gateway.(*AuthKey).ProcessRequest(0xc000454660, 0x1ab3f20, 0xc0003c68c0, 0xc00062ad00, 0x0, 0x0, 0x203000, 0x203000, 0x70)
	/go/src/github.com/TykTechnologies/tyk/gateway/mw_auth_key.go:87 +0x434 fp=0xc0009160c0 sp=0xc000915930 pc=0x141c204
github.com/TykTechnologies/tyk/gateway.TraceMiddleware.ProcessRequest(0x1ac92c0, 0xc000454660, 0x1ab3f20, 0xc0003c68c0, 0xc00062ad00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:66 +0x3fd fp=0xc000916260 sp=0xc0009160c0 pc=0x1412e2d
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1ab3f20, 0xc0003c68c0, 0xc00062ad00)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:130 +0x528 fp=0xc000917fe0 sp=0xc000916260 pc=0x1499388
net/http.HandlerFunc.ServeHTTP(0xc000079d00, 0x1ab3f20, 0xc0003c68c0, 0xc00062ad00)
	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc000918008 sp=0xc000917fe0 pc=0xd1dd64
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1ab3f20, 0xc0003c68c0, 0xc00062ad00)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18 fp=0xc000919d88 sp=0xc000918008 pc=0x1499d78
net/http.HandlerFunc.ServeHTTP(0xc000079d40, 0x1ab3f20, 0xc0003c68c0, 0xc00062ad00)
	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc000919db0 sp=0xc000919d88 pc=0xd1dd64
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1ab3f20, 0xc0003c68c0, 0xc00062ad00)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18 fp=0xc00091bb30 sp=0xc000919db0 pc=0x1499d78
net/http.HandlerFunc.ServeHTTP(0xc000079d80, 0x1ab3f20, 0xc0003c68c0, 0xc00062ad00)
	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc00091bb58 sp=0xc00091bb30 pc=0xd1dd64
vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00007db00, 0x1ab3f20, 0xc0003c68c0, 0xc00062ad00)
	/go/src/vendor/github.com/gorilla/mux/mux.go:150 +0x105 fp=0xc00091bc88 sp=0xc00091bb58 pc=0xee94a5
github.com/TykTechnologies/tyk/gateway.(*handleWrapper).ServeHTTP(0xc0000ae8a8, 0x1ab3f20, 0xc0003c68c0, 0xc00062ab00)
	/go/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:41 +0x16f fp=0xc00091bcf0 sp=0xc00091bc88 pc=0x145d14f
net/http.serverHandler.ServeHTTP(0xc00009ea90, 0x1ab3f20, 0xc0003c68c0, 0xc00062ab00)
	/usr/local/go/src/net/http/server.go:2774 +0xa8 fp=0xc00091bd20 sp=0xc00091bcf0 pc=0xd211e8
net/http.(*conn).serve(0xc0000f3400, 0x1ab8a60, 0xc0007e9d80)
	/usr/local/go/src/net/http/server.go:1878 +0x851 fp=0xc00091bfc8 sp=0xc00091bd20 pc=0xd1cd21
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00091bfd0 sp=0xc00091bfc8 pc=0x9e70f1
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

When copying Policy MetaData to Session MetaData
https://github.com/TykTechnologies/tyk/blob/v2.9.4.3/gateway/middleware.go#L470

**Comment by matiasinsaurralde** [comment]
Related to #3309 and #3308.

**Comment by letzya** [comment]
fix #3309

**Comment by letzya** [comment]
fix #3309

**Comment by tomshy** [comment]
am running tyk-gateway:v3.1.2 yet am still getting this gateway panic

**Comment by buger** [comment]
Thats very strange indeed! 

Can you ensure setting `optimisations_use_async_session_write` to false in your gateway config?

**Comment by tomshy** [comment]
I've tried tyk versions between 2.9.4 - 3.0.2 with your suggestion of setting `optimisations_use_async_session_write` to false but am getting same error. Am sending a high number of requests to a basic api(no middlewares) authenticated using hmac authentication with clockskew enabled. Am using partitioned policies with `partitions` object set as follows:

```
"quota": true,
"rate_limit": true,
"acl": true,
```

Backtrace is so long but here's a snippet of it. I hope it helps catch the bug.

```
tyk-gateway_1  | fatal error: concurrent map writes
tyk-gateway_1  | 
tyk-gateway_1  | goroutine 746914 [running]:
tyk-gateway_1  | runtime.throw(0x17b5f82, 0x15)
tyk-gateway_1  | 	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000ab64e0 sp=0xc000ab64b0 pc=0x9b5b92
tyk-gateway_1  | runtime.mapassign_faststr(0x16094e0, 0xc00469a0f0, 0xc0021d5b30, 0x3, 0xc00449d088)
tyk-gateway_1  | 	/usr/local/go/src/runtime/map_faststr.go:211 +0x42a fp=0xc000ab6548 sp=0xc000ab64e0 pc=0x99b26a
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.BaseMiddleware.ApplyPolicies(0xc001646400, 0x1aaa780, 0xc000129ab0, 0xc00096ecb0, 0xc000ab7ec8, 0x1, 0x0)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:467 +0xfb3 fp=0xc000ab7540 sp=0xc000ab6548 pc=0x1414533
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.BaseMiddleware.CheckSessionAndIdentityForValidKey(0xc001646400, 0x1aaa780, 0xc000129ab0, 0xc00096ecb0, 0xc0037b4041, 0x1e, 0xc000976700, 0x0, 0x0, 0x0, ...)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:569 +0xf1f fp=0xc000ab8258 sp=0xc000ab7540 pc=0x1416d4f
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.(*HTTPSignatureValidationMiddleware).getSecretAndSessionForKeyID(0xc0021e0990, 0xc000976700, 0xc0037b4041, 0x1e, 0xc0016f9f45, 0xb, 0x0, 0x0, 0x0, 0x0, ...)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/mw_http_signature_validation.go:296 +0xa6 fp=0xc000ab86b0 sp=0xc000ab8258 pc=0x1424f46
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.(*HTTPSignatureValidationMiddleware).ProcessRequest(0xc0021e0990, 0x1aab840, 0xc005825260, 0xc000976700, 0x0, 0x0, 0x203001, 0x203001, 0x70)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/mw_http_signature_validation.go:125 +0x1c44 fp=0xc000aba0a0 sp=0xc000ab86b0 pc=0x1423494
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.TraceMiddleware.ProcessRequest(0x1ac0f00, 0xc0021e0990, 0x1aab840, 0xc005825260, 0xc000976700, 0x0, 0x0, 0x0, 0x0, 0x0)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:66 +0x3fd fp=0xc000aba240 sp=0xc000aba0a0 pc=0x141202d
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:130 +0x528 fp=0xc000abbfa0 sp=0xc000aba240 pc=0x14968a8
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc003b06900, 0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc000abbfc8 sp=0xc000abbfa0 pc=0xd1cda4
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18 fp=0xc000abdd28 sp=0xc000abbfc8 pc=0x1497298
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc003b06940, 0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc000abdd50 sp=0xc000abdd28 pc=0xd1cda4
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18 fp=0xc000abfab0 sp=0xc000abdd50 pc=0x1497298
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc003b06980, 0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc000abfad8 sp=0xc000abfab0 pc=0xd1cda4
tyk-gateway_1  | vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/go/src/vendor/github.com/rs/cors/cors.go:190 +0x1a4 fp=0xc000abfb30 sp=0xc000abfad8 pc=0x13101d4
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc00607b2c0, 0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc000abfb58 sp=0xc000abfb30 pc=0xd1cda4
tyk-gateway_1  | vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001d2c4e0, 0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/go/src/vendor/github.com/gorilla/mux/mux.go:150 +0x105 fp=0xc000abfc88 sp=0xc000abfb58 pc=0xe89945
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.(*handleWrapper).ServeHTTP(0xc00024e670, 0x1aab840, 0xc005825260, 0xc000976500)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:41 +0x16f fp=0xc000abfcf0 sp=0xc000abfc88 pc=0x145afaf
tyk-gateway_1  | net/http.serverHandler.ServeHTTP(0xc0002a6820, 0x1aab840, 0xc005825260, 0xc000976500)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:2774 +0xa8 fp=0xc000abfd20 sp=0xc000abfcf0 pc=0xd20228
tyk-gateway_1  | net/http.(*conn).serve(0xc002890aa0, 0x1ab0300, 0xc00255c740)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1878 +0x851 fp=0xc000abffc8 sp=0xc000abfd20 pc=0xd1bd61
tyk-gateway_1  | runtime.goexit()
tyk-gateway_1  | 	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000abffd0 sp=0xc000abffc8 pc=0x9e6131
tyk-gateway_1  | created by net/http.(*Server).Serve
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

Thank you!

**Comment by buger** [comment]
@tomshy just to clarify. Original issue was about "org rate limits", do you use them in your case?

**Comment by tomshy** [comment]
no we don't

**Comment by tomshy** [comment]
We tried to isolate the issue and it seems the gateway panics when you set the `meta_data` object in policy. Opened a new issue [here](https://github.com/TykTechnologies/tyk/issues/3564)
