### ISSUE TITLE
Signing middleware panics if upstream target does not have trailing slash 

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#3242]
**Branch/Environment/Version**
- Branch/Version: Master/Release-2.9
- Environment: All
**Describe the bug**
When we enable signing middleware and upstream target does not have tailing slash, gateway panics

**Reproduction steps**
1. Create api with upstream e.g http//httpbin.org/ip
2. Enable signing middleware for that api
```
"request_signing": {
      "is_enabled": true,
      "secret": "ZGI4YWZhM2MwODE5NDVjNDhiNThjMWE0NDcxMjUwMjA=",
      "key_id": "eyJvcmciOiI1ZTQxM2Y4MGNjZTlmMzA4MDkyMWEwZGQiLCJpZCI6IjY2MzE3OTYyYTkwMjRkN2E5NzViMDQxMmZhNWRiYzU3IiwiaCI6Im11cm11cjY0In0=",
      "algorithm": "hmac-sha1",
      "header_list": [],
      "certificate_id": "",
      "signature_header": ""
```
3. Send some traffic to that api

**Actual behavior**
Gateway will panics 

**Expected behavior**
Gateway should not panics

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
```
2020/07/27 15:44:39 http: panic serving 127.0.0.1:51425: runtime error: slice bounds out of range
goroutine 914 [running]:
net/http.(*conn).serve.func1(0xc000820000)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x4c7a620, 0x5b82140)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/TykTechnologies/tyk/gateway.(*RequestSigning).getRequestPath(0xc000a7ea40, 0xc000620900, 0x0, 0x0)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/mw_request_signing.go:86 +0x131
github.com/TykTechnologies/tyk/gateway.(*RequestSigning).ProcessRequest(0xc000a7ea40, 0x50f9940, 0xc000564000, 0xc000620900, 0x0, 0x0, 0x203000, 0x203000, 0x70)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/mw_request_signing.go:123 +0x151
github.com/TykTechnologies/tyk/gateway.TraceMiddleware.ProcessRequest(0x510e4e0, 0xc000a7ea40, 0x50f9940, 0xc000564000, 0xc000620900, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/middleware.go:66 +0x3fd
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x50f9940, 0xc000564000, 0xc000620900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/middleware.go:130 +0x528
net/http.HandlerFunc.ServeHTTP(0xc0005b2fc0, 0x50f9940, 0xc000564000, 0xc000620900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x50f9940, 0xc000564000, 0xc000620900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18
net/http.HandlerFunc.ServeHTTP(0xc0005b3000, 0x50f9940, 0xc000564000, 0xc000620900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x50f9940, 0xc000564000, 0xc000620900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18
net/http.HandlerFunc.ServeHTTP(0xc0005b3040, 0x50f9940, 0xc000564000, 0xc000620900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x50f9940, 0xc000564000, 0xc000620900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18
net/http.HandlerFunc.ServeHTTP(0xc0005b3080, 0x50f9940, 0xc000564000, 0xc000620900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x50f9940, 0xc000564000, 0xc000620900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18
net/http.HandlerFunc.ServeHTTP(0xc0005b30c0, 0x50f9940, 0xc000564000, 0xc000620900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x50f9940, 0xc000564000, 0xc000620900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18
net/http.HandlerFunc.ServeHTTP(0xc0005b3100, 0x50f9940, 0xc000564000, 0xc000620900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x50f9940, 0xc000564000, 0xc000620900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18
net/http.HandlerFunc.ServeHTTP(0xc0005b3140, 0x50f9940, 0xc000564000, 0xc000620900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x50f9940, 0xc000564000, 0xc000620900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18
net/http.HandlerFunc.ServeHTTP(0xc0005b3180, 0x50f9940, 0xc000564000, 0xc000620900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x50f9940, 0xc000564000, 0xc000620900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18
net/http.HandlerFunc.ServeHTTP(0xc0005b31c0, 0x50f9940, 0xc000564000, 0xc000620900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000b7a180, 0x50f9940, 0xc000564000, 0xc000620900)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0x105
github.com/TykTechnologies/tyk/gateway.(*handleWrapper).ServeHTTP(0xc000386208, 0x50f9940, 0xc000564000, 0xc000620700)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:41 +0x16f
net/http.serverHandler.ServeHTTP(0xc0000d0750, 0x50f9940, 0xc000564000, 0xc000620700)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000820000, 0x50ff0c0, 0xc0005d2a00)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by ilijabojanovic** [comment]
Verified
