### ISSUE TITLE
Gateway panic after reading session from storage engine

### ISSUE THREAD

**Issue by goughy000** [TykTechnologies/tyk#3307]
_Note: This is a bug report from my personal usage of Tyk Gateway.  Views and work is that of my own, not of my employer_

**Branch/Environment/Version**
- Branch/Version: v2.9.4.4
- Environment: Docker, local

**Describe the bug**

Gateway panic after reading user.SessionState from storage engine

**Reproduction steps**

1. Start redis docker
2. Start tyk docker with an api definition and policy defined
3. Generate a key to access that api
4. Use the key and observe it works fine
5. Stop and start the tyk-gateway container (leave redis running)
6. Use the key to call the api again

**Actual behavior**
```
2020/09/09 18:52:39 http: panic serving 172.17.0.1:57934: runtime error: invalid memory address or nil pointer dereference
goroutine 106 [running]:
net/http.(*conn).serve.func1(0xc0004b2a00)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x1635b40, 0x25fe080)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:48
github.com/TykTechnologies/tyk/user.(*SessionState).GetMetaData(0xc000579388, 0x0)
	/go/src/github.com/TykTechnologies/tyk/user/session.go:199 +0x38
github.com/TykTechnologies/tyk/gateway.BaseMiddleware.ApplyPolicies(0xc000464400, 0x1ad0200, 0xc0001cac40, 0xc000148690, 0xc000579388, 0x1790020, 0xc0001203c0)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:290 +0xcf
github.com/TykTechnologies/tyk/gateway.BaseMiddleware.CheckSessionAndIdentityForValidKey(0xc000464400, 0x1ad0200, 0xc0001cac40, 0xc000148690, 0xc000579b38, 0xc0001a6300, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:594 +0x2f8
github.com/TykTechnologies/tyk/gateway.(*AuthKey).ProcessRequest(0xc0004d0ac0, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300, 0x0, 0x0, 0x203000, 0x203000, 0xe00fae)
	/go/src/github.com/TykTechnologies/tyk/gateway/mw_auth_key.go:87 +0x440
github.com/TykTechnologies/tyk/gateway.TraceMiddleware.ProcessRequest(0x1ae6600, 0xc0004d0ac0, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:67 +0x3fd
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:131 +0x55f
net/http.HandlerFunc.ServeHTTP(0xc0003c1940, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:166 +0xf4f
net/http.HandlerFunc.ServeHTTP(0xc0003c1980, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:166 +0xf4f
net/http.HandlerFunc.ServeHTTP(0xc0003c19c0, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/usr/local/go/src/net/http/server.go:1995 +0x44
vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0005b3d40, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/go/src/vendor/github.com/gorilla/mux/mux.go:150 +0x105
github.com/TykTechnologies/tyk/gateway.(*handleWrapper).ServeHTTP(0xc0000ae888, 0x1ad12c0, 0xc0003920e0, 0xc0001bae00)
	/go/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:41 +0x16f
net/http.serverHandler.ServeHTTP(0xc00051c1a0, 0x1ad12c0, 0xc0003920e0, 0xc0001bae00)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0004b2a00, 0x1ad5e00, 0xc000078680)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Expected behavior**
Key should work fine after reloading the gateway instance

**Screenshots/Video**

**Logs (debug mode or log file):**

```
**************************************************************************************************************
*                                           WARNING                                                          *
**               USING GATEWAY SECRET IN TYK.CONF BECAUSE NO ENV VARIABLE SET                               **
*                                REFER TO IMAGE README FOR MORE INFO                                         *
**************************************************************************************************************

time="Sep 09 18:52:19" level=info msg="Tyk API Gateway v2.9.4.4" prefix=main
time="Sep 09 18:52:19" level=debug msg="Connecting to redis cluster"
time="Sep 09 18:52:19" level=debug msg="Creating new Redis connection pool"
time="Sep 09 18:52:19" level=info msg="--> [REDIS] Creating single-node client"
time="Sep 09 18:52:19" level=debug msg="Session update async pool size" pool_size=50
time="Sep 09 18:52:19" level=debug msg="Notifier will not work in hybrid mode" prefix=main
time="Sep 09 18:52:19" level=debug msg="Storage Engine already initialised..."
time="Sep 09 18:52:19" level=info msg="PIDFile location set to: /var/run/tyk/tyk-gateway.pid" prefix=main
time="Sep 09 18:52:19" level=warning msg="The control_api_port should be changed for production" prefix=main
time="Sep 09 18:52:19" level=warning msg="Insecure configuration allowed: allow_insecure_configs: true" prefix=checkup
time="Sep 09 18:52:19" level=warning msg="Health Checker is deprecated and not recommended" prefix=checkup
time="Sep 09 18:52:19" level=warning msg="Default secret `352d20ee67be67f6340b4c0605b044b7` should be changed for production." prefix=checkup
time="Sep 09 18:52:19" level=debug msg="Initialising default org store" prefix=main
time="Sep 09 18:52:19" level=debug msg="Storage Engine already initialised..."
time="Sep 09 18:52:19" level=debug msg="Storage Engine already initialised..."
time="Sep 09 18:52:19" level=debug msg="Storage Engine already initialised..."
time="Sep 09 18:52:19" level=debug msg="Storage Engine already initialised..."
time="Sep 09 18:52:19" level=debug msg="Error trying to get value:redis: nil"
time="Sep 09 18:52:19" level=info msg="Redis connection pools are ready after number of retires" currRetry=0
time="Sep 09 18:52:19" level=info msg="Redis connection pools are ready" prefix=main
time="Sep 09 18:52:19" level=info msg="Initialising Tyk REST API Endpoints" prefix=main
time="Sep 09 18:52:19" level=debug msg="No Primary instance found, assuming control" prefix=host-check-mgr
time="Sep 09 18:52:19" level=info msg="Starting Poller" prefix=host-check-mgr
time="Sep 09 18:52:19" level=debug msg="---> Initialising checker" prefix=host-check-mgr
time="Sep 09 18:52:19" level=debug msg="[HOST CHECKER] Config:TriggerLimit: 3"
time="Sep 09 18:52:19" level=debug msg="[HOST CHECKER] Config:Timeout: ~10"
time="Sep 09 18:52:19" level=debug msg="[HOST CHECKER] Config:WorkerPool: 2"
time="Sep 09 18:52:19" level=debug msg="[HOST CHECKER] Init complete"
time="Sep 09 18:52:19" level=debug msg="---> Starting checker" prefix=host-check-mgr
time="Sep 09 18:52:19" level=debug msg="[HOST CHECKER] Starting..."
time="Sep 09 18:52:19" level=debug msg="[HOST CHECKER] Check loop started..."
time="Sep 09 18:52:19" level=debug msg="[HOST CHECKER] Host reporter started..."
time="Sep 09 18:52:19" level=debug msg="---> Checker started." prefix=host-check-mgr
time="Sep 09 18:52:19" level=debug msg="Loaded API Endpoints" prefix=main
time="Sep 09 18:52:19" level=info msg="--> Standard listener (http)" port=":8080" prefix=main
time="Sep 09 18:52:19" level=warning msg="Starting HTTP server on:[::]:8080" prefix=main
time="Sep 09 18:52:19" level=info msg="Initialising distributed rate limiter" prefix=main
time="Sep 09 18:52:19" level=debug msg="DRL: Setting node ID: solo-ec5c41fe-5cf3-4e67-aa93-7978ec0e4023|333f887175f5"
time="Sep 09 18:52:19" level=info msg="Tyk Gateway started (v2.9.4.4)" prefix=main
time="Sep 09 18:52:19" level=info msg="--> Listening on address: (open interface)" prefix=main
time="Sep 09 18:52:19" level=info msg="--> Listening on port: 8080" prefix=main
time="Sep 09 18:52:19" level=info msg="--> PID: 9" prefix=main
time="Sep 09 18:52:19" level=info msg="Loading policies" prefix=main
time="Sep 09 18:52:19" level=info msg="Starting gateway rate limiter notifications..."
time="Sep 09 18:52:19" level=info msg="Policies found (1 total):" prefix=main
time="Sep 09 18:52:19" level=debug msg=" - my-policy-id" prefix=main
time="Sep 09 18:52:19" level=info msg="Loading API Specification from /opt/tyk-gateway/apps/one.json"
time="Sep 09 18:52:19" level=debug msg="Checking for transform paths..."
time="Sep 09 18:52:19" level=debug msg="Checking for transform paths..."
time="Sep 09 18:52:19" level=info msg="Detected 1 APIs" prefix=main
time="Sep 09 18:52:19" level=info msg="Loading API configurations." prefix=main
time="Sep 09 18:52:19" level=info msg="Tracking hostname" api_name="Tyk Test API" domain="(no host)" prefix=main
time="Sep 09 18:52:19" level=info msg="Initialising Tyk REST API Endpoints" prefix=main
time="Sep 09 18:52:19" level=debug msg="Loaded API Endpoints" prefix=main
time="Sep 09 18:52:19" level=debug msg="Storage Engine already initialised..."
time="Sep 09 18:52:19" level=info msg="API bind on custom port:0" prefix=main
time="Sep 09 18:52:19" level=debug msg="Storage Engine already initialised..."
time="Sep 09 18:52:19" level=debug msg="Storage Engine already initialised..."
time="Sep 09 18:52:19" level=info msg="Initializing HealthChecker"
time="Sep 09 18:52:19" level=debug msg="Storage Engine already initialised..."
time="Sep 09 18:52:19" level=debug msg="Storage Engine already initialised..."
time="Sep 09 18:52:19" level=debug msg="Initializing API" api_id=my-api-id api_name="Tyk Test API" org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg="Connecting to redis cluster"
time="Sep 09 18:52:19" level=debug msg="Creating new Redis connection pool"
time="Sep 09 18:52:19" level=info msg="--> [REDIS] Creating single-node client"
time="Sep 09 18:52:19" level=debug msg=Init api_id=my-api-id api_name="Tyk Test API" mw=VersionCheck org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg=Init api_id=my-api-id api_name="Tyk Test API" mw=RateCheckMW org_id=my-org-id
time="Sep 09 18:52:19" level=info msg="Checking security policy: Token" api_id=my-api-id api_name="Tyk Test API" org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg=Init api_id=my-api-id api_name="Tyk Test API" mw=AuthKey org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg=Init api_id=my-api-id api_name="Tyk Test API" mw=KeyExpired org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg=Init api_id=my-api-id api_name="Tyk Test API" mw=AccessRightsCheck org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg=Init api_id=my-api-id api_name="Tyk Test API" mw=GranularAccessMiddleware org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg=Init api_id=my-api-id api_name="Tyk Test API" mw=RateLimitAndQuotaCheck org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg=Init api_id=my-api-id api_name="Tyk Test API" mw=TransformHeaders org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg=Init api_id=my-api-id api_name="Tyk Test API" mw=VersionCheck org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg=Init api_id=my-api-id api_name="Tyk Test API" mw=KeyExpired org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg=Init api_id=my-api-id api_name="Tyk Test API" mw=AccessRightsCheck org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg="Rate limit endpoint is: /stubs/tyk/rate-limits/" api_id=my-api-id api_name="Tyk Test API" org_id=my-org-id
time="Sep 09 18:52:19" level=debug msg="Setting Listen Path: /stubs/" api_id=my-api-id api_name="Tyk Test API" org_id=my-org-id
time="Sep 09 18:52:19" level=info msg="API Loaded" api_id=my-api-id api_name="Tyk Test API" org_id=my-org-id prefix=gateway server_name=-- user_id=-- user_ip=--
time="Sep 09 18:52:19" level=debug msg="Checker host list" prefix=main
time="Sep 09 18:52:19" level=info msg="Loading uptime tests..." prefix=host-check-mgr
time="Sep 09 18:52:19" level=debug msg="--- Setting tracking list up" prefix=host-check-mgr
time="Sep 09 18:52:19" level=debug msg="Reset initiated" prefix=host-check-mgr
time="Sep 09 18:52:19" level=debug msg="[HOST CHECKER] Checker reset queued!"
time="Sep 09 18:52:19" level=debug msg="Checker host Done" prefix=main
time="Sep 09 18:52:19" level=info msg="Initialised API Definitions" prefix=main
time="Sep 09 18:52:19" level=info msg="API reload complete" prefix=main






time="Sep 09 18:52:27" level=debug msg="[HOST CHECKER] Host list reset"
time="Sep 09 18:52:29" level=debug msg="Primary instance set, I am master" prefix=host-check-mgr
time="Sep 09 18:52:39" level=debug msg=Started api_id=my-api-id api_name="Tyk Test API" mw=VersionCheck org_id=my-org-id origin=172.17.0.1 path="/stubs/hello-world" ts=1599677559387388794
time="Sep 09 18:52:39" level=debug msg=Finished api_id=my-api-id api_name="Tyk Test API" code=200 mw=VersionCheck ns=195062 org_id=my-org-id origin=172.17.0.1 path="/stubs/hello-world"
time="Sep 09 18:52:39" level=debug msg=Started api_id=my-api-id api_name="Tyk Test API" mw=RateCheckMW org_id=my-org-id origin=172.17.0.1 path="/stubs/hello-world" ts=1599677559387744382
time="Sep 09 18:52:39" level=debug msg=Finished api_id=my-api-id api_name="Tyk Test API" code=200 mw=RateCheckMW ns=96697 org_id=my-org-id origin=172.17.0.1 path="/stubs/hello-world"
time="Sep 09 18:52:39" level=debug msg=Started api_id=my-api-id api_name="Tyk Test API" mw=AuthKey org_id=my-org-id origin=172.17.0.1 path="/stubs/hello-world" ts=1599677559387874670
time="Sep 09 18:52:39" level=debug msg="Querying local cache" api_id=my-api-id api_name="Tyk Test API" mw=AuthKey org_id=my-org-id origin=172.17.0.1 path="/stubs/hello-world"
time="Sep 09 18:52:39" level=debug msg="Querying keystore" api_id=my-api-id api_name="Tyk Test API" mw=AuthKey org_id=my-org-id origin=172.17.0.1 path="/stubs/hello-world"
2020/09/09 18:52:39 http: panic serving 172.17.0.1:57934: runtime error: invalid memory address or nil pointer dereference
goroutine 106 [running]:
net/http.(*conn).serve.func1(0xc0004b2a00)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x1635b40, 0x25fe080)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:48
github.com/TykTechnologies/tyk/user.(*SessionState).GetMetaData(0xc000579388, 0x0)
	/go/src/github.com/TykTechnologies/tyk/user/session.go:199 +0x38
github.com/TykTechnologies/tyk/gateway.BaseMiddleware.ApplyPolicies(0xc000464400, 0x1ad0200, 0xc0001cac40, 0xc000148690, 0xc000579388, 0x1790020, 0xc0001203c0)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:290 +0xcf
github.com/TykTechnologies/tyk/gateway.BaseMiddleware.CheckSessionAndIdentityForValidKey(0xc000464400, 0x1ad0200, 0xc0001cac40, 0xc000148690, 0xc000579b38, 0xc0001a6300, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:594 +0x2f8
github.com/TykTechnologies/tyk/gateway.(*AuthKey).ProcessRequest(0xc0004d0ac0, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300, 0x0, 0x0, 0x203000, 0x203000, 0xe00fae)
	/go/src/github.com/TykTechnologies/tyk/gateway/mw_auth_key.go:87 +0x440
github.com/TykTechnologies/tyk/gateway.TraceMiddleware.ProcessRequest(0x1ae6600, 0xc0004d0ac0, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:67 +0x3fd
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:131 +0x55f
net/http.HandlerFunc.ServeHTTP(0xc0003c1940, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:166 +0xf4f
net/http.HandlerFunc.ServeHTTP(0xc0003c1980, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:166 +0xf4f
net/http.HandlerFunc.ServeHTTP(0xc0003c19c0, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/usr/local/go/src/net/http/server.go:1995 +0x44
vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0005b3d40, 0x1ad12c0, 0xc0003920e0, 0xc0001a6300)
	/go/src/vendor/github.com/gorilla/mux/mux.go:150 +0x105
github.com/TykTechnologies/tyk/gateway.(*handleWrapper).ServeHTTP(0xc0000ae888, 0x1ad12c0, 0xc0003920e0, 0xc0001bae00)
	/go/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:41 +0x16f
net/http.serverHandler.ServeHTTP(0xc00051c1a0, 0x1ad12c0, 0xc0003920e0, 0xc0001bae00)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0004b2a00, 0x1ad5e00, 0xc000078680)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
time="Sep 09 18:52:39" level=debug msg="Primary instance set, I am master" prefix=host-check-mgr
time="Sep 09 18:52:49" level=debug msg="Primary instance set, I am master" prefix=host-check-mgr
```

**Configuration (tyk config file):**

tyk.conf
```
{
  "log_level": "debug",
  "listen_port": 8080,
  "secret": "352d20ee67be67f6340b4c0605b044b7",
  "template_path": "/opt/tyk-gateway/templates",
  "tyk_js_path": "/opt/tyk-gateway/js/tyk.js",
  "middleware_path": "/opt/tyk-gateway/middleware",
  "use_db_app_configs": false,
  "app_path": "/opt/tyk-gateway/apps/",
  "storage": {
    "type": "redis",
    "host": "redis",
    "port": 6379,
    "username": "",
    "password": "",
    "database": 0,
    "optimisation_max_idle": 2000,
    "optimisation_max_active": 4000
  },
  "enable_analytics": false,
  "analytics_config": {
    "type": "csv",
    "csv_dir": "/tmp",
    "mongo_url": "",
    "mongo_db_name": "",
    "mongo_collection": "",
    "purge_delay": -1,
    "ignored_ips": []
  },
  "health_check": {
    "enable_health_checks": true,
    "health_check_value_timeouts": 60
  },
  "optimisations_use_async_session_write": true,
  "enable_non_transactional_rate_limiter": true,
  "enable_sentinel_rate_limiter": false,
  "enable_redis_rolling_limiter": false,
  "allow_master_keys": false,
  "policies": {
    "policy_source": "file",
    "policy_record_name": "/opt/tyk-gateway/policies/policies.json"
  },
  "hash_keys": true,
  "close_connections": false,
  "http_server_options": {
    "enable_websockets": true
  },
  "allow_insecure_configs": true,
  "coprocess_options": {
    "enable_coprocess": true,
    "coprocess_grpc_server": ""
  },
  "enable_bundle_downloader": true,
  "bundle_base_url": "",
  "global_session_lifetime": 100,
  "force_global_session_lifetime": false,
  "max_idle_connections_per_host": 500
}
```

apps
```
{
  "name": "Tyk Test API",
  "api_id": "my-api-id",
  "org_id": "my-org-id",
  "definition": {
    "location": "",
    "key": ""
  },
  "global_rate_limit": {
    "rate": 0,
    "per": 0
  },
  "use_keyless": false,
  "auth": {
    "auth_header_name": "api-key"
  },
  "version_data": {
    "not_versioned": true,
    "versions": {
      "Default": {
        "name": "Default",
        "expires": "3000-01-02 15:04",
        "use_extended_paths": true,
        "extended_paths": {
          "ignored": [],
          "white_list": [],
          "black_list": [],
          "transform_headers": [{
            "delete_headers": ["wibble"],
            "add_headers": {
              "wibble": "$tyk_meta.wibble"
            },
            "path": ".*",
            "method": "GET"
          }]
        }
      }
    }
  },
  "proxy": {
    "listen_path": "/stubs/",
    "target_url": "http://stubs:8882/",
    "strip_listen_path": true
  },
  "do_not_track": true
}
```

policies.json
```
{
  "my-policy-id": {
      "rate": 0,
      "per": 0,
      "quota_max": 0,
      "quota_renewal_rate": 0,
      "access_rights": {
        "my-api-id": {
          "api_name": "Tyk Test API",
          "api_id": "my-api-id",
          "versions": [
            "Default"
          ]
        }
      },
      "org_id": "my-org-id",
      "hmac_enabled": false,
      "meta_data": {
        "wibble": "wobble"
      }
  }
}
```

**Additional context**

I think it's possibly something to do with this
https://github.com/TykTechnologies/tyk/blob/v2.9.4.4/gateway/auth_manager.go#L321

session.Mutex is not set? (not a serialized field)

Probably a regression from #3300 

(if it is this, then similar bug might be here too: https://github.com/TykTechnologies/tyk/blob/v2.9.4.4/gateway/auth_manager.go#L149 )

**Comment by christtyk** [comment]
Thank you for reporting this! We are reviewing for a fix

**Comment by letzya** [comment]
Looks related https://github.com/TykTechnologies/tyk/issues/3227
