### ISSUE TITLE
Concurrent Map Writes when setting meta_data in policy

### ISSUE THREAD

**Issue by tomshy** [TykTechnologies/tyk#3564]
**Branch/Environment/Version**
- Branch/Version: Tyk version 2.9.4 onwards
- Environment: On-prem

**Describe the bug**
Gateway panics when you set `meta_data` object in policy, apply the policy to a key and send a high volume of requests to the gateway using the key. 

**Reproduction steps**

1. Add api...
2. Add policy and set `meta_data` on policy
3. Apply policy to key
4. Send high volume of requests to gateway using the key

**Actual behavior**
Gateway panics as shown in the error log below

**Expected behavior**
Gateway should be able to handle the requests without panicking

**Logs**
```
tyk-gateway_1  | fatal error: concurrent map writes
tyk-gateway_1  | 
tyk-gateway_1  | goroutine 746914 [running]:
tyk-gateway_1  | runtime.throw(0x17b5f82, 0x15)
tyk-gateway_1  | 	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000ab64e0 sp=0xc000ab64b0 pc=0x9b5b92
tyk-gateway_1  | runtime.mapassign_faststr(0x16094e0, 0xc00469a0f0, 0xc0021d5b30, 0x3, 0xc00449d088)
tyk-gateway_1  | 	/usr/local/go/src/runtime/map_faststr.go:211 +0x42a fp=0xc000ab6548 sp=0xc000ab64e0 pc=0x99b26a
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.BaseMiddleware.ApplyPolicies(0xc001646400, 0x1aaa780, 0xc000129ab0, 0xc00096ecb0, 0xc000ab7ec8, 0x1, 0x0)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:467 +0xfb3 fp=0xc000ab7540 sp=0xc000ab6548 pc=0x1414533
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.BaseMiddleware.CheckSessionAndIdentityForValidKey(0xc001646400, 0x1aaa780, 0xc000129ab0, 0xc00096ecb0, 0xc0037b4041, 0x1e, 0xc000976700, 0x0, 0x0, 0x0, ...)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:569 +0xf1f fp=0xc000ab8258 sp=0xc000ab7540 pc=0x1416d4f
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.(*HTTPSignatureValidationMiddleware).getSecretAndSessionForKeyID(0xc0021e0990, 0xc000976700, 0xc0037b4041, 0x1e, 0xc0016f9f45, 0xb, 0x0, 0x0, 0x0, 0x0, ...)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/mw_http_signature_validation.go:296 +0xa6 fp=0xc000ab86b0 sp=0xc000ab8258 pc=0x1424f46
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.(*HTTPSignatureValidationMiddleware).ProcessRequest(0xc0021e0990, 0x1aab840, 0xc005825260, 0xc000976700, 0x0, 0x0, 0x203001, 0x203001, 0x70)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/mw_http_signature_validation.go:125 +0x1c44 fp=0xc000aba0a0 sp=0xc000ab86b0 pc=0x1423494
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.TraceMiddleware.ProcessRequest(0x1ac0f00, 0xc0021e0990, 0x1aab840, 0xc005825260, 0xc000976700, 0x0, 0x0, 0x0, 0x0, 0x0)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:66 +0x3fd fp=0xc000aba240 sp=0xc000aba0a0 pc=0x141202d
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:130 +0x528 fp=0xc000abbfa0 sp=0xc000aba240 pc=0x14968a8
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc003b06900, 0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc000abbfc8 sp=0xc000abbfa0 pc=0xd1cda4
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18 fp=0xc000abdd28 sp=0xc000abbfc8 pc=0x1497298
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc003b06940, 0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc000abdd50 sp=0xc000abdd28 pc=0xd1cda4
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:165 +0xf18 fp=0xc000abfab0 sp=0xc000abdd50 pc=0x1497298
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc003b06980, 0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc000abfad8 sp=0xc000abfab0 pc=0xd1cda4
tyk-gateway_1  | vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/go/src/vendor/github.com/rs/cors/cors.go:190 +0x1a4 fp=0xc000abfb30 sp=0xc000abfad8 pc=0x13101d4
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc00607b2c0, 0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc000abfb58 sp=0xc000abfb30 pc=0xd1cda4
tyk-gateway_1  | vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001d2c4e0, 0x1aab840, 0xc005825260, 0xc000976700)
tyk-gateway_1  | 	/go/src/vendor/github.com/gorilla/mux/mux.go:150 +0x105 fp=0xc000abfc88 sp=0xc000abfb58 pc=0xe89945
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.(*handleWrapper).ServeHTTP(0xc00024e670, 0x1aab840, 0xc005825260, 0xc000976500)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:41 +0x16f fp=0xc000abfcf0 sp=0xc000abfc88 pc=0x145afaf
tyk-gateway_1  | net/http.serverHandler.ServeHTTP(0xc0002a6820, 0x1aab840, 0xc005825260, 0xc000976500)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:2774 +0xa8 fp=0xc000abfd20 sp=0xc000abfcf0 pc=0xd20228
tyk-gateway_1  | net/http.(*conn).serve(0xc002890aa0, 0x1ab0300, 0xc00255c740)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1878 +0x851 fp=0xc000abffc8 sp=0xc000abfd20 pc=0xd1bd61
tyk-gateway_1  | runtime.goexit()
tyk-gateway_1  | 	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000abffd0 sp=0xc000abffc8 pc=0x9e6131
tyk-gateway_1  | created by net/http.(*Server).Serve
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Additional context**
Related issue [here](https://github.com/TykTechnologies/tyk/issues/3227)

**Comment by buger** [comment]
Thank you for isolating! 

Issue looks very similar to https://github.com/TykTechnologies/tyk/pull/3274 which was fixed in 3.0.2 

Here is 3.0.1 behavior https://github.com/TykTechnologies/tyk/blob/v3.0.1/gateway/middleware.go#L526
And here is 3.0.2 https://github.com/TykTechnologies/tyk/blob/v3.0.2/gateway/middleware.go#L535

Can you try on 3.0.3/3.0.4 release? 
Thank you!

**Comment by tomshy** [comment]
Tried the suggested versions. However, the gateway still panics with a slightly different error. Here's the stacktrace:
```
tyk-gateway_1  | fatal error: concurrent map iteration and map write
tyk-gateway_1  | 
tyk-gateway_1  | goroutine 4938 [running]:
tyk-gateway_1  | runtime.throw(0x1fd0d44, 0x26)
tyk-gateway_1  | 	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0040cecb8 sp=0xc0040cec88 pc=0xcb7312
tyk-gateway_1  | runtime.mapiternext(0xc0040ceda0)
tyk-gateway_1  | 	/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc0040ced40 sp=0xc0040cecb8 pc=0xc98907
tyk-gateway_1  | runtime.mapiterinit(0x1d65ec0, 0xc004033aa0, 0xc0040ceda0)
tyk-gateway_1  | 	/usr/local/go/src/runtime/map.go:850 +0x1c9 fp=0xc0040ced60 sp=0xc0040ced40 pc=0xc98279
tyk-gateway_1  | github.com/TykTechnologies/tyk/user.cloneMetadata(0xc004033aa0, 0xc001e57850)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/user/session.go:188 +0x9e fp=0xc0040cee10 sp=0xc0040ced60 pc=0x14762be
tyk-gateway_1  | github.com/TykTechnologies/tyk/user.(*SessionState).Clone(0xc003f72000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/user/session.go:157 +0x10a fp=0xc0040cf0a0 sp=0xc0040cee10 pc=0x1475d1a
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.BaseMiddleware.CheckSessionAndIdentityForValidKey(0xc000147400, 0x2627900, 0xc00324b2d0, 0xc0025fa000, 0xc0040d0518, 0xc004fc6f00, 0x0, 0x0, 0x0, 0x0, ...)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:650 +0x15b1 fp=0xc0040cfe98 sp=0xc0040cf0a0 pc=0x1ae9681
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.(*HTTPSignatureValidationMiddleware).getSecretAndSessionForKeyID(0xc003252450, 0xc004fc6f00, 0xc0041af301, 0x1e, 0xc0041af205, 0xb, 0x0, 0x0, 0x0, 0x0, ...)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/mw_http_signature_validation.go:296 +0xbc fp=0xc0040d0508 sp=0xc0040cfe98 pc=0x1afa1dc
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.(*HTTPSignatureValidationMiddleware).ProcessRequest(0xc003252450, 0x26289c0, 0xc0051797a0, 0xc004fc6f00, 0x0, 0x0, 0x203000, 0x203000, 0x70)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/mw_http_signature_validation.go:125 +0x1c4c fp=0xc0040d1f38 sp=0xc0040d0508 pc=0x1af870c
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.TraceMiddleware.ProcessRequest(0x2642d20, 0xc003252450, 0x26289c0, 0xc0051797a0, 0xc004fc6f00, 0x0, 0x0, 0x0, 0x0, 0x0)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:73 +0x3fd fp=0xc0040d20d8 sp=0xc0040d1f38 pc=0x1ae3bed
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x26289c0, 0xc0051797a0, 0xc004fc6f00)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:137 +0x528 fp=0xc0040d3eb0 sp=0xc0040d20d8 pc=0x1b738f8
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc003233580, 0x26289c0, 0xc0051797a0, 0xc004fc6f00)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc0040d3ed8 sp=0xc0040d3eb0 pc=0xfe5ca4
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x26289c0, 0xc0051797a0, 0xc004fc6f00)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:172 +0xf18 fp=0xc0040d5cb0 sp=0xc0040d3ed8 pc=0x1b742e8
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc0032335c0, 0x26289c0, 0xc0051797a0, 0xc004fc6f00)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc0040d5cd8 sp=0xc0040d5cb0 pc=0xfe5ca4
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.createMiddleware.func1.1(0x26289c0, 0xc0051797a0, 0xc004fc6f00)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:172 +0xf18 fp=0xc0040d7ab0 sp=0xc0040d5cd8 pc=0x1b742e8
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc003233600, 0x26289c0, 0xc0051797a0, 0xc004fc6f00)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc0040d7ad8 sp=0xc0040d7ab0 pc=0xfe5ca4
tyk-gateway_1  | vendor/github.com/rs/cors.(*Cors).Handler.func1(0x26289c0, 0xc0051797a0, 0xc004fc6f00)
tyk-gateway_1  | 	/go/src/vendor/github.com/rs/cors/cors.go:219 +0x1b8 fp=0xc0040d7b30 sp=0xc0040d7ad8 pc=0x1a5b9f8
tyk-gateway_1  | net/http.HandlerFunc.ServeHTTP(0xc00324e660, 0x26289c0, 0xc0051797a0, 0xc004fc6f00)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc0040d7b58 sp=0xc0040d7b30 pc=0xfe5ca4
tyk-gateway_1  | vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000aed80, 0x26289c0, 0xc0051797a0, 0xc004fc6d00)
tyk-gateway_1  | 	/go/src/vendor/github.com/gorilla/mux/mux.go:212 +0xe3 fp=0xc0040d7c88 sp=0xc0040d7b58 pc=0x13b5123
tyk-gateway_1  | github.com/TykTechnologies/tyk/gateway.(*handleWrapper).ServeHTTP(0xc000010a90, 0x26289c0, 0xc0051797a0, 0xc004fc6d00)
tyk-gateway_1  | 	/go/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:41 +0x16f fp=0xc0040d7cf0 sp=0xc0040d7c88 pc=0x1b3263f
tyk-gateway_1  | net/http.serverHandler.ServeHTTP(0xc00072b520, 0x26289c0, 0xc0051797a0, 0xc004fc6d00)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:2774 +0xa8 fp=0xc0040d7d20 sp=0xc0040d7cf0 pc=0xfe9128
tyk-gateway_1  | net/http.(*conn).serve(0xc004747ae0, 0x262e0c0, 0xc0026e1440)
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:1878 +0x851 fp=0xc0040d7fc8 sp=0xc0040d7d20 pc=0xfe4c61
tyk-gateway_1  | runtime.goexit()
tyk-gateway_1  | 	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0040d7fd0 sp=0xc0040d7fc8 pc=0xce78b1
tyk-gateway_1  | created by net/http.(*Server).Serve
tyk-gateway_1  | 	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by buger** [comment]
Right! My research shows the same, here is PR which fix it https://github.com/TykTechnologies/tyk/pull/3567

Also, it is possible to overcome the issue by setting `local_session_cache.disable_cached_session_state` to `true`, but it may come with some performance penalty.

**Comment by tomshy** [comment]
Tried out `local_session_cache.disable_cached_session_state: true` and for sure it's a workaround the issue. However, as you said it's affecting performance. 

Will wait for the docker release containing the fix!

Thanks @buger
