### ISSUE TITLE
fatal error: runtime: no plugin module data

### ISSUE THREAD

**Issue by beng90** [TykTechnologies/tyk#4167]
**Branch/Environment/Version**
- Branch/Version: Master
- Environment: Docker local

**Describe the bug**
I try to build tyk gateway using goreleaser on local host and then load custom plugin but there is still problem with loading.
Without plugin it works fine.

**Reproduction steps**

1. Checkout tyk repository on master branch
2. Execute following command `goreleaser release -f ci/goreleaser/goreleaser.yml --skip-announce --skip-publish --skip-validate --skip-sign --rm-dist --debug`
3. Configure any plugin in your API configuration for example in auth_check
4. Run generated docker image with plugin configuration set

**Actual behavior**
Tyk gateway crashes while running with following error.

fatal error: runtime: no plugin module data

**Expected behavior**
Plugin successfully loaded and tyk doesn't crash

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/10477361/177642544-a4e83a07-1532-4e74-a3a5-4adcb81c980c.png)

**Logs (debug mode or log file):**
`gateway.api | time="Jul 06 13:54:38" level=info msg="Initialising Tyk REST API Endpoints" prefix=main
gateway.api | time="Jul 06 13:54:38" level=info msg="API bind on custom port:0" prefix=main
gateway.api | fatal error: runtime: no plugin module data
gateway.api | 
gateway.api | goroutine 1 [running]:
gateway.api | runtime.throw({0x29e3144?, 0x4000855000?})
gateway.api |   /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000627018 sp=0xc000626fe8 pc=0xf9bf51
gateway.api | plugin.lastmoduleinit()
gateway.api |   /usr/local/go/src/runtime/plugin.go:20 +0x8d0 fp=0xc000627100 sp=0xc000627018 pc=0xfcb5d0
gateway.api | plugin.open({0xc0004d9a40, 0x3a})
gateway.api |   /usr/local/go/src/plugin/plugin_dlopen.go:77 +0x3ea fp=0xc000627370 sp=0xc000627100 pc=0x180cd4a
gateway.api | plugin.Open(...)
gateway.api |   /usr/local/go/src/plugin/plugin.go:32
gateway.api | github.com/TykTechnologies/tyk/goplugin.GetHandler({0xc0004d9a40?, 0xc000627490?}, {0xc0004347d0, 0xa})
gateway.api |   /go/src/github.com/TykTechnologies/tyk/goplugin/goplugin.go:14 +0x33 fp=0xc0006273e0 sp=0xc000627370 pc=0x180da13
gateway.api | github.com/TykTechnologies/tyk/gateway.(*GoPluginMiddleware).loadPlugin(0xc000026840)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/mw_go_plugin.go:135 +0x20b fp=0xc0006276f0 sp=0xc0006273e0 pc=0x241d86b
gateway.api | github.com/TykTechnologies/tyk/gateway.(*GoPluginMiddleware).EnabledForSpec(0xb0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/mw_go_plugin.go:102 +0x3c fp=0xc000627a88 sp=0xc0006276f0 pc=0x241d57c
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).mwAppendEnabled(0xc000629020?, 0xc000628b28, {0x2d90dd0, 0xc000026840})
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/middleware.go:172 +0x35 fp=0xc000627ae8 sp=0xc000627a88 pc=0x240d655
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).processSpec(0xc0003d0000, 0xc000460d80, 0x9?, 0xc0006302c8, 0x0?, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/api_loader.go:383 +0x2931 fp=0xc00062c750 sp=0xc000627ae8 pc=0x23cec91
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).loadHTTPService(0x26f2cc0?, 0xc000460d80, 0x3e43d68?, 0x1?, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/api_loader.go:730 +0x43c fp=0xc00062f568 sp=0xc00062c750 pc=0x23d323c
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).loadApps.func2(0xc0006301f8, 0xc00050b5c0?, 0x2d9b818?, 0x0, 0x2d9b818?, 0xc00050b600?, 0x2d9b5e8?, 0xc00055f260?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/api_loader.go:911 +0x447 fp=0xc00062f688 sp=0xc00062f568 pc=0x23d57c7
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).loadApps(0xc0003d0000, {0xc0005a82c0?, 0x2, 0x2})
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/api_loader.go:915 +0x5b6 fp=0xc000633b00 sp=0xc00062f688 pc=0x23d4ff6
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).loadGlobalApps(0xc0003d0000)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/api_loader.go:631 +0xd1 fp=0xc000633b48 sp=0xc000633b00 pc=0x23d25d1
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).DoReload(0xc0003d0000)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/server.go:927 +0x2c5 fp=0xc000635268 sp=0xc000633b48 pc=0x2492785
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).startServer(0xc0003d0000)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/server.go:1734 +0xbe9 fp=0xc00063ce60 sp=0xc000635268 pc=0x249ad69
gateway.api | github.com/TykTechnologies/tyk/gateway.Start()
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/server.go:1542 +0xa99 fp=0xc00063ff70 sp=0xc00063ce60 pc=0x2498179
gateway.api | main.main()
gateway.api |   /go/src/github.com/TykTechnologies/tyk/main.go:8 +0x17 fp=0xc00063ff80 sp=0xc00063ff70 pc=0x250afd7
gateway.api | runtime.main()
gateway.api |   /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc00063ffe0 sp=0xc00063ff80 pc=0xf9e992
gateway.api | runtime.goexit()
gateway.api |   /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00063ffe8 sp=0xc00063ffe0 pc=0xfd0b61
gateway.api | 
gateway.api | goroutine 19 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc00028bc10, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 20 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc00028bc30, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 21 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc00028bc50, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 22 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc00028bc60, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 23 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc00028bc70, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 24 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc00028bc80, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 25 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc00028bc90, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 26 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc00028bca0, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 27 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc00028bcb0, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 28 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc00028bcc0, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 6 [chan receive]:
gateway.api | github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00011e4e0)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/klauspost/compress/zstd/blockdec.go:215 +0x94
gateway.api | created by github.com/klauspost/compress/zstd.newBlockDec
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/klauspost/compress/zstd/blockdec.go:118 +0x165
gateway.api | 
gateway.api | goroutine 7 [chan receive]:
gateway.api | github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00011e5b0)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/klauspost/compress/zstd/blockdec.go:215 +0x94
gateway.api | created by github.com/klauspost/compress/zstd.newBlockDec
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/klauspost/compress/zstd/blockdec.go:118 +0x165
gateway.api | 
gateway.api | goroutine 8 [chan receive]:
gateway.api | github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00011e680)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/klauspost/compress/zstd/blockdec.go:215 +0x94
gateway.api | created by github.com/klauspost/compress/zstd.newBlockDec
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/klauspost/compress/zstd/blockdec.go:118 +0x165
gateway.api | 
gateway.api | goroutine 9 [chan receive]:
gateway.api | github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00011e9c0)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/klauspost/compress/zstd/blockdec.go:215 +0x94
gateway.api | created by github.com/klauspost/compress/zstd.newBlockDec
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/klauspost/compress/zstd/blockdec.go:118 +0x165
gateway.api | 
gateway.api | goroutine 50 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc0005a8fe0, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 51 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc0005a9000, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 52 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc0005a9470, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 53 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc0005a9480, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 54 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc0005a9490, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 55 [select]:
gateway.api | github.com/TykTechnologies/tyk/gateway.(*HostCheckerManager).CheckActivePollerLoop(0x0?, {0x2d89030, 0xc00007ecc0})
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/host_checker_manager.go:107 +0x105
gateway.api | created by github.com/TykTechnologies/tyk/gateway.(*HostCheckerManager).Start
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/host_checker_manager.go:85 +0xa5
gateway.api | 
gateway.api | goroutine 56 [select]:
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).initHealthCheck.func1({0x2d89030?, 0xc00007ecc0})
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/health_check.go:72 +0x192
gateway.api | created by github.com/TykTechnologies/tyk/gateway.(*Gateway).initHealthCheck
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/health_check.go:62 +0x105
gateway.api | 
gateway.api | goroutine 35 [chan send]:
gateway.api | github.com/Jeffail/tunny.(*workerWrapper).Loop(0xc00033e2a0)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/Jeffail/tunny/worker.go:51 +0x66
gateway.api | created by github.com/Jeffail/tunny.(*workerWrapper).Open
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/Jeffail/tunny/worker.go:80 +0x116
gateway.api | 
gateway.api | goroutine 36 [chan send]:
gateway.api | github.com/Jeffail/tunny.(*workerWrapper).Loop(0xc00033e2d0)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/Jeffail/tunny/worker.go:51 +0x66
gateway.api | created by github.com/Jeffail/tunny.(*workerWrapper).Open
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/Jeffail/tunny/worker.go:80 +0x116
gateway.api | 
gateway.api | goroutine 37 [chan send]:
gateway.api | github.com/Jeffail/tunny.(*workerWrapper).Loop(0xc00033e300)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/Jeffail/tunny/worker.go:51 +0x66
gateway.api | created by github.com/Jeffail/tunny.(*workerWrapper).Open
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/Jeffail/tunny/worker.go:80 +0x116
gateway.api | 
gateway.api | goroutine 38 [chan send]:
gateway.api | github.com/Jeffail/tunny.(*workerWrapper).Loop(0xc00033e330)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/Jeffail/tunny/worker.go:51 +0x66
gateway.api | created by github.com/Jeffail/tunny.(*workerWrapper).Open
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/Jeffail/tunny/worker.go:80 +0x116
gateway.api | 
gateway.api | goroutine 39 [select]:
gateway.api | github.com/TykTechnologies/tyk/gateway.(*HostUptimeChecker).HostCheckLoop(0xc000350000, {0x2d89030, 0xc00007ecc0})
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/host_checker.go:116 +0x119
gateway.api | created by github.com/TykTechnologies/tyk/gateway.(*HostUptimeChecker).Start
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/host_checker.go:389 +0xe5
gateway.api | 
gateway.api | goroutine 40 [select]:
gateway.api | github.com/TykTechnologies/tyk/gateway.(*HostUptimeChecker).HostReporter(0xc000350000, {0x2d89030?, 0xc00007ecc0})
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/host_checker.go:145 +0x12a
gateway.api | created by github.com/TykTechnologies/tyk/gateway.(*HostUptimeChecker).Start
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/host_checker.go:391 +0x193
gateway.api | 
gateway.api | goroutine 31 [select]:
gateway.api | github.com/go-redis/redis/v8/internal/pool.(*ConnPool).reaper(0xc0003cc0a0, 0xc00013e000?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/go-redis/redis/v8/internal/pool/pool.go:485 +0xd4
gateway.api | created by github.com/go-redis/redis/v8/internal/pool.NewConnPool
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/go-redis/redis/v8/internal/pool/pool.go:111 +0x225
gateway.api | 
gateway.api | goroutine 59 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc00040b6e0, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 11 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc0005d0120, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 12 [select]:
gateway.api | github.com/pmylund/go-cache.(*janitor).Run(0xc0005d0130, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1079 +0x85
gateway.api | created by github.com/pmylund/go-cache.runJanitor
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/pmylund/go-cache/cache.go:1099 +0xed
gateway.api | 
gateway.api | goroutine 13 [select]:
gateway.api | github.com/TykTechnologies/tyk/gateway.cleanIdleMemConnProviders({0x2d89030, 0xc00007ecc0})
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/reverse_proxy.go:828 +0xdf
gateway.api | created by github.com/TykTechnologies/tyk/gateway.(*Gateway).initialiseSystem
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/server.go:1230 +0x1145
gateway.api | 
gateway.api | goroutine 14 [sleep]:
gateway.api | time.Sleep(0x2540be400)
gateway.api |   /usr/local/go/src/runtime/time.go:194 +0x12e
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).addPubSubDelay(...)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/redis_signals.go:79
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).startPubSubLoop(0xc0003d0000)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/redis_signals.go:73 +0x7b
gateway.api | created by github.com/TykTechnologies/tyk/gateway.(*Gateway).start
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/server.go:1615 +0x2f7
gateway.api | 
gateway.api | goroutine 15 [select]:
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).reloadLoop(0xc0003d0000, 0xc0005ca480, {0x0, 0x0, 0x0?})
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/server.go:947 +0xad
gateway.api | created by github.com/TykTechnologies/tyk/gateway.(*Gateway).start
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/server.go:1634 +0x6b0
gateway.api | 
gateway.api | goroutine 16 [select]:
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).reloadQueueLoop(0xc0003d0000, {0x0, 0x0, 0x0?})
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/server.go:982 +0xc5
gateway.api | created by github.com/TykTechnologies/tyk/gateway.(*Gateway).start
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/server.go:1635 +0x6ed
gateway.api | 
gateway.api | goroutine 66 [select]:
gateway.api | github.com/TykTechnologies/tyk/storage.(*RedisController).ConnectToRedis(0xc0001a4a10, {0x2d89030, 0xc00007ecc0}, 0xc0005d0230?, 0xc0003d4400)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/storage/redis_controller.go:173 +0x2d4
gateway.api | created by github.com/TykTechnologies/tyk/gateway.Start
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/server.go:1508 +0x7c5
gateway.api | 
gateway.api | goroutine 64 [select]:
gateway.api | github.com/go-redis/redis/v8/internal/pool.(*ConnPool).reaper(0xc0001ce000, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/go-redis/redis/v8/internal/pool/pool.go:485 +0xd4
gateway.api | created by github.com/go-redis/redis/v8/internal/pool.NewConnPool
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/go-redis/redis/v8/internal/pool/pool.go:111 +0x225
gateway.api | 
gateway.api | goroutine 67 [IO wait]:
gateway.api | internal/poll.runtime_pollWait(0x40418739a8, 0x72)
gateway.api |   /usr/local/go/src/runtime/netpoll.go:302 +0x89
gateway.api | internal/poll.(*pollDesc).wait(0xc0003c8180?, 0x0?, 0x0)
gateway.api |   /usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
gateway.api | internal/poll.(*pollDesc).waitRead(...)
gateway.api |   /usr/local/go/src/internal/poll/fd_poll_runtime.go:88
gateway.api | internal/poll.(*FD).Accept(0xc0003c8180)
gateway.api |   /usr/local/go/src/internal/poll/fd_unix.go:614 +0x22c
gateway.api | net.(*netFD).accept(0xc0003c8180)
gateway.api |   /usr/local/go/src/net/fd_unix.go:172 +0x35
gateway.api | net.(*TCPListener).accept(0xc0005d6618)
gateway.api |   /usr/local/go/src/net/tcpsock_posix.go:139 +0x28
gateway.api | net.(*TCPListener).Accept(0xc0005d6618)
gateway.api |   /usr/local/go/src/net/tcpsock.go:288 +0x3d
gateway.api | net/http.(*Server).Serve(0xc000240620, {0x2d87948, 0xc0005d6618})
gateway.api |   /usr/local/go/src/net/http/server.go:3039 +0x385
gateway.api | created by github.com/TykTechnologies/tyk/gateway.(*proxyMux).serve
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/proxy_muxer.go:438 +0x9cd
gateway.api | 
gateway.api | goroutine 68 [chan receive]:
gateway.api | github.com/TykTechnologies/drl.(*Cache).startCleanupTimer.func1()
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/drl/ttlcache.go:85 +0x2d
gateway.api | created by github.com/TykTechnologies/drl.(*Cache).startCleanupTimer
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/drl/ttlcache.go:82 +0xa5
gateway.api | 
gateway.api | goroutine 69 [sleep]:
gateway.api | time.Sleep(0x12a05f200)
gateway.api |   /usr/local/go/src/runtime/time.go:194 +0x12e
gateway.api | github.com/TykTechnologies/drl.(*DRL).Init.func1()
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/drl/drl.go:50 +0x32
gateway.api | created by github.com/TykTechnologies/drl.(*DRL).Init
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/drl/drl.go:45 +0x10a
gateway.api | 
gateway.api | goroutine 70 [sleep]:
gateway.api | time.Sleep(0x77359400)
gateway.api |   /usr/local/go/src/runtime/time.go:194 +0x12e
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).startRateLimitNotifications.func1()
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/distributed_rate_limiter.go:39 +0x79
gateway.api | created by github.com/TykTechnologies/tyk/gateway.(*Gateway).startRateLimitNotifications
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/distributed_rate_limiter.go:26 +0x14e
gateway.api | 
gateway.api | goroutine 88 [select]:
gateway.api | github.com/go-redis/redis/v8/internal/pool.(*ConnPool).reaper(0xc0003cc3c0, 0x0?)
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/go-redis/redis/v8/internal/pool/pool.go:485 +0xd4
gateway.api | created by github.com/go-redis/redis/v8/internal/pool.NewConnPool
gateway.api |   /go/src/github.com/TykTechnologies/tyk/vendor/github.com/go-redis/redis/v8/internal/pool/pool.go:111 +0x225
gateway.api | 
gateway.api | goroutine 71 [IO wait]:
gateway.api | internal/poll.runtime_pollWait(0x4041873a98, 0x72)
gateway.api |   /usr/local/go/src/runtime/netpoll.go:302 +0x89
gateway.api | internal/poll.(*pollDesc).wait(0xc0003c8280?, 0x0?, 0x0)
gateway.api |   /usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
gateway.api | internal/poll.(*pollDesc).waitRead(...)
gateway.api |   /usr/local/go/src/internal/poll/fd_poll_runtime.go:88
gateway.api | internal/poll.(*FD).Accept(0xc0003c8280)
gateway.api |   /usr/local/go/src/internal/poll/fd_unix.go:614 +0x22c
gateway.api | net.(*netFD).accept(0xc0003c8280)
gateway.api |   /usr/local/go/src/net/fd_unix.go:172 +0x35
gateway.api | net.(*TCPListener).accept(0xc00000f1b8)
gateway.api |   /usr/local/go/src/net/tcpsock_posix.go:139 +0x28
gateway.api | net.(*TCPListener).Accept(0xc00000f1b8)
gateway.api |   /usr/local/go/src/net/tcpsock.go:288 +0x3d
gateway.api | net/http.(*Server).Serve(0xc0002409a0, {0x2d87948, 0xc00000f1b8})
gateway.api |   /usr/local/go/src/net/http/server.go:3039 +0x385
gateway.api | github.com/TykTechnologies/tyk/gateway.(*Gateway).TykNewSingleHostReverseProxy.func1.2()
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/reverse_proxy.go:216 +0x25
gateway.api | created by github.com/TykTechnologies/tyk/gateway.(*Gateway).TykNewSingleHostReverseProxy.func1
gateway.api |   /go/src/github.com/TykTechnologies/tyk/gateway/reverse_proxy.go:215 +0x14d
`

**Configuration (tyk config file):**

Tyk has default configuration.

API configuration

`{
  "name": "httpbin",
  "slug": "httpbin",
  "api_id": "1",
  "org_id": "1",
  "use_keyless": false,
  "definition": {
    "location": "header",
    "key": "x-api-version"
  },
  "version_data": {
    "not_versioned": true,
    "versions": {
      "Default": {
        "name": "Default",
        "use_extended_paths": true
      }
    }
  },
  "use_go_plugin_auth": true,
  "custom_middleware": {
    "pre": [],
    "post_auth_check": [],
    "auth_check": {
      "name": "CustomAuth",
      "path": "/opt/tyk-gateway/plugins/test/plugin_v4.1.0_linux_amd64.so"
    },
    "post": [
    ],
    "driver": "goplugin"
  },
  "proxy": {
    "listen_path": "/httpbin/",
    "target_url": "http://httpbin.org/",
    "preserve_host_header": true,
    "strip_listen_path": true
  },
  "active": true
}
`

**Additional context**
I have my own fork with tyk where I made changes but I returned to basics and I'm trying to build pure instance with tyk on my local computer and then connect plugin. In google I found tips that it can be related with dynamic linking problems but I use linux/amd64 architecture and in this image there are not lddflags.

**Comment by buger** [comment]
Hello! This is smth new. 
How do you compile your plugin? 
Can you share code of your plugin, does it use CGO libraries? 

Thanks!

**Comment by beng90** [comment]
Sure. This is my simple code.

`package main

import (
	"fmt"
	"net/http"
)

func CustomAuth(rw http.ResponseWriter, r *http.Request) {
	fmt.Println("something")
}

func main() {}
`

Command to compile plugin:
`docker run --platform linux/amd64 --rm -v `pwd`:/plugin-source tykio/tyk-plugin-compiler:v4.1.0-rc16 plugin.so`

I've tried a lot of versions and I'm sure that I'm using the same tag as it used in building gateway.

Verified either on ubuntu and Mac OS.

GOLANG_CROSS = 1.15
CGO_ENABLED=1

**Comment by beng90** [comment]
Can you provide some simple command for ubuntu or Mac OS to build docker images which you use to development?

**Comment by beng90** [comment]
Do you have command to simply build tyk-gateway this way?
goreleaser needs ENVs e.g. GOLANG_CROSS and I set it to 1.15

**Comment by andyo-tyk** [comment]
It's not clear from the above what problem you were seeing with the tyk-gateway once you'd successfully built the plugin and run it per @buger's direction.

I'm closing this, due to length of time since the last update as I suspect you may have resolved the issue yourself.

If you're still hitting problems, please don't hesitate to comment here, then I can re-open this ticket and we will see what we can do to unblock you.
