### ISSUE TITLE
TestHostChecker flake (negative WaitGroup counter)

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#770]
https://travis-ci.org/TykTechnologies/tyk/jobs/235966342

```
=== RUN   TestHostChecker
WARN Legacy path detected! Upgrade to extended.
INFO host-check-mgr: Loading uptime tests...
INFO host-check-mgr: ---> Adding uptime test: http://127.0.0.1:16500/get
INFO host-check-mgr: ---> Adding uptime test: http://127.0.0.1:16501/get
WARN host-check-mgr: [HOST CHECKER MANAGER] Host is DOWN: http://127.0.0.1:16500/get
WARN host-check-mgr: [HOST CHECKER MANAGER] Host is DOWN: http://127.0.0.1:16501/get
panic: sync: negative WaitGroup counter
goroutine 10752 [running]:
sync.(*WaitGroup).Add(0xc4247283f0, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/sync/waitgroup.go:75 +0x1c9
sync.(*WaitGroup).Done(0xc4247283f0)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/sync/waitgroup.go:100 +0x34
github.com/TykTechnologies/tyk.TestHostChecker.func1(0xdf031f, 0x8, 0xd2d560, 0xc424d49480, 0xc424725980, 0x27)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/host_checker_test.go:89 +0x2a
github.com/TykTechnologies/tyk.(*testEventHandler).HandleEvent(0xc4241165e0, 0xdf031f, 0x8, 0xd2d560, 0xc424d49480, 0xc424725980, 0x27)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/host_checker_test.go:64 +0x45
created by github.com/TykTechnologies/tyk.fireEvent
	github.com/TykTechnologies/tyk/_test/_obj_test/event_system.go:205 +0x1e1
exit status 2
```

I can't reproduce locally, and that PR should not affect this test at all. Retrying the build fixed it.

This is very likely a race, as `go test -race` isn't happy at all with the host checker code.

**Comment by mvdan** [comment]
The underlying issue is that the global host checker does work in the background, but we make it do work forcefully too. This may end up in us receiving two event callbacks, if the machine is slow enough to let the global checker work through its sleeps.

We should either not run the global loop, or not force it to do the work we want ourselves. Not an easy decision; the former means we don't test the real code as much, and the latter means we have to refactor the sleep logic to not have the test take in the order of 5-15s.

I'm trying the latter at the moment, figuring out how to make it fast.
