### ISSUE TITLE
Webhook event kills gateway

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#821]
Branch: Master
Environment: On-prem

Reproduction steps:

1. Create webhook 
2. Enable webhook trigger for api definition (e.g when host is down)

Actual:
When webhook event triggers gateway exits with panic message  

Here is console log

```
tyk-gateway_1    | time="Jun 20 21:53:34" level=warning msg="[HOST CHECKER MANAGER] Host is DOWN: http://jajajajaj.com:8080/"
tyk-gateway_1    | panic: runtime error: invalid memory address or nil pointer dereference
tyk-gateway_1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6e8d04]
tyk-gateway_1    |
tyk-gateway_1    | goroutine 1571 [running]:
tyk-gateway_1    | panic(0xc39960, 0xc420014060)
tyk-gateway_1    | 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
tyk-gateway_1    | html/template.(*Template).escape(0x0, 0x0, 0x0)
tyk-gateway_1    | 	/usr/local/go/src/html/template/template.go:79 +0x44
tyk-gateway_1    | html/template.(*Template).Execute(0x0, 0x11da040, 0xc42081aa10, 0xc90100, 0xc4207ed650, 0x7, 0xc4203c3090)
tyk-gateway_1    | 	/usr/local/go/src/html/template/template.go:101 +0x2f
tyk-gateway_1    | main.(*WebHookHandler).CreateBody(0xc420754540, 0xd1ff29, 0x8, 0xc73fc0, 0xc4207a3a80, 0xc4207ed5c0, 0x27, 0xc4204c05c8, 0x53b540, 0xc4205516c0, ...)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/event_handler_webhooks.go:206 +0xd9
tyk-gateway_1    | main.(*WebHookHandler).HandleEvent(0xc420754540, 0xd1ff29, 0x8, 0xc73fc0, 0xc4207a3a80, 0xc4207ed5c0, 0x27)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/event_handler_webhooks.go:215 +0x86
tyk-gateway_1    | created by main.fireEvent
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/event_system.go:197 +0x17b
compose_tyk-gateway_1 exited with code 2
tyk-dashboard_1  | time="Jun 20 21:53:35" level=debug msg="Sending notification{NoticeDashboardZeroConf {\"DashboardConfig\":{\"Hostname\":\"172.18.0.5\",\"Po
```

**Comment by mvdan** [comment]
I understand this is a regression only in master, i.e. this doesn't happen on 2.3.x.

**Comment by ilijabojanovic** [comment]
@mvdan Yes, this is only visible on master. 2.3.X releases are ok!

**Comment by mvdan** [comment]
@ilijabojanovic please test my PR above - I believe it was simply a config issue, i.e. your template couldn't be loaded.

But Tyk at master doesn't error properly, so the template is let through even if it hasn't been loaded. That can cause a panic on a request later on.

With the PR, the gateway should give you a useful error. Note that even if the `template_path` doesn't exist or fails to load, a warning will be shown and it will fall back to `templates/default_webhook.json`.
