### ISSUE TITLE
Gateway may panic when loading duplicate APIs on stable

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#938]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42cfbb]
goroutine 405 [running]:
panic(0xccaae0, 0xc420010080)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.processSpec(0xc42266c280, 0xc420411b30, 0x11, 0xc4252ae140, 0xc4252ae160, 0xc4252ae180, 0xc4253d0480, 0xc4253d04e0, 0xc420411b30, 0xc42003eee8)
/src/github.com/TykTechnologies/tyk/api_loader.go:149 +0x5bb
main.loadApps.func1(0xc4252a9a30, 0xc4200218d8, 0xc4252ae140, 0xc4252ae160, 0xc4252ae180, 0xc4253d0480, 0xc4253d04e0, 0xc4253d0540, 0xc42266c280, 0x11, ...)
/src/github.com/TykTechnologies/tyk/api_loader.go:646 +0x10a
created by main.loadApps
/src/github.com/TykTechnologies/tyk/api_loader.go:649 +0x4eb
```

That line contains:

```
prev := (*ApiSpecRegister)[referenceSpec.APIID]
```

Which was added in 2.3.6 as part of deduplicating APIs when loading them.

I'm fairly sure the panic refers to `ApiSpecRegister` being nil, and not `referenceSpec`, as the latter is used a few lines further up in the codebase. And `ApiSpecRegister` can be nil sometimes, as a pointer to a map.

The good news is that this is already fixed in master, as we got rid of the double pointer. We should do something similar in stable.

**Comment by mvdan** [comment]
To clarify - the bug was introduced when backporting this feature to stable. We overlooked the situation with the pointer to the map.

**Comment by mvdan** [comment]
This bug only affects stable, and it was merged. GitHub won't close unless there's a merge in master, but there won't be one. Closing manually.
