### ISSUE TITLE
Not able to login into tyk dashboard from clean instalation on Local Standalone Cent-OS VM

### ISSUE THREAD

**Issue by vishalniit** [TykTechnologies/tyk#947]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
It gives me error while trying to login with given username & password
`[root@127 ~]# sudo /opt/tyk-dashboard/install/bootstrap.sh local.apigateway
Creating Organisation

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ORGID:
Adding new user

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
USER AUTH:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
NEW ID:
Setting password

DONE
====
Login at http://local.apigateway:3000/
User: 4qeelj9aww@default.com
Pass: test123
`

**What is the expected behavior?**
It should allow me to login for new user created using bootstrap.sh script.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Latest version used from documentation.

**Comment by lonelycode** [comment]
This isn't a bug. The bootstrap script must point at the dashboard and it's most likely that the dashboard isn't running or isn't reachable on that address. Can you post this to the community forum, we can help you there (https://community.tyk.io)
